### ISSUE TITLE
Latest image (first production image) missing some packages

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#101]
It looks like our first production image is missing some packages:

* iptraf
* zlib
* zlib-devel
* perl-TimeDate

Can this be fixed with a new image? If not, we'll need to cover this via RPM installation in YAML, which is less than desirable.

Please let us know, thanks!

**Comment by rjschwei** [comment]
As discussed in September via e-mail iptraf is no longer part of the distribution and is available from PackageHub. Also as discussed in that e-mail thread te documentation that refers to this requirement is likely outdated.

I will add the other packages to the image.

**Comment by jeffaco** [comment]
For posterity sake, can you mention the replacement repositorie(s) for `iptraf`?

As I recall, that was in SAP documentation for diagnostic purposes. But if we have another package that is in the distribution to do similar things, that should fill our needs.

Thanks!

**Comment by rjschwei** [comment]
wireshark
