### ISSUE TITLE
File /etc/idmapd.conf is not set properly

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#102]
File `/etc/idmapd.conf` is not set properly.

> Domain=localdomain and  Verbosity = 3 should set, this is a storage requirement and we create localdomain in storage side. If this is not set properly, then permissions to storage won't work properly.

Can you please insure that the file is set up properly?

**Comment by rjschwei** [comment]
Domain=localdomain is the default

I will change the verbosity to 3 in the image build setup
