### ISSUE TITLE
File /etc/fstab is not set up properly

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#103]
This may be a self-induced problem (perhaps I need to set options more carefully), but:

In `/etc/fstab`, we need SAP Hana recommended settings for NFS storage. This is required for Ansible playbooks and such, for example.

Each NFS mount should have the following specified in `/etc/fstab`:

```
rw,hard,timeo=600,vers=4,rsize=1048576,wsize=1048576,intr,noatime,lock 0 0
```

Is there a way, with existing grammer in YAML, to have this appended to each line?

What does SUSE suggest for this?

**Comment by rjschwei** [comment]
The yaml storage sections contains all you need.

`storage:
  -
    file_system: nfs
    min_size:  112G
    device: "10.250.21.12:/nfs/share"
    mount: "/mnt/foo"
    mount_options:
      - a
      - b
      - c`

The code will write all "mount_options" provided to the fstab file. If no options are provided the code writes "defaults"

**Comment by jeffaco** [comment]
We have a list of mount options in `/etc/fstab`, comma-separated. There's a fair number of them (perhaps 8-10, but I haven't counted).

Can this all be separated as a single option, comma-separated? Or is it better to list them out individually under `mount_options:`?

**Comment by jeffaco** [comment]
Ping.

I can supply comma-separated and see if it works, but I'd like to save the boot if I know it won't. And there's a lot of options, so the file isn't nearly as long with comma-separated options.

**Comment by rjschwei** [comment]
https://github.com/SUSE-Enceladus/azure-li-services/blob/master/azure_li_services/units/storage.py#L64

The code does no processing of the options. Obviously you have to resupply the options for every file system. Here is a quick and dirty example, run in Python3. All 3 configurations result in the same output

`import yaml

a = """storage:
   -
     file_system: nfs
     min_size:  112G
     device: "10.250.21.12:/nfs/share"
     mount: "/mnt/foo"
     mount_options:
       - a
       - b
       - c
"""

b = """storage:
   -
     file_system: nfs
     min_size:  112G
     device: "10.250.21.12:/nfs/share"
     mount: "/mnt/foo"
     mount_options:
       - a,b,c
"""

c = """storage:
   -
     file_system: nfs
     min_size:  112G
     device: "10.250.21.12:/nfs/share"
     mount: "/mnt/foo"
     mount_options:
       - a
       - b,c
"""

configs = [
    yaml.load(a),
    yaml.load(b),
    yaml.load(c)
]

for config in configs:
    print(','.join(config.get('storage')[0].get('mount_options')))
`
