### ISSUE TITLE
Required kernel options are not enabled as per SAP HANA notes

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#104]
While options can be enabled via a variety of mechanisms, we often use `/etc/sysctl.conf` for this.

The follow kernel options are recommended as per SAP HANA notes. They do not appear to be set in our LI image:

```
net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_syn_retries = 8
net.ipv4.tcp_window_scaling = 1
```

Can these please be set properly?

**Comment by rjschwei** [comment]
Adding an overlay file, /etc/sysctl.d/91-hana-basenet.conf to the image build
