### ISSUE TITLE
Need to have MTU settable on per NIC/VLAN basis

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#105]
Currently, we have no way to specify the MTU setting for a network card. This setting appears to be specified both in the `/etc/sysconfig/network/ifcfg-eth0` file and the VLAN specification file at `/etc/sysconfig/network/ifcfg-eth0.X` (where X is the number for the VLAN).

LI:

* eth0 must be set to MTU of 1500 because the default hardware MTU is 9000 and that’s not correct
    * This must be applied to both `/etc/sysconfig/network/ifcfg-eth0` and `/etc/sysconfig/network/ifcfg-eth0.X`
* The other ethernet interfaces are ok with the default of 9000 and we do not need to set them
 
VLI:

* The virtual interfaces for the client VLAN (whatever the customer’s client VLAN number is) must be set to 1500 explicitly
* The other interfaces must all be explicitly set to 9000

Since we know if we're generating YAML for LI for VLI, if we could specify what the MTU should be for the NIC and VLAN, that would cover us.

I like the idea of having grammar for this in the YAML file. That way, if some different SKU needs a different number, we can cover it in YAML generation.

**Comment by schaefi** [comment]
I'm going to work on this and will come up with a pull request. However you should keep in mind we together have agreed on a release before X-mas and put things into production. As Robert already pointed out the process for changes is now different. QA gets involved, approvals are needed, etc... When you are talking about a "blocker for a new image" what does that mean on your end with regards to the approved release we had before X-mas ?

**Comment by jeffaco** [comment]
For all prior issues raised (in the last batch), we'll either have to handle those via scripting at the end of O/S deployment (via scripts specified in YAML), or we'll need a new image that has these handled.

At this point, I'm hoping for a quick turn-around of a new image, and no new problems, so the next image will be our shipping image. If you can't produce that within the next several days, though (perhaps a week at the longest), then we'll need to develop scripts that will be tossed once we have a new image.

Does that clarify where we are?

**Comment by jeffaco** [comment]
Oh yuck, that's really unfortunate. Okay, can we have a new image then with everything except MTU? That way, there's less that we need to script for. Thanks.

**Comment by jeffaco** [comment]
So this is already pushed to master. Now that we're in production, what's the process to get an image that includes this fix?

**Comment by schaefi** [comment]
I had a conversation with Robert about this a few minutes before. We will short circuit the process as an exception this time. I've merged the code and we will build you a new image bypassing the usual maintenance process. Robert will come back to you with more details. I expect the image build to be done by tomorrow. Today it's late at my time zone and I need some sleep ;)
