### ISSUE TITLE
SElinux should be disabled as per SAP HANA requirement

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#107]
SELinux should be disabled when using HANA. This does not appear to be the case with our images.

**Comment by rjschwei** [comment]
Hmm,

Can you please provide more details on this? By default selinux is disabled and we do not add the necessary parameters to the kernel command line or GRUB configuration to enable it.

SLES docs for setting up SELinux https://www.suse.com/documentation/sles-12/book_security/data/sec_selinux_install.html

However, I will add /etc/selinux/config to the image build with
`SELINUX=disabled`
as content.

**Comment by schaefi** [comment]
@jeffaco please clarify. I saw Robert already explicitly disabled SELINUX in a config file. Not sure if you want to boot the image in another selinux policy which would mean a new boot parameter.

Also don't understand why this is an issue. It would also be good to clarify for which target this applies: LI / VLI

Thanks

**Comment by jeffaco** [comment]
This applies to both LI and VLI.

The person checking the system decided that SELINUX was enabled and stated it should not be. We did not check his answers. It sounds like, since there are many ways that SELINUX can be disabled, he simply didn't see what he expected.

>However, I will add /etc/selinux/config to the image build with
> SELINUX=disabled
>as content.

This is good for clarity, and I would like this change. Other than that, this issue is resolved.

Was the above chance actually made to the `/etc/selinux/config` file? If so, feel free to close this issue. Thanks!
