### ISSUE TITLE
NetApp configuration file /etc/sysctl.d/91-hana-netapp.conf is not quite right

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#108]
My mistake on this - sorry!

In issue #86, I asked you to add NetApp configuration file `/etc/sysctl.d/91-hana-netapp.conf`.

I did want that file, but apparently that file is just for **VLI**, not for LI.

Can you please modify code to only add this file for VLI? Thanks.

**Comment by rjschwei** [comment]
If this is machine type specific we should consider adding the data as a "static" file to the initialization code. If that's what we want to do, @schaefi thoughts?, then we'll want to file another bug in bugzilla. For now I will remove the file from the image build.

Content of file being removed:

`
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.rmem_default = 16777216
net.core.wmem_default = 16777216
net.core.optmem_max = 16777216
net.ipv4.tcp_rmem = 65536 16777216 16777216
net.ipv4.tcp_wmem = 65536 16777216 16777216`

**Comment by schaefi** [comment]
I think it falls into the category of the static image pre configuration which doesn't need code to become available. So what you did with just removing /etc/sysctl.d/91-hana-netapp.conf from the overlay tree looks good to me.

Regarding VLI I'm still under the impression that we need two image builds on our side. One for LI and one for VLI. Even though Jeff said VLI will use the same LUN concept to boot there might be differences which we don't want to handle all in services code here. This netapp setup is just one example and I think there might be more. Thinking of e.g the kernel crash dump default values. Those are set on the kernel command line and we invented a nice way to set different values but if changes a kexec reboot is required. I could imagine the Very Large Instance type will need other defaults than the Large Instance type and to apply those two image descriptions would be needed.

I'm just guessing here and I would love if everything can be clumped together in one image build serving both targets but I doubt it would be a good idea. While the netapp setup would be easy to handle by the machine type there are other setup steps which are not that easy.

**Comment by jeffaco** [comment]
I know that you guys are hesitant to have two image builds. From my point of view, the two are uniquely different (we'd never boot a VLI build on an LI system and visa-versa), so I'm kind of indifferent. But I do see cases where there may be two different layouts of files on the two types of systems. Given this, perhaps handling this in code allows us to keep one image build instead of two (since the code knows what type of system it's generating for)?

Yes, the LUN boot mechanism is identical. But networking is different (although this is a bad example, as this is laid out in code), the kernel boot line parameters are likely different, certain setup files will be different, etc. Some of this MUST be handled in code, and some of it may be handled in code or may be handled by separate images.

Which way we go, as far as I'm concerned, is up to you guys. Keeping track of two sets of images vs. one set of images (per release) isn't really a big deal for me. Either way, I need to keep track of multiple images (one or more for each O/S version, one or more for each O/S vendor - SuSE vs. RedHat), etc. Branching that out into LI vs. VLI, up front, is fine. Or keeping one per O/S version is fine too.

**Comment by rjschwei** [comment]
> I know that you guys are hesitant to have two image builds.

That's somewhat of a mis-representation. If we need a second image build we'll do it. I am just not certain we have come to that conclusion yet.

> (we'd never boot a VLI build on an LI system and visa-versa)

Until it happens the first time ;)

The example @schaefi provided for the crash dump configuration is a good example showing why 2 image builds would be preferable if indeed we need different configs for the crash dump.

> Keeping track of two sets of images vs. one set of images (per release) isn't really a big deal for me

I'll remind you of this when we are in full production and have SLES 12 SP3 & 4 and SLES 15 & SP1 images and all images need to be refreshed at the same time because of some security issue ;)

**Comment by jeffaco** [comment]
>I'll remind you of this when we are in full production and have SLES 12 SP3 & 4 and SLES 15 & SP1 images and all images need to be refreshed at the same time because of some security issue ;)

Yeah, I can see there will be a lot of images. My hope is that, by the time SLES 15 SP1 comes around, we'll have enough automation in place to make the process easier. But what I hope, and what I get, are often dramatically different! ☹️

**Comment by schaefi** [comment]
> That's somewhat of a mis-representation. If we need a second image build we'll do it. I am just not
> certain we have come to that conclusion yet

Issue #94 also points to two image descriptions. I think we should make the decision and create a VLI image description at least in our devel space. I volunteer to set that up if we all agree

**Comment by rjschwei** [comment]
I agree we now have 3 configuration settings that are better handled with a separate image setup rather than trying to work around what is probably inevitable with hacks in code.

So let's get the VLI image setup in the Devel space so we can at least keep track of these changes and do not forget them.

**Comment by schaefi** [comment]
> Can you please modify code to only add this file for VLI? Thanks.

done, now to the new image builds created for VLI
