### ISSUE TITLE
wicked and wickedd-nanny

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#112]
On an escalation, `wicked` and `wickedd-nanny` is coming up. I recall discussing this, but I can't find anything about it in issues. So it must have been discussed in E-Mail (I guess).

On bare metal systems where network configuration should not be changing ad-hoc, should we be using `wickedd-nanny`? My understanding is that `wickedd-nanny` is primarily involved with ad-hoc changes to network configuration (i.e. new wireless networks, hot plug devices, etc). None of that should ever be an issue in a server environment. Does `wickedd-nanny` bring value to us? Could it cause problems for us?

I'm much less clear on `wicked` itself. Is `wicked` a mandatory part of the system? If not, do we need it? What value does it bring to us in a bare-metal environment?

**Comment by rjschwei** [comment]
wicked and it's components manage the network interface setup. The initialization code (azure-li-services) writes the ifcfg-* files and according to those configurations wicked will setup the network interfaces.

In short:
- yes you need wicked
- no wickedd-nanny should not create any problems.
