### ISSUE TITLE
Gen4 VLI support bonding network setup

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#114]
We had a change two weeks ago for network configuration in Gen4, and I was not advised of that. So, this weekend, when I finally got access to Gen4 resources and tried to deploy an O/S, I couldn't get the network up.

In Gen4 (currently we don't have a way in YAML to differentiate between Gen3 and Gen4), we now use bonded interfaces for resiliency. The underlying fabric will automatically bond, but the decision was made to bond at the O/S level as well to try and protect against O/S network configuration problems (with a single interface).

So, a few questions:

1. Any chance of getting a BETA version of the O/S with this change that we can start experimenting with?
1. I know that since the code GA'ed, it will take much longer for changes to be made. Estimate for a new release that's fully supported?

Thanks so much.

Attached is sample output from a working blade in Gen4 LI:

```
Sollabdsm32:/etc/sysconfig/network # for i in ifcfg-* ifroute*; do echo "---------- File: $i ---------"; cat $i; done
---------- File: ifcfg-bond0 ---------
NAME=bond0
DEVICE=bond0
BOOTPROTO=none
STARTMODE=onboot
BONDING_MASTER=yes
BONDING_SLAVE0=eth0
BONDING_SLAVE1=eth1
BONDING_MODULE_OPTS="mode=active-backup miimon=100"
ONBOOT=yes
MTU=9000
---------- File: ifcfg-bond1 ---------
NAME=bond1
DEVICE=bond1
BOOTPROTO=none
STARTMODE=onboot
BONDING_MASTER=yes
BONDING_SLAVE0=eth2
BONDING_SLAVE1=eth3
BONDING_MODULE_OPTS="mode=active-backup miimon=100"
ONBOOT=yes
MTU=9000
---------- File: ifcfg-bond2 ---------
NAME=bond2
DEVICE=bond2
BOOTPROTO=none
STARTMODE=onboot
BONDING_MASTER=yes
BONDING_SLAVE0=eth4
BONDING_SLAVE1=eth5
BONDING_MODULE_OPTS="mode=active-backup miimon=100"
ONBOOT=yes
MTU=9000
---------- File: ifcfg-bond3 ---------
NAME=bond3
DEVICE=bond3
BOOTPROTO=none
STARTMODE=onboot
BONDING_MASTER=yes
BONDING_SLAVE0=eth6
BONDING_SLAVE1=eth7
BONDING_MODULE_OPTS="mode=active-backup miimon=100"
ONBOOT=yes
MTU=9000
---------- File: ifcfg-bond4 ---------
NAME=bond4
DEVICE=bond4
BOOTPROTO=none
STARTMODE=onboot
BONDING_MASTER=yes
BONDING_SLAVE0=eth8
BONDING_SLAVE1=eth9
BONDING_MODULE_OPTS="mode=active-backup miimon=100"
ONBOOT=yes
MTU=9000
---------- File: ifcfg-bond5 ---------
NAME=bond5
DEVICE=bond5
BOOTPROTO=none
STARTMODE=onboot
BONDING_MASTER=yes
BONDING_SLAVE0=eth10
BONDING_SLAVE1=eth11
BONDING_MODULE_OPTS="mode=active-backup miimon=100"
ONBOOT=yes
MTU=9000

---------- File: ifcfg-eth0 ---------
NAME=eth0
DEVICE=eth0
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug
---------- File: ifcfg-eth1 ---------
NAME=eth1
DEVICE=eth1
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug
---------- File: ifcfg-eth10 ---------
NAME=eth10
DEVICE=eth10
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug
---------- File: ifcfg-eth11 ---------
NAME=eth11
DEVICE=eth11
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug

---------- File: ifcfg-eth2 ---------
NAME=eth2
DEVICE=eth2
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug
---------- File: ifcfg-eth3 ---------
NAME=eth3
DEVICE=eth3
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug
---------- File: ifcfg-eth4 ---------
NAME=eth4
DEVICE=eth4
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug

---------- File: ifcfg-eth5 ---------
NAME=eth5
DEVICE=eth5
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug
---------- File: ifcfg-eth6 ---------
NAME=eth6
DEVICE=eth6
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug

---------- File: ifcfg-eth7 ---------
NAME=eth7
DEVICE=eth7
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug
---------- File: ifcfg-eth8 ---------
NAME=eth8
DEVICE=eth8
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug
---------- File: ifcfg-eth9 ---------
NAME=eth9
DEVICE=eth9
MTU=9000
ONBOOT=YES
BOOTPROTO=NONE
STARTMODE=hotplug
---------- File: ifcfg-lo ---------
# Loopback (lo) configuration
IPADDR=127.0.0.1/8
NETMASK=255.0.0.0
NETWORK=127.0.0.0
STARTMODE=nfsroot
BOOTPROTO=static
USERCONTROL=no
FIREWALL=no
---------- File: ifcfg-vlan250 ---------
VLAN_ID=250
BOOTPROTO=static
IPADDR=10.60.0.32
NETMASK=255.255.255.0
MTU=1500
ETHERDEVICE=bond0
ONBOOT=YES
VLAN=yes
STARTMODE=auto
---------- File: ifcfg-vlan251 ---------
VLAN_ID=251
BOOTPROTO=static
IPADDR=10.20.251.52
NETMASK=255.255.255.0
MTU=9000
ETHERDEVICE=bond1
ONBOOT=YES
VLAN=yes
STARTMODE=auto

---------- File: ifcfg-vlan252 ---------
VLAN_ID=252
BOOTPROTO=static
IPADDR=10.20.252.52
NETMASK=255.255.255.0
MTU=9000
ETHERDEVICE=bond2
ONBOOT=YES
VLAN=yes
STARTMODE=auto
---------- File: ifcfg-vlan253 ---------
VLAN_ID=253
BOOTPROTO=static
IPADDR=10.20.253.52
NETMASK=255.255.255.0
MTU=9000
ETHERDEVICE=bond3
ONBOOT=YES
VLAN=yes
STARTMODE=auto
---------- File: ifcfg-vlan254 ---------
VLAN_ID=254
BOOTPROTO=static
IPADDR=10.20.254.52
NETMASK=255.255.255.0
MTU=9000
ETHERDEVICE=bond4
ONBOOT=YES
VLAN=yes
STARTMODE=auto

---------- File: ifcfg-vlan255 ---------
VLAN_ID=255
BOOTPROTO=static
IPADDR=10.20.255.52
NETMASK=255.255.255.0
MTU=9000
ETHERDEVICE=bond5
ONBOOT=YES
VLAN=yes
STARTMODE=auto
---------- File: ifroute-vlan250 ---------
default 10.60.0.1 - vlan250
Sollabdsm32:/etc/sysconfig/network # 
```

**Comment by jeffaco** [comment]
This will be different for Gen3 and Gen4. So I'm asking: Can we have the setup code have a flag for Gen4 and, if set, set up bonding (as per above) during the network setup?

We could have a separate image (with bonding built in, but setting up IP addresses during the rest of network setup), but then we have separate images. I think, with some Python work, we can remain at a single image for Gen3 vs. Gen4 HLI.

So my thinking is, modify the YAML like this:

Old:

```
version: "20180614"
instance_type: LargeInstance
sku: "SR92"
hostname: "azurehost1"
```

New:

```
version: "20180614"
instance_type: LargeInstance
generation: 4
sku: "SR92"
hostname: "azurehost1"
```

Then, given the generation of the hardware, the Python code can make appropriate choices.

Thoughts?

**Comment by rjschwei** [comment]
I am not opposed to having knowledge of the HW generation in the initialization code, however I would not, based on this knowledge do "magic" network configuration. I think the bonding configuration belongs into the YAML config file and should not be intrinsically known to the initialization code based on some flag.

IMHO the HW iteration flag would be useful for driver install purposes for example.

**Comment by jeffaco** [comment]
I'm fine with that. What do you suggest for YAML syntax to create bonding?

Note that, in this particular case, the underlying hardware has 12 ethernet ports, 6 bonds, and 6 VLANs spread across those bonds.

Thanks.

**Comment by jeffaco** [comment]
Due to timing for this change, and the fact that it doesn't really give us more resiliency (since the underlying fabric already gives us that for UCS), we decided to go back to standard (non-bonded) networking for LI.

We still care about bonding, but only for VLI. VLI is on different hardware where we need to bond ourselves to get resiliency. That gives us more time.

This issue will need to be resolved before first generation of a VLI image. Note that in Gen3, we use bonding, while in Gen4 we moved to active/passive (as the above Gen4 files show). Given that we won't support VLI in Gen3, the image probably needs only support active/passive.

**Comment by schaefi** [comment]
ok, after the fire drill mode for pressing kiwi issues is done now and resolved I'll start to work on VLI this week. Regarding this issue we want bonding support. Here is my suggestion to handle that in the yaml

```yaml
networking:
  -
    interface: eth0
    mtu: 9000

  -
    interface: eth1
    mtu: 9000

  -
    interface: bond0
    vlan: 250
    ip: X.X.X.X
    gateway: X.X.X.X
    bonding_slaves:
      - eth0
      - eth1
    bonding_options:
      - active-backup
      - miimon=100
```

So we are adding ```bonding_slaves``` and ```bonding_options``` and the code will care for creating all required files.

**Comment by schaefi** [comment]
We don't need to make this LI / VLI specific. It's just a network setup task. We did not had support for bonding constructs but will add it now. The way you use it in the configuration is on your side and imho transparent to any instance type

**Comment by rjschwei** [comment]
> We don't need to make this LI / VLI specific. It's just a network setup task. We did not had support for bonding constructs but will add it now. The way you use it in the configuration is on your side and imho transparent to any instance type

+1

**Comment by schaefi** [comment]
I'm now setting up the image build including the changes. An e-mail including a summary of the changes and what you need to care for on the yaml format will follow tomorrow. So you should have a new image for testing at hand before you meet with Robert ;)
