### ISSUE TITLE
SLES 12 SP4 doesn't resize disk partition properly

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#117]
Here is a space snapshot for `SLES 12 SP3`:

```
Sollabdsm31:~ # fdisk -l /dev/mapper/3600a09803830423066244d6f302d4454
Disk /dev/mapper/3600a09803830423066244d6f302d4454: 61 GiB, 65504542720 bytes, 127938560 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 65536 bytes
Disklabel type: dos
Disk identifier: 0x7d1e316d

Device                                              Boot     Start       End   Sectors Size Id Type
/dev/mapper/3600a09803830423066244d6f302d4454-part1           2048 123764759 123762712  59G 83 Linux
/dev/mapper/3600a09803830423066244d6f302d4454-part2      123766784 127925594   4158811   2G 82 Linux s
Sollabdsm31:~ # 
Sollabdsm31:~ # df -h /
Filesystem                                           Size  Used Avail Use% Mounted on
/dev/mapper/3600a09803830423066244d6f302d4454-part1   59G  9.2G   46G  17% /
Sollabdsm31:~ # 
```

Here is a space snapshot for `SLES 12 SP4`:

```
azurehost2:~ # fdisk -l /dev/mapper/3600a09803830362f6e2b48516b525758
Disk /dev/mapper/3600a09803830362f6e2b48516b525758: 77 GiB, 82688606208 bytes, 161501184 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 65536 bytes
Disklabel type: dos
Disk identifier: 0x49a1e4bc

Device                                              Boot  Start     End Sectors  Size Id Type
/dev/mapper/3600a09803830362f6e2b48516b525758-part1 *      2048  616447  614400  300M 83 Linux
/dev/mapper/3600a09803830362f6e2b48516b525758-part2      616448 7362559 6746112  3.2G 83 Linux
azurehost2:~ # 
azurehost2:~ # 
azurehost2:~ # df -h /
Filesystem                                           Size  Used Avail Use% Mounted on
/dev/mapper/3600a09803830362f6e2b48516b525758-part2  3.3G  2.5G  759M  77% /
azurehost2:~ # 
```

The important information here:

Operating System | LUN Size | Size of / Partition
------------------ | --------- | -----------------
SP3 | 61G | 59G
SP4 | 77G | 3.3G

We have two SP4 nodes, both have the same problem.

**Comment by schaefi** [comment]
I need the log file to check what happened. Could you boot the machine with the boot option

```
rd.debug rd.kiwi.debug
```

and after the machine has been booted send the log file

```
/run/initramfs/log/boot.kiwi
```

Thanks

**Comment by jeffaco** [comment]
I'm not completely square what you need. Are you saying: Redeploy the machine with those boot options? Or can I just boot an existing machine exhibiting the failure with the above boot options?

I don't mess with kernel boot options much, so if you could send detailed instructions (or refer me to docs), that would be great. Thanks.

**Comment by schaefi** [comment]
Sorry for not being clear. I meant: Redeploy the machine with those boot options

**Comment by schaefi** [comment]
@jeffaco any news here ?

**Comment by jeffaco** [comment]
Not yet, sorry. In the middle of an office move, don't have a home base until tomorrow. I'll get to this as soon as I can, sorry for the delay.

**Comment by jeffaco** [comment]
Okay, I booted the system, here's the [boot.kiwi log file](https://github.com/SUSE-Enceladus/azure-li-services/files/2887148/boot.kiwi.log).

I used the same image to test the networking changes, and that didn't go well. I'll update that issue with results from that.

Any idea why this image isn't extending properly (while SP3 is fine)?

**Comment by schaefi** [comment]
Thanks for the log, very helpful.

I hope you have the machine still running because I need another information. I think I found the problem but I need to verify that this is really the case. Could you call the following on the machine you have booted (as root)

```
lsblk -p -n -r -s -o NAME,TYPE /dev/dm-3
```

and also

```
lsblk
```

Thanks

**Comment by schaefi** [comment]
> Any idea why this image isn't extending properly (while SP3 is fine)?

Starting with SP4 the move to the dracut boot system has been finished. Before that the boot initrd was a custom kiwi specific invention. With dracut all is based on modules. The current image does not include the multipath module and I guess this is causing the trouble. However I need to investigate further details and as I can't access the machine I might ask some dump questions

**Comment by schaefi** [comment]
This is a problem of the kiwi appliance builder and I will handle the defect in

* https://github.com/SUSE/kiwi/issues/954

**Comment by schaefi** [comment]
Bugzilla issue to track the update for SLES has been opened too:

* https://bugzilla.suse.com/show_bug.cgi?id=1126283

**Comment by schaefi** [comment]
Potential fix for the issue here:

* https://github.com/SUSE/kiwi/pull/955

I need to rebuild your image with the kiwi builder containing that patch. I'll keep this open until a new image is available for testing. The information I asked for are still important to me, just in case the first patch did not fix the issue. Thanks

**Comment by jeffaco** [comment]
@schaefi You asked for output from `lsblk` commands. I had an image of the O/S (I booted the O/S into an alternate LUN and saved that so I could restore the original O/S). So, while I could run your commands, from the O/S point of view I needed to shut down and restart the O/S to get those. Hopefully this won't disturb the results of your commands. If they do, let me know and I'll deploy again and then collect the results.

Just so it doesn't get lost in the noise: How come we didn't get error results written to the LUN in this case? It clearly had access to the LUN since it set up accounts and stuff.

Output from `lsblk -p -n -r -s -o NAME,TYPE /dev/dm-3`:

```
/dev/sda disk
/dev/sdg disk
/dev/sdm disk
/dev/sds disk
/dev/mapper/3600a098038304179392b4d6c6e2f496e mpath
/dev/mapper/3600a098038304179392b4d6c6e2f496e-part1 part
```

Output from `lsblk` is much longer, and can be found [here](https://github.com/SUSE-Enceladus/azure-li-services/files/2890462/lsblk-full.txt).

Let me know what else you need, I'll do my best to provide.

**Comment by schaefi** [comment]
> Just so it doesn't get lost in the noise: How come we didn't get error results 

I'm pretty sure you have error results, but systemd shows all data only if you fetch them as root. So can you confirm the following:

* su root
* systemctl status -l ```service_name```

provides detailed information ?

**Comment by schaefi** [comment]
Thanks for the lsblk output, that confirmed my assumption. The fix for kiwi has made its way to the master branch. I'll let you know when there is a new image.

**Comment by jeffaco** [comment]
No, I guess I wasn't clear.

Yes, I got error status from the console. But there was nothing in the LUN (not success, not failure, not logs - nothing in terms of status). That's what I'm asking about ...

**Comment by schaefi** [comment]
> But there was nothing in the LUN

Hmm, I checked the code and couldn't find a problem there. write_service_log() is called as part of the cleanup service. I'll take this issue apart from this one because the intermix is not a good thing

**Comment by schaefi** [comment]
The bug in kiwi has been fixed. I'll do testing in my system but regarding multipath this is only a poor test. So we will send you a new image for testing and if that doesn't resolve the resize issue please re-open. Thanks
