### ISSUE TITLE
Ability to disable certain services in YAML

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#118]
Can we have the ability to disable certain services in YAML, if needed?

For example (from our operations folks):

>nscd service:
>
>nscd service is turning off current golden images, nscd  is an caching daemon implements a cache for name service requests, there is chances on impacting performances, in particular it keeps toomany open files till possibly stop the instance for the error like “VFS: file-max limit” .

I was thinking of just asking you to disable that service in our image. But should we have something more generic instead?

Perhaps something like:

```
services:
  disable:
    -nscd
    -someotherservice
```

Should we have something generic like this, or just have you modify the image? If modifying the image, please disable service `nscd`, thanks.

**Comment by rjschwei** [comment]
That's an image modification issue. I'll make the appropriate modifications.

**Comment by rjschwei** [comment]
Images modified and submitted to product build project.
