### ISSUE TITLE
Configure the iscsi SBD device

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#119]
From our operations team:

>For HSR, we do ISCSI Configuration in OS for SBD configuration. Currently this option us not available in yaml Can we add it this feature in next release ?

What this is about is configuring the [SBD device](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/ha-setup-with-stonith). Basically, we'd like to set up the `/etc/iscsi/initiatorname.iscsi` file appropriately, as well as the `/etc/iscsi/iscsid.conf` file. We're trying to get down to doing everything in section(s) 1 and 2.

This is only for HSR clusters. So this should be optionally specified in YAML file. Currently, for new customers that use HSR clusters, we set up the machine up front for the customer. With the new deployment, we have no way to do this.

Maybe something like:

```
stonith:
  initiatorname: t090xyzzysid4
  ipaddress: a.b.c.d
```

Is this something that can be done if needed?

**Comment by jeffaco** [comment]
In retrospect, the naming convention for the initiator is just that: a naming convention. How about something like:

```
stonith:
  initiatorname: t090xyzzysid4
  ipaddress: a.b.c.d
  sbd-device: <SBD Device Name>
```

Naming conventions can change and shouldn't be hard-coded if possible ...

**Comment by rjschwei** [comment]
Yes can be done. This is a new service, while the configuration is done before the network is up the connection can only be initiated after the network is online, Thus we might consider running the new service after wicked is done, then doe the configuration and start the iscsi connection.

Filed bugs in bugzilla: 1125372, 1125372

**Comment by schaefi** [comment]
@jeffaco I was just reading the documentation about the SBD device setup since this is new stuff for me. A couple questions:

1. The proposed changes to ```/etc/iscsi/iscsid.conf``` are

     * node.session.timeo.replacement_timeout=5
     * node.startup = automatic.

     This looks static to me and I would put that file as an overlay to the image description, or is it expected to exist only on demand ? Are the changes the only ones you need or does the iscsi daemon  config involve other settings too ? Maybe you can just send the file as you need it

2.  Contents of ```/etc/iscsi/initiatorname.isci```

    You suggested the initiatorname attribute which I would use 1:1 in the setup of ```InitiatorName=value``` I was wondering what the purpose of ipaddress and sbd-device is ?
    This information would be used in the discovery and sbd enablement calls:
    ```iscsiadm -m discovery ... <ip>``` , ```sbd -m <device>``` I do not expect that setup steps to be in our court or am I mistaken and the suggested setup covers a lot more than just writing config files ?

Thanks

**Comment by jeffaco** [comment]
I'm not sure what would happen to iscsi if we configured part of iscsi (`/etc/iscsi/iscsid.conf`), without configuring the rest of it. It's just not a use case we've done, so I'm not sure what sort of adverse affects that may have.

Also, in original message: Note: /etc/iscsi/initiatorname.isci  file name is wrong and it should be /etc/iscsi/initiatorname.iscsi. I will edit the original posting with this correction.

As for your second question, the ask was that your service does everything through step 2 in [the instructions](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/ha-setup-with-stonith). But in further discussion, I'm going to hand this off to Raghu, he will respond here to more precisely answer your questions. He's more deeply involved with the iscsi stuff.

Expect to hear back from Raghu shortly.

**Comment by rkrishna12** [comment]
@schaefi To address question 2:

As Jeff mentioned, we are expecting your service to issue the iscsiadm, sbd calls. One correction on the InitiatorName is that you add the SUSE prefix to the value that we provide you. Using Jeff's example, the end result should be:  ```InitiatorName=iqn.1996-04.de.suse:01:t090xyzzysid4```

The ipaddress field specifies the IP address of the iSCSI target, and should be used for this command: ```iscsiadm -m discovery ... <ip>```. 

The actual sbd device name is dynamic (will not be provided in the yaml) and should be determined using the ```fdisk -l``` command mentioned in the instructions.

**Comment by schaefi** [comment]
ok, that looks straight forward then. Thanks

**Comment by schaefi** [comment]
I think I have all info to do the implementation. I'll start on this by early next week.

**Comment by schaefi** [comment]
The implementation is almost done, however I came across on issue.

The documentation states:

> To get the device name run the command fdisk –l. Run it on both the nodes. Pick the device with the size of 178 MiB.

While this might be ok from a manual process it seems not advisable from an automation perspective.
Selecting a storage device by its capacity sounds not reliable to me. Reliable ways to select a storage device are:

* by-id
* by-uuid
* by-label
* by-path
* by-partlabel
* by-partuuid

I usually prefer UUID's. Is it possible that we provide a clear storage identification along with the initiatorname/ip in the yaml configuration and select the device properly ?

Thanks

**Comment by schaefi** [comment]
@rkrishna12 @jeffaco see my question above. Thanks much

**Comment by schaefi** [comment]
For reference, current coding is here: https://github.com/SUSE-Enceladus/azure-li-services/tree/iscsi_sbd

**Comment by jeffaco** [comment]
Raghu is out sick. A bunch of people are, I think some sort of bug is making the rounds.

I've sent him E-Mail - he should respond when he feels up to it.

**Comment by schaefi** [comment]
@jeffaco needless to say I can't finish this until we have sorted out the issue on the device selection. I couldn't convince my fingers to code the selection by storage size. Thus setting the blocked label for the moment. Would be great if you and/or @rkrishna12 get in touch with me as soon as possible. Thanks

**Comment by rkrishna12** [comment]
@schaefi, I will take a look at this one today. Unfortunately I was not involved in the initial design of that work flow, but will ascertain if we can use a more reliable indicator.

**Comment by schaefi** [comment]
any news ?

**Comment by rkrishna12** [comment]
I have a potential solution using /dev/disk/by-path. 

Example device name which can be derived from the output of the iscsiadm commands: 
ip-10.250.53.31:3260-iscsi-iqn.1992-08.com.netapp:sn.ad7fde85db0b11e7a8ef00a098988a9b:vs.27-lun-1

I verified this in one of our test environments. I will ensure this generically works in our prod environment and report back in next couple of days.

**Comment by rkrishna12** [comment]
@schaefi, I have confirmed that we can use the device under /dev/disk/by-path derived from the output of the iscsiadm commands. 

---
Here is an example sequence:

ISCSI IP address: 10.20.253.31

\> iscsiadm -m discovery -t st -p 10.20.253.31:3260

**Output:**
>        10.20.253.31:3260,1054 iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6
>        10.20.253.42:3260,1057 iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6
>        10.20.253.32:3260,1056 iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6
>        10.20.253.41:3260,1055 iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6   

\> iscsiadm -m node -l

**Output:**
> Login to [iface: default, target: iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6, portal: 10.20.253.42,3260] successful.
> Login to [iface: default, target: iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6, portal: 10.20.253.32,3260] successful.
> Login to [iface: default, target: iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6, portal: 10.20.253.31,3260] successful.
> Login to [iface: default, target: iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6, portal: 10.20.253.41,3260] successful.

**Device to target:**
> /dev/disk/by-path/ip-10.20.253.31:3260-iscsi-iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6-lun-0

**The template is this:**
> /dev/disk/by-path/ip-__\<ISCSI IP Address\>__:__\<Port\>__-iscsi-__\<Target name from output\>__-lun-0

**Comment by schaefi** [comment]
Great, thanks for the information :+1:

**Comment by jeffaco** [comment]
Please be careful about merging this. I'd like to get a Gen3 image based on the commit just prior to this so all of our images are consistent as of a point in time. Thanks!

**Comment by jeffaco** [comment]
For completeness, I created a bugzilla entry for this.

We would like the change in all images.

Entered in Bugzilla, [ID 1130714](https://bugzilla.suse.com/show_bug.cgi?id=1130714).

**Comment by jeffaco** [comment]
Hmm, I'm having a problem testing this image, deployment fails with an error:

```
azurehost1:/etc/sysconfig/network # systemctl status -l azure-li-system-setup
* azure-li-system-setup.service - System Setup of Azure Li/VLi machine
   Loaded: loaded (/usr/lib/systemd/system/azure-li-system-setup.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Tue 2019-04-09 20:57:54 UTC; 2h 9min ago
 Main PID: 41648 (code=exited, status=1/FAILURE)

Apr 09 20:57:54 azurehost1 azure-li-system-setup[41648]: Traceback (most recent call last):
Apr 09 20:57:54 azurehost1 azure-li-system-setup[41648]:   File "/usr/bin/azure-li-system-setup", line 9, in <module>
Apr 09 20:57:54 azurehost1 azure-li-system-setup[41648]:     load_entry_point('azure-li-services==1.1.28', 'console_scripts', 'azure-li-system-setup')()
Apr 09 20:57:54 azurehost1 azure-li-system-setup[41648]:   File "/usr/lib/python3.4/site-packages/azure_li_services/units/system_setup.py", line 91, in main
Apr 09 20:57:54 azurehost1 azure-li-system-setup[41648]:     raise AzureHostedException(system_setup_errors)
Apr 09 20:57:54 azurehost1 azure-li-system-setup[41648]: azure_li_services.exceptions.AzureHostedException: [AzureHostedCommandException('iscsiadm: stderr: iscsiadm: cannot make connection to 10.250.53.31: No route to host\niscsiadm: cannot make connection to 10.250.53.31: No route to host\niscsiadm: cannot make connection to 10.250.53.31: No route to host\niscsiadm: cannot make connection to 10.250.53.31: No route to host\niscsiadm: cannot make connection to 10.250.53.31: No route to host\niscsiadm: cannot make connection to 10.250.53.31: No route to host\niscsiadm: connection login retries (reopen_max) 5 exceeded\niscsiadm: Could not perform SendTargets discovery: encountered connection failure\n, stdout: (no output on stdout)',)]
Apr 09 20:57:54 azurehost1 systemd[1]: azure-li-system-setup.service: Main process exited, code=exited, status=1/FAILURE
Apr 09 20:57:54 azurehost1 systemd[1]: Failed to start System Setup of Azure Li/VLi machine.
Apr 09 20:57:54 azurehost1 systemd[1]: azure-li-system-setup.service: Unit entered failed state.
Apr 09 20:57:54 azurehost1 systemd[1]: azure-li-system-setup.service: Failed with result 'exit-code'.
Warning: azure-li-system-setup.service changed on disk. Run 'systemctl daemon-reload' to reload units.
azurehost1:/etc/sysconfig/network #
```

Network must be started first to reach that IP. Is the dependency of the `azure-li-system-setup` configured to require the network first?

**Comment by schaefi** [comment]
> Network must be started first to reach that IP

damn, I knew something was missing. Thanks for testing. I'll fix this and will provide a new testing image

@jeffaco I assume the sas url for fetching the testing image has worked, otherwise you wouldn't have been able to test the SBD device setup. So probably the question is not really relevant, but did you got my e-mails with the sas url from the suselitestingimages storage account ? Did everything work well for you regarding the fetching from there ? Is that process working well for you and the team ? I also plan to keep a max of 3 testing image builds in that account. For the production ready images we continue to use the susepublishedimages account

**Comment by jeffaco** [comment]
@schaefi I just clicked the link to grab the image, didn't think much about it. That makes the account that the link goes to rather transparent. I do now save the link but, frankly, for test purposes, once we have a new test image, older images aren't terribly relevant. As a result, I think saving 3 testing images is just fine.

Does that answer your question?
