### ISSUE TITLE
Service log file not written on lun

### ISSUE THREAD

**Issue by schaefi** [SUSE-Enceladus/azure-li-services#124]
> Yes, I got error status from the console. But there was nothing in the LUN (not success, not failure, not
> logs - nothing in terms of status). That's what I'm asking about ...

@jeffaco The cleanup service should have handled that. Thus could you check the status of that service

```
su root
systemctl status -l azure-li-cleanup
```

Thanks

**Comment by jeffaco** [comment]
Not a lot of information here. I'm not sure if I'm being fat-fingered, but I don't see what I'm doing wrong. Running from the `root` account:

<img width="913" alt="screen shot 2019-02-25 at 8 30 27 am" src="https://user-images.githubusercontent.com/13700943/53352503-bc501600-38d7-11e9-84dd-0bad67f4e229.png">

I know that the `azure-li-storage` service failed:

<img width="560" alt="screen shot 2019-02-25 at 8 33 37 am" src="https://user-images.githubusercontent.com/13700943/53352668-1224be00-38d8-11e9-8336-c45109cc9014.png">

Yet, running `systemctl status -l` against that gives no useful information either.

What am I doing wrong?

**Comment by schaefi** [comment]
You probably rebooted the machine. Please note the deployment does its job and also uninstalls the azure-li-services package on purpose. Potential errors from systemd are now only available in the systemd cache. This means a reboot of the machine or a reload of systemd will loose that information in memory.

The persistence log information is usually stored in the ```workload.log``` file on the LUN. But you told me that this file doesn't exist which I still can't imagine why.

So to provide me more details your process should be:

1. deploy
2. boot
3. realize there is an error
4. login as root
5. systemctl status ...

No reboot or reload of systemd or any other action on the system in between

**Comment by jeffaco** [comment]
Cockpit error, sorry!

The problem: I was working on a image creator LUN. The Image creator LUN had a number of different YAML LUNs mapped to it (for a variety of different test nodes).

I don't normally rebuild the image creator LUN. So, when you have a number of different configuration LUNs mapped to a system, all with the proper label, it's not deterministic on which LUN will be used.

Closing this issue. Sorry for the false report.
