### ISSUE TITLE
SLES 12 SP4 doesn't resize disk partition properly (Take 2)

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#126]
In issue #117, I reported a problem. You said:

>I need the log file to check what happened. Could you boot the machine with the boot option
>
>```
>rd.debug rd.kiwi.debug
>```
>
>and after the machine has been booted send the log file
>
>```
>/run/initramfs/log/boot.kiwi
>```

With image `SLES12-SP4-SAP-Azure-LI-BYOS.x86_64-1.0.3-Build2.1`, the problem persists.

Here's output from `df -h /`:

```
Filesystem                                           Size  Used Avail Use% Mounted on
/dev/mapper/3600a098038304179392b4d6c6e2f496e-part2  3.3G  2.3G  931M  72% /
```

And here's [boot.kiwi](https://github.com/SUSE-Enceladus/azure-li-services/files/2918062/boot-kiwi.txt)

**Comment by schaefi** [comment]
@jeffaco sorry but there must be something wrong. The log shows the exact same error than before and does not include the fixes I made. This is not the image I created

**Comment by schaefi** [comment]
ok Robert sent the wrong link. I hope this one will be a false possitive

**Comment by jeffaco** [comment]
Issue resolved with third image from Robert, closing issue. Thanks!

```
Sollabdsm33:~ # df -h /
Filesystem                                           Size  Used Avail Use% Mounted on
/dev/mapper/3600a098038304179392b4d6c6e2f496e-part2   61G  2.4G   59G   4% /
Sollabdsm33:~ # 
```
