### ISSUE TITLE
SLES 15: JAVA (required by SAP) doesn't appear to installed

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#127]
On image `SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.1-Build1.1.raw`, JAVA doesn't appear to be installed.

Running `java` from the command line doesn't seem to find the binary, and `rpm -qa | grep java` doesn't seem to have any hits.

**Comment by schaefi** [comment]
Which java do you need ? java openjdk v?, java ibm ? other java ?

**Comment by schaefi** [comment]
Probably: java-1_7_1-ibm ?

**Comment by jeffaco** [comment]
Yeah, `java-1_7_1-ibm` is what's installed on SLES 12 SP3/SP4, and is fine.

**Comment by rjschwei** [comment]
Test image provided production all image build descriptions fixed.
