### ISSUE TITLE
Open file count is too low for SAP HANA

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#133]
The default open file count is too low:

```
Sollabdsm31:~ # ulimit -n
1024
Sollabdsm31:~ # 
```

We generally like to set this higher (like 32768) for accounts that we create or use (i.e. root or other accounts that we set up via credentials).

In the past, this was done by setting `.bashrc` file, but this is pretty restrictive in that it assumes `bash` is always used. I think it's better in one of the generic shell files for the account, although I'm not picky as long as `bash` picks it up along with other common shells.

Can this change be made?

**Comment by schaefi** [comment]
> The default open file count is too low

On linux that affects several settings. As you want this system wide and not added to a shell (you had that running in production that way ?) the following changes are needed:

1. /etc/security/limits.conf

```
    * soft nofile <number>
    * hard nofile <number>
```

    This is changing the ulimit. What number do you want ? 32768 ?

2. /etc/sysctl.conf

```
    fs.file-max = number
```

    Applications using sysctl do not use ulimit. I need a number here too

Thanks

**Comment by RalfKlahr** [comment]
Hi Jeff,
I would not touch the fs.file-max parameter, but I would follow the recommendations regarding the limits.conf file. I tested this with the following content:
*        soft    nproc           32768
*        hard    nproc           65536
#@student        hard    nproc           20
#@faculty        soft    nproc           20
#@faculty        hard    nproc           50
#ftp             hard    nproc           0
#@student        -       maxlogins       4

# End of file
h32adm          -       nofile          1048576
@sapsys soft nofile 65536
@sapsys hard nofile 65536
@sdba soft nofile 65536
@sdba hard nofile 65536
@dba soft nofile 65536
@dba hard nofile 65536

**Comment by schaefi** [comment]
> I would not touch the fs.file-max parameter

ok

Thanks for the details

**Comment by schaefi** [comment]
Which images are affected by this ? please checkmark

- [ ] SLES12-SP3-SAP-Azure-LI-BYOS (was released needs bugzilla)
- [ ] SLES12-SP3-SAP-Azure-VLI-BYOS (was released needs bugzilla)
- [ ] SLES12-SP4-SAP-Azure-LI-BYOS
- [ ] SLES12-SP4-SAP-Azure-VLI-BYOS
- [ ] SLES15-SP1-SAP-Azure-LI-BYOS
- [ ] SLES15-SP1-SAP-Azure-VLI-BYOS

**Comment by RalfKlahr** [comment]
this is a general recommendation - image independent

**Comment by schaefi** [comment]
That means you need the change in all of them. In this case we also need bugzilla reports for the already released image

**Comment by jeffaco** [comment]
We would like the change in all images please.

Entered in Bugzilla, [ID 1130712](https://bugzilla.suse.com/show_bug.cgi?id=1130712).

**Comment by schaefi** [comment]
Robert did that change for SLE15 SP1 in the devel space already

**Comment by schaefi** [comment]
@rjschwei I checked the contents of the Devel:PubCloud:Azure:ImagesSLE15/SLES15-SP1-SAP-Azure-LI-BYOS/root.tar.gz and looked for the change reflecting this issue. I can't find /etc/security/limits.conf to be set in that image. So how did you apply this ?

It would also be good if you leave a short note which images you have touched and what has changed. On those images there will be three people working. You, Jesus and myself. I suggest to do one commit per issue. That way an osc diff -rX will allow easier checking.

I will now start to update the other images with /etc/security/limits.conf setup as suggested by @RalfKlahr

**Comment by schaefi** [comment]
@rjschwei found it, you changed config.sh. ok

**Comment by schaefi** [comment]
@rjschwei but I think it's wrong, the change is missing the domain. As we want this for all users the domain should be set to ```*```

**Comment by schaefi** [comment]
@rjschwei I'll fix this for the SLE15 case

**Comment by schaefi** [comment]
Updated all images in the Devel projects

**Comment by schaefi** [comment]
Updated all images in the Stable projects
