### ISSUE TITLE
Modifications to file /etc/sysctl.d/91-hana-basenet.conf

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#134]
In issue #104, we added file `/etc/sysctl.d/91-hana-basenet.conf` to specify kernel configuration parameters for SAP HANA.

We have some changes to make to that file. Can you replace the contents of the existing `/etc/sysctl.d/91-hana-basenet.conf` file with the following instead?

```
# Base Settings
net.core.somaxconn = 4096
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_syn_retries = 8
net.ipv4.tcp_window_scaling = 1
# Disable IPv6
net.ipv6.conf.all.disable_ipv6 = 1
# See NetApp TR-4290
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.rmem_default = 16777216
net.core.wmem_default = 16777216
net.core.optmem_max = 16777216
net.core.netdev_max_backlog = 300000
net.ipv4.tcp_rmem = 65536 16777216 16777216
net.ipv4.tcp_wmem = 65536 16777216 16777216
net.ipv4.tcp_max_syn_backlog = 16348
net.ipv4.tcp_slow_start_after_idle = 0
sunrpc.tcp_slot_table_entries = 128
sunrpc.tcp_max_slot_table_entries = 128
# Setting Swapping activity down to 10
vm.swappiness=10
# SAP Note 1868829
fs.aio-max-nr = 18446744073709551615
net.ipv4.tcp_dsack = 1
net.ipv4.tcp_sack = 1
# For background information, see SAP Note 2205917 and 1557506
vm.pagecache_limit_mb = 0
vm.pagecache_limit_ignore_dirty = 1
vm.dirty_bytes = 629145600
vm.dirty_background_bytes = 314572800
net.ipv4.tcp_tw_reuse = 1
```

Thanks.

**Comment by rjschwei** [comment]
Please start filing bugs in bugzilla

**Comment by schaefi** [comment]
Which images are affected by this ? please checkmark

[ ] SLES12-SP3-SAP-Azure-LI-BYOS (was released needs bugzilla)
[ ] SLES12-SP3-SAP-Azure-VLI-BYOS (was released needs bugzilla)
[ ] SLES12-SP4-SAP-Azure-LI-BYOS
[ ] SLES12-SP4-SAP-Azure-VLI-BYOS
[ ] SLES15-SP1-SAP-Azure-LI-BYOS
[ ] SLES15-SP1-SAP-Azure-VLI-BYOS

**Comment by jeffaco** [comment]
We would like the change in all images please.

Entered in Bugzilla, [ID 1130710](https://bugzilla.suse.com/show_bug.cgi?id=1130710).

**Comment by jeffaco** [comment]
One more requested change on this one: People here get confused when `/etc/sysctl.conf` don't have the entries for SAP HANA, and they don't know to check for files in `/etc/sysctl.d`.

Could you modify `/etc/sysctl.conf` as follows:

```
####
#
# /etc/sysctl.conf is meant for local sysctl settings
#
# sysctl reads settings from the following locations:
#   /boot/sysctl.conf-<kernelversion>
#   /lib/sysctl.d/*.conf
#   /usr/lib/sysctl.d/*.conf
#   /usr/local/lib/sysctl.d/*.conf
#   /etc/sysctl.d/*.conf
#   /run/sysctl.d/*.conf
#   /etc/sysctl.conf
#
# To disable or override a distribution provided file just place a
# file with the same name in /etc/sysctl.d/
#
# For SAP HANA settings, see file: /etc/sysctl.d/91-hana-basenet.conf
#
# See sysctl.conf(5), sysctl.d(5) and sysctl(8) for more information
#
####
```

The only change is the addition of the comment line: `# For SAP HANA settings, see file: /etc/sysctl.d/91-hana-basenet.conf`.

I'll add this to Bugzilla as well.

**Comment by rjschwei** [comment]
> The only change is the addition of the comment line: `# For SAP HANA settings, see file: /etc/sysctl.d/91-hana-basenet.conf`.
> 
> I'll add this to [Bugzilla](https://bugzilla.suse.com/show_bug.cgi?id=1130710#c2) as well.

This will not help. This file will potentially get overwritten on update of the package that provides the generic file or the user will end up with .rpmSave files on the system

**Comment by schaefi** [comment]
/etc/sysctl.conf is marked as %config in the package. So if we provide a modified version and the package will be updated, the new version from the package will stay in the system as .rpmnew and the original stays untouched.

@jeffaco if you can live with that, we can change it.

From my personal perspective the additional comment is not needed. The file explicitly states

```
# To disable or override a distribution provided file just place a
# file with the same name in /etc/sysctl.d/
```

I find this pretty obvious that extensions which are hana based are done in /etc/sysctl.d and I would expect a user that have found this file and the comment is able to find /etc/sysctl.d/91-hana-basenet.conf
as well. However I'm sometimes wrong in expectations. Thus I leave the choice up to you

**Comment by jeffaco** [comment]
Honestly, I never personally had a problem with this. However, two independent people here did.

Let's bag the updating of `/etc/sysctl.conf`. I think this is no different than, say, udev or init.d or sudoers. And in the end, not applying updates to the file from the package owner is probably not really right either.

Do continue with the update to `/etc/sysctl.d/91-hana-basenet.conf`. Thanks.

**Comment by schaefi** [comment]
ok, sounds like a good decision to me :+1:

**Comment by schaefi** [comment]
I will add the modifications to the images in the devel space today

**Comment by schaefi** [comment]
All SLE12 SP3, SP4 and SLE15 Devel images were updated with the new 91-hana-basenet.conf

**Comment by schaefi** [comment]
Stable builds were updated now too
