### ISSUE TITLE
azure-li-call service is failing

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#137]
Using the latest test image (`SLES12-SP3-SAP-Azure-LI-BYOS.x86_64-1.0.54-Build1.1.raw`), I'm seeing a failure in the azure-li-services service. Note that this happened in the prior test image, but I thought it was cockpit error. Now I do not think that is the case:

```
azurehost1:/mnt/yaml # systemctl status -l azure-li-call
* azure-li-call.service - Setup of Azure Li/VLi Script Caller
   Loaded: loaded (/usr/lib/systemd/system/azure-li-call.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mon 2019-04-15 22:14:12 UTC; 6min ago
 Main PID: 26515 (code=exited, status=1/FAILURE)

Apr 15 22:14:12 linux azure-li-call[26515]:   File "/usr/lib/python3.4/site-packages/azure_li_services/units/call.py", line 41, in main
Apr 15 22:14:12 linux azure-li-call[26515]:     call_source.location, call_script
Apr 15 22:14:12 linux azure-li-call[26515]:   File "/usr/lib/python3.4/site-packages/azure_li_services/command.py", line 104, in run
Apr 15 22:14:12 linux azure-li-call[26515]:     command[0], error.decode(), output.decode()
Apr 15 22:14:12 linux azure-li-call[26515]: azure_li_services.exceptions.AzureHostedCommandException: bash: stderr: /bin/bash: /mnt/scripts/test.sh: No such file or directory
Apr 15 22:14:12 linux azure-li-call[26515]: , stdout: (no output on stdout)
Apr 15 22:14:12 linux systemd[1]: azure-li-call.service: Main process exited, code=exited, status=1/FAILURE
Apr 15 22:14:12 linux systemd[1]: Failed to start Setup of Azure Li/VLi Script Caller.
Apr 15 22:14:13 linux systemd[1]: azure-li-call.service: Unit entered failed state.
Apr 15 22:14:13 linux systemd[1]: azure-li-call.service: Failed with result 'exit-code'.
Warning: azure-li-call.service changed on disk. Run 'systemctl daemon-reload' to reload units.
azurehost1:/mnt/yaml #
```

When I mounted the configuration LUN on the host:

```
azurehost1:/mnt/yaml # cat /mnt/yaml/scripts/test.sh
#!/bin/bash

touch /root/SCRIPT-HAS-BEEN-RUN
azurehost1:/mnt/yaml # 
azurehost1:/mnt/yaml # ls -l /mnt/yaml/scripts/test.sh 
-rwxr-xr-x 1 root root 45 Jun  6  2018 /mnt/yaml/scripts/test.sh
azurehost1:/mnt/yaml # 
```

This is not happening on the second host, just the first. I don't see the issue. Do you?

Is it possible that the configuration LUN is getting dismounted before the azure-li-call service runs?

**Comment by schaefi** [comment]
> Is it possible that the configuration LUN is getting dismounted before the azure-li-call service runs?

No, any service that needs the lun mounts it before when needed (meaning if not yet mounted). So the script call service does

```python
call_source = Defaults.mount_config_source()
        try:
            Command.run(
                [
                    'bash', '-c', '{0}/{1}'.format(
                        call_source.location, call_script
                    )
                ]
            )
        finally:
            Defaults.umount_config_source(call_source)
```

**Comment by schaefi** [comment]
The check if already mounted happens via ```mountpoint /mnt``` So if something in the system overmounts /mnt that check would come back with "we are already mounted" and just continuous. At the moment this way and the opportunity that the file really did not exist at the time the call service wants it are the only two ideas I have so far

**Comment by schaefi** [comment]
/mnt is usually an empty directory and also should stay that way. I wonder where ```/mnt/yaml``` comes from ?

**Comment by jeffaco** [comment]
Note that `/mnt/yaml` is how I mount the configuration LUN for diagnostic purposes. That didn't come from your code, to the best of my knowledge.

This seems to replicate pretty much at will. What can I do on my side to help diagnose this issue? Is there some way we can show all files on a LUN before things get started? (I can do that myself before booting a machine for first-time setup, but I'm not sure that alone would be of value to you.)

**Comment by jeffaco** [comment]
This problem "magically went away" when I resolved a problem with `stonith` device setup.

Is it possible that, when `stonith` was failing, there were timing or other problems that negatively affected the script service?

**Comment by schaefi** [comment]
I can't imagine that. The azure-li-system-setup.service where the stonith setup runs among others does not even mount the lun which contains the script to call. I was thinking in the direction that some service umounts the lun exactly at the time the script call service reads the file.

This potential race condition exists if services that mounts/umounts the lun runs in parallel. This situation can exist. I'll do some checks
