### ISSUE TITLE
SLE15: Failed to start /etc/init.d/boot.local

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#141]
Sorry for the delay in testing the new image, I'll get to that tomorrow. I've actually been busy diagnosing a different issue that I just figured out.

As a workaround to module `softdog` being loaded (see issue #139), I threw a `modprobe softdog` line in file `/var/init.d/boot.local`. Unfortunately, `pacemaker` wasn't starting properly, and it turned out to be that module softdog was NOT loaded, despite the fact that it's in the boot.local file.

I then noted an error on the system at boot time:

```
sollabdsm32:~ # grep boot.local /var/log/boot.log
         Starting /etc/init.d/boot.local Compatibility...
[FAILED] Failed to start /etc/init.d/boot.local Compatibility.
         Starting /etc/init.d/boot.local Compatibility...
[FAILED] Failed to start /etc/init.d/boot.local Compatibility.
sollabdsm32:~ # 
```

Sure enough, it didn't appear that `boot.local` was getting run. Other than the error in `boot.local`, I'm not sure why. Is there another log file I could get more information from?

Now, the contents to `boot.local` are as follows:

```
echo 0 > /sys/kernel/mm/ksm/run
cpupower frequency-set -g performance
cpupower set -b 0

modprobe softdog
```

I added the `modprobe softdog`, but the rest come with the image.

1. Doing a `cat /sys/kernel/mm/ksm/run` yields `0`,
2. I know that the frequency is set to performance (probably BIOS default), and this is checked via validation anyway,
3. I'm not sure how to verify that `cpupower set -b 0` is active or not for automation, so I don't know if that's set or not.

It might be harmless that `boot.local` isn't being run, but shouldn't it? What's the issue here? Is this a bug (if so, I'll enter in bugzilla)? Or something else?

**Comment by schaefi** [comment]
I think this is because of wrong usage of the boot.local service. On my system

```
systemctl status rc-local
● rc-local.service - /etc/init.d/boot.local Compatibility
   Loaded: loaded (/usr/lib/systemd/system/rc-local.service; static; vendor pre>
   Active: inactive (dead)
```

So if you put instructions to:

```
/etc/init.d/boot.local
```

I would expect that the service just calls them. If you look at /usr/lib/systemd/system/rc-local.service
you see:

```
ConditionFileIsExecutable=/etc/init.d/boot.local
ExecStart=/etc/init.d/boot.local start
```

That also means your boot.local script must be a correctly written sysV init script. That old stuff usually looked like this:

```
. /etc/rc.status
rc_reset

case "$1" in
    start)
        rc_status
        ;;
    stop)
        rc_status
        ;;
    try-restart|condrestart)
        rc_status
        ;;
    restart)
        rc_status
        ;;
    status)
        rc_status -v
        ;;
    *)
        ;;
esac
rc_exit
```

imho you should not really invest time in legacy stuff. If you want systemd to do something for you I suggest to write a proper systemd unit file and a script that just gets executed by it

**Comment by jeffaco** [comment]
But the existing `boot.local` file is as written by our BYOS image. Couldn't one argue that if, as is, this isn't executed properly, isn't this a bug?

I think we should do one of the following:

1. Remove the file entirely, and the service associated with it. Then we get no error at startup, or
2. Make sure the file is formatted properly to work as is, out of the box.

If we do the first above, are the other existing items in `boot.local` handled elsewhere in `azure-li-services`?

**Comment by schaefi** [comment]
> But the existing boot.local file is as written by our BYOS image. Couldn't one argue that if, as is, 
> this isn't executed properly, isn't this a bug?

I don't think so. The installed ```/etc/init.d/boot.local``` belongs to the package: ```aaa_base-13.2+git20140911.61c1681-38.13.1.x86_64``` The default contents of the file are just comments. Meaning it does nothing. The execution model in systemd runs the init script with the correct sysV init invocation style: ```/etc/init.d/boot.local start``` which results in basically nothing and a zero exit code.

Now you added code to the existing ```/etc/init.d/boot.local```. The code you added is not sysV init compliant. It just executes commands. The error code of the last command defines the error code of the entire sequence. Usually you should get a more detailed information about the service if you call
the following as user root

```
$ systemctl status -l rc-local
```

> Remove the file entirely, and the service associated with it. Then we get no error at startup, or

nope sorry. This is provided by a package from SLES, aaa_base. I'm not removing stuff that's intentionally provided with a SLES package. If you see an error here please contact the maintainers of aaa_base: Werner Fink <werner@suse.com>

> Make sure the file is formatted properly to work as is, out of the box.

without any modifications ```/etc/init.d/boot.local start``` results in nothing with exit code = 0.
```systemctl status rc-local``` does not list that as an error. If you see an error on the rc-local service
without having any modifications done to /etc/init.d/boot.local please contact the maintainer of systemd. That is also Werner Fink <werner@suse.com>

With all that having said, I don't see an error so far

**Comment by jeffaco** [comment]
I don't think your assertion above is true. Is stated in [original post](https://github.com/SUSE-Enceladus/azure-li-services/issues/141#issue-442005536), the original (unmodified) copy of `/etc/init.d/boot.local`, immediately after login to a newly deployed system, is:

```
echo 0 > /sys/kernel/mm/ksm/run
cpupower frequency-set -g performance
cpupower set -b 0
```

These are not comments. And these generate a error in `/var/log/boot.log`. So something, somewhere, has to be changed. The `/var/log/boot.log` file must be modified during the build or something.

Please advise, thanks.

**Comment by schaefi** [comment]
Ohhh, I'm stupid, you are right. The azure-li-system-setup service adds those entries to /etc/init.d/boot.local for the setup of the kernel samepage handling and the setup of the cpu power flags. 

Sorry my fault. So these entries are expected there and yes not sysV init compliant

Can you provide the log detail as user root:

```
$ systemctl status -l rc-local
```

I guess one of the cpupower calls failed for some reason

Thanks

**Comment by schaefi** [comment]
Something different: I tried replying your mail when you told us that you have downloading issues. The mail came back with a return from the mailed daemon saying "Jeff.Coffler@microsoft.com" is unknown. Something very strange is going on... didn't had any problem sending mails to other people today. Not sure if this is in any case related to your download trouble. We haven't change anything on the process here. I used the same storage account and container. Sorry have no idea why things are slow at your end

**Comment by jeffaco** [comment]
I'm not 100% sure if I induced this or not. I'd have to undo my change and reboot (while I'll do, but we know how long that takes).

First some background:

```
sollabdsm31:~ # grep boot.local /var/log/boot.log
         Starting /etc/init.d/boot.local Compatibility...
[FAILED] Failed to start /etc/init.d/boot.local Compatibility.
         Starting /etc/init.d/boot.local Compatibility...
[FAILED] Failed to start /etc/init.d/boot.local Compatibility.
         Starting /etc/init.d/boot.local Compatibility...
[FAILED] Failed to start /etc/init.d/boot.local Compatibility.
         Starting /etc/init.d/boot.local Compatibility...
[FAILED] Failed to start /etc/init.d/boot.local Compatibility.
sollabdsm31:~ # 
sollabdsm31:~ # 
sollabdsm31:~ # cat /etc/init.d/boot.local       
echo 0 > /sys/kernel/mm/ksm/run
cpupower frequency-set -g performance
cpupower set -b 0

modprobe softdog
sollabdsm31:~ # 
```

And now your `systemctl status` output:

```
sollabdsm31:~ # systemctl status -l rc-local     
● rc-local.service - /etc/init.d/boot.local Compatibility
   Loaded: loaded (/usr/lib/systemd/system/rc-local.service; enabled-runtime; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2019-05-09 16:13:32 UTC; 12min ago
  Process: 4439 ExecStart=/etc/init.d/boot.local start (code=exited, status=203/EXEC)

May 09 16:13:32 sollabdsm31 systemd[1]: Starting /etc/init.d/boot.local Compatibility...
May 09 16:13:32 sollabdsm31 systemd[4439]: rc-local.service: Failed at step EXEC spawning /etc/init.d/boot.local: Exec format error
May 09 16:13:32 sollabdsm31 systemd[1]: rc-local.service: Control process exited, code=exited status=203
May 09 16:13:32 sollabdsm31 systemd[1]: Failed to start /etc/init.d/boot.local Compatibility.
May 09 16:13:32 sollabdsm31 systemd[1]: rc-local.service: Unit entered failed state.
May 09 16:13:32 sollabdsm31 systemd[1]: rc-local.service: Failed with result 'exit-code'.
sollabdsm31:~ # 
```

Let me know if I can provide further information. I will revert my change, reboot (and wait 15 minutes for that), then see if the issue repros.

And out of desperation:

```
sollabdsm31:~ # ls -l /etc/init.d/boot.local 
-rwxr-xr-x 1 root root 106 May  8 00:22 /etc/init.d/boot.local
sollabdsm31:~ # 
```

No solace there.

**Comment by jeffaco** [comment]
No relief from a reboot:

I reverted my changes, like this:

sollabdsm31:~ # cat /etc/init.d/boot.local
echo 0 > /sys/kernel/mm/ksm/run
cpupower frequency-set -g performance
cpupower set -b 0
sollabdsm31:~ # 
sollabdsm31:~ # 
sollabdsm31:~ # ls -l /etc/init.d/boot.local 
-rwxr-xr-x 1 root root 88 May  9 16:28 /etc/init.d/boot.local
sollabdsm31:~ # 
```

Then, after a reboot, no change:

```
sollabdsm31:~ # systemctl status -l rc-local
● rc-local.service - /etc/init.d/boot.local Compatibility
   Loaded: loaded (/usr/lib/systemd/system/rc-local.service; enabled-runtime; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2019-05-09 16:35:52 UTC; 1min 44s ago
  Process: 4353 ExecStart=/etc/init.d/boot.local start (code=exited, status=203/EXEC)

May 09 16:35:52 sollabdsm31 systemd[1]: Starting /etc/init.d/boot.local Compatibility...
May 09 16:35:52 sollabdsm31 systemd[4353]: rc-local.service: Failed at step EXEC spawning /etc/init.d/boot.local: Exec format error
May 09 16:35:52 sollabdsm31 systemd[1]: rc-local.service: Control process exited, code=exited status=203
May 09 16:35:52 sollabdsm31 systemd[1]: Failed to start /etc/init.d/boot.local Compatibility.
May 09 16:35:52 sollabdsm31 systemd[1]: rc-local.service: Unit entered failed state.
May 09 16:35:52 sollabdsm31 systemd[1]: rc-local.service: Failed with result 'exit-code'.
sollabdsm31:~ # 
```

Thoughts?

**Comment by schaefi** [comment]
I checked on our integration tests and the result is good here. Our test however only includes:

```
echo 0 > /sys/kernel/mm/ksm/run
```

not more because the cpu power setup failed (intentionally) because my CI hardware doesn't support it
I will try what happens if I add the cpupower calls

**Comment by schaefi** [comment]
Ok all my tests were good. I have an assumption though. I see in your output there is:

```
May 09 16:13:32 sollabdsm31 systemd[4439]: rc-local.service: Failed at step EXEC spawning /etc/init.d/boot.local: Exec format error
```

This only happens if the script that should be called has no shebang set. I checked the default boot.local file and also our azure system_setup.py code. So the default file comes with:

```
#! /bin/sh
# Copyright ...
```

and our azure service appends to this file:

```python
with open(permanent_boot_setup_file, 'a') as boot_local:
```

So the contents of the file as you mention it doesn't seem to have that or you just provide an excerpt of the file contents. So may I ask: Did you have removed the shebang ```#! /bin/sh``` from /etc/init.d/boot.local ?

If so that explains the execution problem. However I don't see our code to do this.

Thanks

**Comment by jeffaco** [comment]
There is no shebang line in the `/etc/init.d/boot.local` file. The contents that I posted above were complete.

However, I now have the new test image on my blades, and the file in the latest test image is different:

```
#! /bin/sh
#
# Copyright (c) 2002 SuSE Linux AG Nuernberg, Germany.  All rights reserved.
#
# Author: Werner Fink, 1996
#         Burchard Steinbild, 1996
#
# /etc/init.d/boot.local
#
# script with local commands to be executed from init on system startup
#
# Here you should add things, that should happen directly after booting
# before we're going to the first run level.
#

echo 0 > /sys/kernel/mm/ksm/run
cpupower frequency-set -g performance
cpupower set -b 0
```

Furthermore, on the latest image, output from `/var/log/boot.log` has changed:

```
sollabdsm31:~ # grep boot.local /var/log/boot.log
         Starting /etc/init.d/boot.local Compatibility...
[  OK  ] Started /etc/init.d/boot.local Compatibility.
sollabdsm31:~ # 
```

So, obviously, there was a change in the latest image where the prior image didn't have this fix.

I guess we can close this issue. I guess you or Jesus or Robert changed this with other changes?

**Comment by schaefi** [comment]
Nope we really didn't touch this file other than appending to the original content which comes from aaa_base. The former version SLES12-SP3-SAP-Azure-LI-BYOS.x86_64-1.0.54-Build1.1.raw.xz is still in the Azure storage account. You can double check yourself by downloading the sas url of the former e-mail.

It's pretty weird but what you wrote lately calmed me down. This is how it should look like

still a mystery though

**Comment by jeffaco** [comment]
Ah crap, now it's my turn to be stupid. In the posts above, I mentioned I had this issue in a "prior version" (rather vague):

>So, obviously, there was a change in the latest image where the prior image didn't have this fix.

Nowhere did I mention what version I was talking about! That sucks, and only complicated understanding this issue. I was actually talking about the latest RELEASED image of SLES 15 (`SLES15-SP0-SAP-Azure-LI-BYOS.x86_64-1.0.3-Build1.12.raw`).

In that image, immediately after using `dd` to copy the raw file to disk, I could mount the disk to examine `/etc/init.d/boot.local` before booting the target system. To my surprise, the file did not exist at all (probably the crux of the problem):

```
Sollabdsm33:~/images/release2.0 # ls /mnt/raw/etc/init.d/          
boot.d  rc0.d  rc1.d  rc2.d  rc3.d  rc4.d  rc5.d  rc6.d  rcS.d
Sollabdsm33:~/images/release2.0 # 
```

After booting the system, and immediately after logging in:

```
sollabdsm32:~ # cat /etc/init.d/boot.local
echo 0 > /sys/kernel/mm/ksm/run
cpupower frequency-set -g performance
cpupower set -b 0
sollabdsm32:~ # 
```

So now we understand the problem. This is a problem that was specific to SLES 15 (I believe), and you're not generating SLES 15 images for me to validate against for test purposes.

Can you please make sure that the base version of this file is included properly so that when `azure-li-services` runs, it properly builds a version of `/etc/init.d/boot.local` that will actually work?

**Comment by schaefi** [comment]
Good catch I have to check how things are different on sles15. I will be on business travel next week and hope I'll find the time to take a look.

It's good that we have that history. As we are using the boot.local concept for sles15 as well we should make sure it works there too. aaa_base is a very very old concept from SUSE. You can see that on the timestamp of the people mentioned in the comment block of /etc/init.d/boot.local, 1996 :smile: So I guess with sles15 maybe that package does no longer exist or is not mandatory anymore.

I need to check that...

**Comment by jeffaco** [comment]
Create a bugzilla entry, now that we understand the issue?

**Comment by schaefi** [comment]
afaik we haven't released sle15 images officially. That means we don't need a bugzilla entry

**Comment by schaefi** [comment]
I have fixed all sle15 image descriptions to work correctly with the rc-local service and our extension to it

**Comment by schaefi** [comment]
I'll run the integration tests for the sle12-sp4 and the sle15 build and will provide testing images for your reference next. Expect sas urls coming along by mail
