### ISSUE TITLE
Regression or bug with system_setup service

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#142]
We're just finishing up final automation for O/S checking, and we found some issues.

In #52, you discuss setting up the `tuned-adm` profile and setting up the `saptune` daemon. What you say you do looks correct, but in checking, it's not:

```
sollabdsm32:~ # tuned-adm active
Current active profile: saptune
sollabdsm32:~ # saptune daemon status
Daemon (tuned.service) is running.
The system has been tuned for the following solutions and notes:
        HANA
sollabdsm32:~ # 
```

I expected that the `tuned-adm` profile is set to `sap-hana`, but it's not, it's `saptune`. This is incorrect, and what's specified in issue #52 is correct.

Is this a regression? Or did I just miss that after acceptance testing?

**Comment by schaefi** [comment]
Well we implemented according to the specs and discussion of #52 and you've been one of the reviewers. See the following lines of code that reflects the implementation:

* https://github.com/SUSE-Enceladus/azure-li-services/blob/master/azure_li_services/units/system_setup.py#L125

I guess your point is that the call

```
tuned-adm profile sap-hana
```

is not part of our code. This is because, and if I understood correctly, that this sap-hana profile is delivered by a custom package that you install through our package installer service. Thus I would expect that package to activate the profile in a %post of the spec file or you supply a script call that activates it. In any case it seems that SLES does not provide the sap-hana profile that is needed.

Also see the conversation from here:

* https://github.com/SUSE-Enceladus/azure-li-services/pull/59

So if anything here is wrong we need more details

Thanks

**Comment by jeffaco** [comment]
The only "custom package" that we install is either:

1. UCS drivers for UCS hardware, or
2. SFS (Software Foundation Services) for HPE hardware

We don't install any other packages.

Furthermore:

```
sollabdsm31:~ # tuned-adm list
Available profiles:
- balanced
- desktop
- latency-performance
- network-latency
- network-throughput
- powersave
- sap-ase
- sap-bobj
- sap-hana
- sap-netweaver
- saptune
- throughput-performance
- virtual-guest
- virtual-host
Current active profile: sap-hana
sollabdsm31:~ # 
```

The `sap-hana` package is one of the default packages that are included with `tuned-adm`. That's the one that we want for use with SAP HANA.

**Comment by rjschwei** [comment]
Hmm, I started a SLES 4 SAP instance in and tested the steps implemented in #59 and things worked as expected:

`# saptune daemon start
Starting daemon (tuned.service), this may take several seconds...
Daemon (tuned.service) has been enabled and started.
Your system has not yet been tuned. Please visit `saptune note` and `saptune solution` to start tuning.
# saptune solution apply HANA
All tuning options for the SAP solution have been applied successfully.
# tuned-adm profile sap-hana
# systemctl enable tuned
# systemctl start tuned
# tuned-adm active
Current active profile: sap-hana`

The test system was a SLES 12 SP4 For SAP instance.

Makes me wonder if there is anything in the logs that would indicate some kind of error in the azure-li-services that would cause the tuning setup to be skipped. Or maybe there are erors in the systemlog when we are starting tuned and the errors go undetected.

**Comment by jeffaco** [comment]
Using the just-released SP4 production (identical behavior with SLES 15):

```
sollabdsm32:~ # cat /etc/issue 

Welcome to SUSE Linux Enterprise Server for SAP Applications 12 SP4  (x86_64) - Kernel \r (\l).


sollabdsm32:~ # 
```

So no errors during startup (the `/etc/issues` file is modified if something fails).

```
sollabdsm32:~ # saptune daemon status
Daemon (tuned.service) is running.
The system has been tuned for the following solutions and notes:
        HANA
sollabdsm32:~ # tuned-adm active         
Current active profile: saptune
sollabdsm32:~ # 
```

I'm not sure if it's dependency ordering or what, but `tuned-adm` definitely isn't set up for `sap-hana`.

**Comment by jeffaco** [comment]
It looks like this is slightly more complicated. The `tuned-adm` profile `sap-hana` must have come from an SAP note. But it does not appear that `sap-hana` exists on SLES 15.

I'll reach out to our SAP guys to figure out what they think we should be using, and if it should be different in SLES 12 vs. SLES 15. I'll post back here when I hear something further.

**Comment by jeffaco** [comment]
According to SAP Note [1275776](https://launchpad.support.sap.com/#/notes/1275776):

>In SLES 12 the profiles 'sap-netweaver' and 'sap-hana' are identical and therefore either can be used. If you want to use 'sap-ase' or 'sap-bobj', check each configuration carefully and keep in mind that setting some system values are still hard-coded and not configurable! Check the log /var/log/sapconf.log after applying the profile.
>
>In SLES 15 all profiles are unified to 'sapconf'.

So it looks like in SLES 12 SP3 and SLES 12 SP4, we want `tuned-adm` profile `sap-hana`.

In SLES 15, we want `tuned-adm` profile `sapconf`.

Thanks ...

**Comment by schaefi** [comment]
Ok this starts to become confusing now. Le me summarize my thinking:

1. The call ```tuned-adm profile name_of_profile``` is not done by the current setup implementation.
    This was by intention because due to the initial discussion it was not clear where the profile will come
    from. Your expectation that this profile gets applied is therefore not met. Our setup code does
    everything that can be generically done. Also see https://github.com/SUSE-Enceladus/azure-li-services/issues/142#issuecomment-492570817

2. There is some information about profiles here and in contrast to my former understanding they are
    provided by the ```sapconf``` package and can just be used as such. Is this correct ? If not which 
    package(s) provides the profiles ?

3. If the profiles can just be used they seem to have a different name depending on which distro we
    use; SLE12 vs. SLE15. Apart from that I think that this rename is a questionable idea we need to
    have a clean way to distinguish the fact. So would it be correct to apply ```sap-hana``´ if it exists
    and if not apply ```sapconf``` ?

Thanks

**Comment by jeffaco** [comment]
I am not installing any packages here to get profiles. The profiles are just available via `tuned-adm`, so I would expect that the profiles either just ship with whatever ships `tuned-adm`, or some package that installs on top of that.

As for your last question, yes. In SLES 15, `tuned-adm` no longer supplied the `sap-hana` profile. So if you can't apply `sap-hana`, then it should be safe to apply `sapconf`. This change was made by SAP (it looks like), as they mentioned that in one of their notes (specified above).
