### ISSUE TITLE
hostname is not set up in /etc/hosts

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#143]
Because the hostname is not set up in the `/etc/hosts` file, the `hostname -f` command fails.

This needs to be customized by the customer anyway, so it's minor, but it would be nice if the command passed successfully after installation so automation tests pass. Perhaps you can add something like:

```
client-ip    hostname.example.com hostname
```

to `/etc/hosts` where client-ip is the IP address specified in the networking section (generally first IP specified in the networking section, ending in a VLAN of '0', with an MTU of 1500).

If you were very bitter about that (making assumptions about the client IP), even adding something like:

```
127.0.0.1 hostname
```

would at least get us farther.

Note that this is the very last check for LI systems we have in automation, near as I can tell in reviewing what we've got. So that's an upside since we (very much) want to get to VLI. Note that these checks will need to be in VLI as well - they are common.

Thanks for your consideration.

**Comment by jeffaco** [comment]
Can this be picked up for the next test image, by chance? It would be helpful, thanks ...

**Comment by prtyag** [comment]
@schaefi do we have some update on this issue? hostname -f is still failing for some recent images given by suse.

**Comment by schaefi** [comment]
Closing due to no further information. As written in the associated PR we need further details if this is still relevant. The PR as it is right now is a good implementation from Jesus but has questionable reasons. For clarifying those please open a new issue with further details

Thanks
