### ISSUE TITLE
With latest test image of SLES 12 SP4, "saptune daemon status" fails

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#149]
With the latest test image of SLES 12 SP4, it appears that saptune isn't quite right.

Note the following log:

```
sollabdsm31:~ # saptune daemon status
Daemon (tuned.service) is running.
tuned.service profile is incorrect. If you wish to correct it, run `saptune daemon start`.
sollabdsm31:~#
```

If I do what it says, things seem better, and output is what I expect:

```
sollabdsm31:~ # saptune daemon start
Starting daemon (tuned.service), this may take several seconds...
Daemon (tuned.service) has been enabled and started.
sollabdsm31:~ # saptune daemon status
Daemon (tuned.service) is running.
The system has been tuned for the following solutions and notes:
        HANA
sollabdsm31:~ #
```

It looks like #142 isn't quite right ...

Please advise, thanks.

**Comment by schaefi** [comment]
I don't see what should be wrong. Check yourself:

* https://github.com/SUSE-Enceladus/azure-li-services/blob/master/azure_li_services/units/system_setup.py#L125

Our sequence does:

1. enable service tuned
2. start tuned daemon
3. start saptune daemon
4. run saptune solution apply HANA
5. run tuned-adm profile "either sap-hana or sapconf"

I don't see anything wrong there unless somebody tells me that a profile apply requires a restart of the saptune daemon

In my test regarding #142 I ran ```tuned-adm list``` and it reports the list of profiles and the active one. Thus the implementation for #142 looks correct to me and this one is an after effect which looks weird to me. So can you please clarify with the SAP people:

a) does the setup of a profile require restart of services ?
b) is the daemon in question running as expected ?The error message "tuned.service profile is incorrect." implies a problem with the profile or the service but not with our startup sequence

Thanks

**Comment by jeffaco** [comment]
It looks like ordering is picky here. Note the logs below:

```
sollabdsm31:~ # saptune daemon stop 
Stopping daemon (tuned.service), this may take several seconds...
Daemon (tuned.service) has been disabled and stopped.
All tuned parameters have been reverted to default.
sollabdsm31:~ # tuned-adm profile sap-bobj
Cannot talk to Tuned daemon via DBus.
You need to (re)start the tuned daemon by hand for changes to apply.
sollabdsm31:~ # systemctl start tuned    
sollabdsm31:~ # tuned-adm profile sap-bobj  (Note: sap-bobj is some something I picked at random)
sollabdsm31:~ # saptune daemon status
Daemon (tuned.service) is running.
tuned.service profile is incorrect. If you wish to correct it, run `saptune daemon start`.
```

I think if your ordering is different, it works fine. See the following log:

```
sollabdsm31:~ # saptune daemon stop
Stopping daemon (tuned.service), this may take several seconds...
Daemon (tuned.service) has been disabled and stopped.
All tuned parameters have been reverted to default.
sollabdsm31:~ # 
sollabdsm31:~ # 
sollabdsm31:~ # systemctl start tuned     
sollabdsm31:~ # tuned-adm profile sap-hana
sollabdsm31:~ # saptune daemon start      
Starting daemon (tuned.service), this may take several seconds...
Daemon (tuned.service) has been enabled and started.
sollabdsm31:~ # saptune daemon status     
Daemon (tuned.service) is running.
The system has been tuned for the following solutions and notes:
        HANA
sollabdsm31:~ # 
```

It seems like setting of a profile requires a restart of saptune. Or just configure saptune second, and then no restart appears to be required.

So I think your sequencing should be something like:

1. enable service tuned
1. start tuned daemon
1. run tuned-adm profile "either sap-hana or sapconf"
1. start saptune daemon
1. run saptune solution apply HANA

If you give me an exact command sequence, I can deploy a fresh O/S and try it. But I think the above will do the trick.

**Comment by schaefi** [comment]
All right, thanks for hunting this down. I'll take a look

**Comment by schaefi** [comment]
@jeffaco we will provide a new testing image next. I'll ask Jesus to send it across the wire

**Comment by jeffaco** [comment]
I'm never sure if you want a brand new issue for a repeating problem, or just re-opening a prior issue. If, in the future, you prefer a brand new issue, let me know.

I received new test image `SLES12-SP4-SAP-Azure-LI-BYOS.x86_64-1.0.8-Build1.2.raw` this morning and tried it out. It fails automation for O/S acceptance:

```
19:04:23 Executing commands to check system state ...            failed
19:04:23   ERROR: Command "tuned-adm active" returned "Current active profile: saptune", not matching expression "Current active profile: sap-hana"
```

Sure enough, this appears wrong, at least for SLES 12 SP4:

```
sollabdsm31:~ # tuned-adm active
Current active profile: saptune
sollabdsm31:~ # 
```

The following fixes it up:

```
sollabdsm31:~ # tuned-adm profile sap-hana
sollabdsm31:~ # saptune daemon start
Starting daemon (tuned.service), this may take several seconds...
Daemon (tuned.service) has been enabled and started.
sollabdsm31:~ # 
```

According to SAP note [1275776](https://launchpad.support.sap.com/#/notes/1275776) pointed out [here](https://github.com/SUSE-Enceladus/azure-li-services/issues/142#issuecomment-494171785), we should be using `sap-hana` for SLES 12 SP3 and SLES 12 SP4, and we should be using `sapconf` in SLES 15.

This seemed to work fine in the prior test image, but now it's not.

**Comment by schaefi** [comment]
> I'm never sure if you want a brand new issue for a repeating problem, or just re-opening a prior issue

All good, thanks. It belongs here

I think the problem is the change in the startup sequence. We never apply the profile saptune. We either apply sap-hana if /usr/lib/tuned/sap-hana exists or we apply sapconf.

Now that we had to change the order of the service start my guess is that:

1. tuned-adm profile ...
2. saptune daemon start
3. saptune solution apply HANA

This somehow invalidates the tuned-adm profile setting.

> This seemed to work fine in the prior test image, but now it's not.

In the prior test image the complain was that the tuned.service profile is incorrect.
So may I ask how this should be done correctly ?

My suggestion is to revert the change in order and just add a restart of the saptune daemon

The behavior of these tools is weird. Thus if there is any official recommendation by the people who wrote this I would rather follow that instead of the try and error game

Thanks

**Comment by jeffaco** [comment]
It looks like SAP Note [1275776](https://launchpad.support.sap.com/#/notes/1275776) is the note that covers this. And it just isn't 100% detailed here; it says what to do, but doesn't give specific sequencing.

I reached out to one of our PMs on this, and this is the sequence that he follows:

```
saptune daemon start
tuned-adm profile sap-hana
systemctl start tuned
systemctl enable tuned
tuned-adm profile sap-hana
saptune solution apply HANA
saptune daemon start
```

It appears, to me, that after you apply a change to saptune, the daemon needs to be restarted (otherwise you get the error that I was seeing). Without the final `saptune daemon start`, the command `saptune daemon status` would fail with the error I was complaining about.

Unfortunately, I can't test this 100%, as I only have bare metal to try this on, and that bare metal has been partially configured at first boot by the very code we're trying to fix here. Sorry ...

Can you try the above sequence on a "virgin" system and see if it works properly?

**Comment by schaefi** [comment]
Still no luck with this. Something is very strange with saptune

**Comment by schaefi** [comment]
From my tests I can confirm that any start of ```tuned-adm profile ...``` will lead to an error message on ```saptune daemon status```. This is not really good programming. If those things depends on each other they should also be restarted or updated on a change

**Comment by schaefi** [comment]
In the current code the last we do is ```saptune daemon start``` but the status stll says it's not ok. Repeating the same command again without any change brings everything back on green, wtf ??

Is there any timeout constraint that has to be respected between a profile apply and the restart of the saptune daemon ?

**Comment by jeffaco** [comment]
I think that there appear to be two daemons that are interrelated and dependent on one another, but don't seem to do a good job if one daemon gets a change. Documentation in SAP notes don't appear to give clear guidance here. The command sequence I gave you did work for me, but I ran from individual commands, so it's entirely possible that it only worked due to timing of my commands. Ugh!

I can do more investigation (using scripting) if necessary. But I see that you closed this issue again. Do you have a solution here, or do you need me to investigate further?

Thank, and sorry for the grief ...

**Comment by schaefi** [comment]
I hope I have a solution... but I had that hope already two times and got batted ;) So I'll give the image that currently builds a try and if it does not work I re-open the thing again

**Comment by schaefi** [comment]
Finally this works in my tests now :)

I'll upload a new testing VLI image for your reference today
