### ISSUE TITLE
Build image to support UEFI boot

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#15]
In discussion of boot performance with Cisco, they commented that their blades boot much more slowly in MS-DOS compatibility mode, and suggested that use of UEFI would be much faster. They also stipulated that they didn't believe Linux supported UEFI.

Can the SUSE O/S image support booting via UEFI? What's involved for that?

**Comment by schaefi** [comment]
yes we can :)

sles12 provides the shim package with a Microsoft signed shim loader. I can change the image layout to uefi in a minute. However I think we should coordinate on the order of changes. Do we want to get the required services implemented first and then switch over to uefi or is it important that we do it now and hold on with further services until you see the machine running in efi mode ?

**Comment by rjschwei** [comment]
IMHO we should wait with the switch over until we have the remaining services implemented.

**Comment by schaefi** [comment]
I think so too

**Comment by jeffaco** [comment]
Agreed. Let's get to the point where we're 100% done with LI, then go for UEFI. Once that's done, we can move on to VLI.

I just added this as a placeholder. It was discussed in E-Mail, but other that than, it's been in my head. Now it's more formal! 😄

**Comment by schaefi** [comment]
:+1:

**Comment by schaefi** [comment]
One open question at this point:

* Do you want secure boot to be enabled ?

**Comment by jeffaco** [comment]
I'll need to check with our VLI vendor, and see if they can do secure boot. Let's table this for now, and this can be addressed at a later date, while we're working on VLI (if that's okay with you).

I'm sensitive to your desire for the same image for both platforms, and if VLI can't do secure boot, that would make your desire impossible ...

So let's table this and take up during VLI integration, thanks.

**Comment by schaefi** [comment]
That's fine, thanks

**Comment by schaefi** [comment]
The switch will be done on agreement with Jeff and will be the only change in the image description without any other change on the packages used to build the image including azure-li-services

**Comment by schaefi** [comment]
With regards to a conversation between Robert and Jeff it seems the switch is not worth the effort.
Thus I'm changing the blocked label and mark this as an enhancement we might want to have for a future generation

**Comment by jeffaco** [comment]
At this point, it appears that UEFI will have a minimal effect on boot performance. Given that, I don't see a clear advantage to make the change.

Closing this issue for now; will re-open it if anything changes. Thanks.
