### ISSUE TITLE
User root set to shell /sbin/nologin if no password set

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#151]
Using image `SLES12-SP4-SAP-Azure-LI-BYOS.x86_64-1.0.8-Build1.2.raw` (and prior), user `root` doesn't allow login if no password is set in the YAML file.

YAML looks like this for credentials:

```
  username: "root"
  ssh-key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCt0tiRjcZE0XU38M6aBxaRd+fsVUnezP8/fStL4vgxuzu84FFTTK6XIVsMWVbDxROVA0H98Sexfm8ZDgxYxQ5g6Nk1wbWxB9wbPHrykJScV3tUGWh4RgDq4rm/8+k7Msd32Ubj2t5962W1h1s+zhax4io0bSvJtKj9Ke1Bcq86zEcFg3iPIyxSY8oKK02luT3m73/0L+2BzVXzSsUwE23Nh37+jVAWt+aXHJPlg7YNJGN/9luqx90I3BiPDRtsj4AZ8OtYvBgpDbGK8cVMEDGvOg0+a8JE8oebzgzArYNlWskCRvdvVPU3rk8GKjSKDC2j5lS5sjiiT342Qc3VjoScg5pNfT5fBQ2KI3+LQW9UGwtQwX4er+rjVMM72f1BRI5pIBuwWQIQJzwlqF/KUZcCC5Ly8H8S96thxpmsnXz89GOfldFbQQa/IP5dqCERFpncg1stnDjtGUGU7LIBcBkxqC0ixHgsNKlqFkpT/2oP3y8J875sxykKcigq2Gzw8avXH0W/7nA2pGIrqMMNvMs4ORmSi0FufwNnMsmJYW/baOPUgO+yzUeWLL9wajFo7ozoXz/Q1mLhd8791XO8+ph1Txs0smqV0BK7l/8rAOfhJB1t/aLIB1D+AuVxkfFXUDCcTT4LHSpS7LgI+vsegcN5rPPdFucgMoxLncEC5Fwfww== Jeff Coffler Common Key"
```

After boot:

```
h31adm@sollabdsm31:~> grep root /etc/passwd   
root:x:0:0:root:/root:/sbin/nologin
h31adm@sollabdsm31:~>
```

No login is allowed because the default shell is `/sbin/nologin`. Because an SSH key was specified, we should allow login. Obviously, with no password set, there should be no password that allows login. But SSH key login should be valid.

Was this intentional or an oversight?

(I'll open a bug in Bugzilla if we agree this is a problem)

**Comment by jeffaco** [comment]
It turns out that this is an issue for the non-root user as well. If we create a non-root user with just an SSH key, it is set to a shell of `/sbin/nologin`.

**Comment by schaefi** [comment]
The behavior here was intentional. No shadow hash means no login for this user. This is by intention

> Because an SSH key was specified, we should allow login. 

why ? This assumption seems not correct to me. The presence of an ssh key could be combined with a command. That means the key could be used to execute just one command. We haven't added support for that but I just wanted to say the pure presence of an ssh-key has no direct implication on the login capability.

My personal vote: provide a shadow hash which clearly indicates that we want to login

**Comment by jeffaco** [comment]
I wasn't aware that an SSH key could be used to execute a specific command. Regardless, I never use it that way.

We feel that password authentication is fundamentally flawed. If someone knows your password, then your system can be compromised. But if you use an SSH key (and the key is encrypted), then it's essentially 2FA (something you have - the private key - and something you know - the encryption password). This, I feel, is much stronger than just password login.

We have temporarily worked around this by generating a long random password, hashing that, storing the hash, and then immediately just forgetting the password that was generated. By making it a long password, this thwarts ost brute force attempts. But we would prefer to actually not allow a password at all, and JUST allow an SSH key. This is a common configuration. Indeed, on Azure, if you use an SSH key for authentication, then login is allowed, but there is no password that works. On AWS, they very strongly promote keys (I think they actually don't allow passwords on AWS, but I'm not sure since I haven't tried that myself.)

Can we support login via SSH key only with a shell? Perhaps because an SSH key was specified, or perhaps by  adding something to the YAML to clearly indicate that we want a login shell?

Thanks.

**Comment by schaefi** [comment]
ok thanks for the explanation. The security aspect of the shadow hash makes sense to me.

@jesusbv you already started to change the behavior in this regard. Let's make use of your patch.
Thanks
