### ISSUE TITLE
Unable to boot test VLI image on test machine

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#152]
I set up the VLI host to boot the test image you provided last week (`SLES12-SP4-SAP-Azure-VLI-BYOS.x86_64-0.0.16-Build1.2.raw`), and it seemed to fail boot virtually immediately. Is there a multipath issue or something?

Here's a log on the console:

```
EFI Shell version 2.40 [1.0]
Current running mode 1.1.2
Device mapping table
  blk0  :HardDisk - Alias (null)
         PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x1)/Fibre(0x200900A098D3B5F0,0x0)/HD(1,MBR,0x0B4C2F49,0x800,0x96000)
  blk1  :HardDisk - Alias (null)
         PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x1)/Fibre(0x200900A098D3B5F0,0x0)/HD(2,MBR,0x0B4C2F49,0x96800,0x67B000)
  blk2  :HardDisk - Alias (null)
         PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x1)/Fibre(0x200A00A098D3B5F0,0x0)/HD(1,MBR,0x0B4C2F49,0x800,0x96000)
  blk3  :HardDisk - Alias (null)
         PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x1)/Fibre(0x200A00A098D3B5F0,0x0)/HD(2,MBR,0x0B4C2F49,0x96800,0x67B000)
  blk4  :HardDisk - Alias (null)
         PciRoot(0x0)/Pci(0x3,0x2)/Pci(0x0,0x1)/Fibre(0x200B00A098D3B5F0,0x0)/HD(1,MBR,0x0B4C2F49,0x800,0x96000)
  blk5  :HardDisk - Alias (null)
         PciRoot(0x0)/Pci(0x3,0x2)/Pci(0x0,0x1)/Fibre(0x200B00A098D3B5F0,0x0)/HD(2,MBR,0x0B4C2F49,0x96800,0x67B000)
  blk6  :HardDisk - Alias (null)
         PciRoot(0x0)/Pci(0x3,0x2)/Pci(0x0,0x1)/Fibre(0x200C00A098D3B5F0,0x0)/HD(1,MBR,0x0B4C2F49,0x800,0x96000)
  blk7  :HardDisk - Alias (null)
         PciRoot(0x0)/Pci(0x3,0x2)/Pci(0x0,0x1)/Fibre(0x200C00A098D3B5F0,0x0)/HD(2,MBR,0x0B4C2F49,0x96800,0x67B000)
  blk8  :BlockDevice - Alias (null)
         PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x1)/Fibre(0x200900A098D3B5F0,0x0)
  blk9  :BlockDevice - Alias (null)
         PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x1)/Fibre(0x200900A098D3B5F0,0x1000000000000)
  blkA  :BlockDevice - Alias (null)
         PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x1)/Fibre(0x200A00A098D3B5F0,0x0)
  blkB  :BlockDevice - Alias (null)
         PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x1)/Fibre(0x200A00A098D3B5F0,0x1000000000000)
  blkC  :BlockDevice - Alias (null)
         PciRoot(0x0)/Pci(0x3,0x2)/Pci(0x0,0x1)/Fibre(0x200B00A098D3B5F0,0x0)
  blkD  :BlockDevice - Alias (null)
         PciRoot(0x0)/Pci(0x3,0x2)/Pci(0x0,0x1)/Fibre(0x200B00A098D3B5F0,0x1000000000000)
  blkE  :BlockDevice - Alias (null)
         PciRoot(0x0)/Pci(0x3,0x2)/Pci(0x0,0x1)/Fibre(0x200C00A098D3B5F0,0x0)
  blkF  :BlockDevice - Alias (null)
         PciRoot(0x0)/Pci(0x3,0x2)/Pci(0x0,0x1)/Fibre(0x200C00A098D3B5F0,0x1000000000000)
  blk10 :Removable BlockDevice - Alias (null)
         PciRoot(0x0)/Pci(0x1D,0x0)/USB(0x0,0x0)/USB(0x0,0x0)

Press ESC in 1 seconds to skip startup.nsh, any other key to continue.
Shell>
```

Any idea what the issue is here? In looking at NetApp configuration and device mapping, things look correct.

Please advise, thanks!

**Comment by schaefi** [comment]
So you are booting in EFI mode ? if so did you remember that we postponed the decision to change the image to be EFI bootable until we need it :)

Looks like we need it for VLI. If so let me know and I change the bit

Thanks

**Comment by jeffaco** [comment]
Okay, let's do EFI for VLI, but not for LI. This should be possible since we're using separate images.

The reason I backed away from EFI for LI: I was originally hoping that it would speed up the post boot (which, due to a lot of memory on these machines, is really slow). When I learned it would not, I then thought that EFI had no point. But this was just for LI; I didn't know if VLI used EFI at the time or not.

So, since we can't even boot, let's make the VLI image support EFI (since it appears we need it), and lets leave the LI image untouched. Thanks!

**Comment by schaefi** [comment]
> Okay, let's do EFI for VLI, but not for LI. This should be possible since we're using separate images.

yes

ok, I'll turn the key for the VLI image

**Comment by schaefi** [comment]
Done now, I have changed all VLI builds to build EFI images. Once everything has settled I will run our internal tests. As the image structure from a disk perspective is now very different I will do some sanity checks before we send a new image.

I'm working together with @jesusbv on this part and I plan for an updated image next week. As a side note next week is suse's hackweek and that means engineers are free to work on some project. Nevertheless I will try to get you a new image once it has build and tested successfully in our network.
