### ISSUE TITLE
Production image seems to have problem with UCS drivers

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#158]
I was given some new production images today to address SACK vulnerability, and the image (at least SLES 12 SP3 - image `SLES12-SP3-SAP-Azure-LI-BYOS.x86_64-1.0.55-Build1.26`) has a problem with ENIC/FNIC drivers:

```
sollabdsm32:/hana/shared/H31/SAP_HANA_DATABASE # rpm -qa | grep cisco
cisco-fnic-1.6.0.36-100R.11.3.x86_64
cisco-fnic-kmp-default-1.6.0.36_k4.4.73_5-100R.11.3.x86_64
cisco-enic-usnic-kmp-default-3.0.44.553.545.8_k4.4.73_5-100R.5.1.x86_64
sollabdsm32:/hana/shared/H31/SAP_HANA_DATABASE # 
```

Specifically, note that there are two flavors of fnic drivers (one `kmp`, one not). These are different driver architectures, you should only have `cisco-fnic-kmp-default...` for fnic (you should not have `cisco-fnic-1.6.0.36-100R.11.3.x86_64`).

This was a problem in the prior production image that we did not catch. I'll add this to our automation so we won't miss it again.

Can you get this resolved for future images (both production and test images)?

**Comment by jeffaco** [comment]
Hold on this please. I need to reach out to Cisco. It seems that one driver file is dependent on the other, and that's not what I expected. I'll reach out to Cisco and get back to you.

**Comment by jeffaco** [comment]
Okay, I've researched this (actually, I can't take credit, Jai researched it at my request).

OLD production image SLES 12 SP3:
```
# rpm -qa | grep -i cisco
cisco-fnic-1.6.0.36-100R.11.3.x86_64
cisco-fnic-kmp-default-1.6.0.36_k4.4.73_5-100R.11.3.x86_64
cisco-enic-usnic-kmp-default-3.0.44.553.545.8_k4.4.73_5-100R.5.1.x86_64
```

OLD production image SLES 12 SP4:
```
# rpm -qa | grep -i cisco
#
```

OLD production image SLES 15:
```
# rpm -qa | grep -i cisco
#
```

NEW production image SLES 12 SP3:
```
# rpm -qa | grep -i cisco
cisco-fnic-1.6.0.36-100R.11.3.x86_64
cisco-fnic-kmp-default-1.6.0.36_k4.4.73_5-100R.11.3.x86_64
cisco-enic-usnic-kmp-default-3.0.44.553.545.8_k4.4.73_5-100R.5.1.x86_64
```

NEW production image SLES 12 SP4:
```
# rpm -qa | grep -i cisco
#
```

NEW production image SLES 15:
```
# rpm -qa | grep -i cisco
#
```

In the SP3 case for both sets of images, these RPMs are causing problems getting the "right" RPMs installed. Note that in the SP4 case and SLES 15 case, RPMs aren't there but the right modules are loaded, as indicated by `lsmod | grep enic` and `lsmod | grep fnic`.

Can we get rid of the RPM installs for the Cisco drivers, leaving us with modules that are just loaded as needed. This leaves the system in a much cleaner state so we can install the proper drivers based on the UCS firmware version running on the blade.

Note that this is not a regression; we just missed it before. But I sure like the way you guys set up SLES 12 SP4 and SLES 15 in this regard!

**Comment by schaefi** [comment]
On SLES12 SP4 and SLES 15 the drivers are part of the default kernel. Therefore no extra packages need to be installed. On SLES12 SP3 the drivers are provided through the enterprise buildservice and are not part of the default kernel.

> Can we get rid of the RPM installs for the Cisco drivers,

if we do that the sle12 SP3 image will come without any cisco drivers. How should that work ?
Basically I hear you saying the drivers the enterprise buildservice provides are broken ?
If that is correct we should hand over this problem to the responsible people

> Note that this is not a regression; we just missed it before. 

May I ask how this could be missed in a production image ? the cisco stuff sounded like a fundamental important part to the system you can't live without. So you are saying we submitted an image with broken cisco drivers from the beginning on ?

**Comment by jeffaco** [comment]
I just saw this posting, somehow I wasn't notified of it earlier, sorry.

No, the kernel modules are mandatory. If the kernel drivers aren't provided in SLES 12 SP3, and if you didn't provide them by RPMs, then I suspect the system would fail to boot properly.

The real problem is that there's two sets of modules:

```
cisco-fnic-1.6.0.36-100R.11.3.x86_64
cisco-fnic-kmp-default-1.6.0.36_k4.4.73_5-100R.11.3.x86_64
```

I thought you used the kmp style or not, but when trying to delete, these appear to be dependent on one another. Maybe I'm mistaken? Are these two actually dependent on one another, or is there a dependency because they both provide similar bits? Please clarify (if you can).

As for your last question, this was missed for two reasons: (1) Due to an error on our part (I was as surprised as I think you'll be), the production image was not used until June 8th, despite the fact that we asked that to be used MUCH earlier, and (2) Due to a mess of blade firmware (different versions in just about every data center), we were going to leave figuring out the proper UCS version to install to Operations until we standardized on similar firmware across our fleet. We're executing on standardized firmware now, which is why this came up.

**Comment by rjschwei** [comment]
`cisco-fnic` is most likely code that is need in user space

`rpm -ql cisco-fnic`

will tell you which files the package provides. The `cisco-fnic-kmp-default` package provides the kernel module. The modules would be dependent on each other as the user space components make no sense without he kernel module and vice-versa.

If the firmware changes there is a good chance we would need updated drivers from Cisco. Those would have to be submitted to the enterprise build service. There is nothing we can do on our end.

Please contact Cisco and ask them what version of the drivers are needed for the firmware you are deploying and also to submit the code to the Enterprise Build service.

**Comment by jeffaco** [comment]
Cisco tends to deliver a version of firmware to SUSE that will at least allow you to boot. For a fully supported scenario, you're supposed to install a version of UCS drivers that match the blade firmware that's running on the blade (which is part of the service profile). That's why we have the package installation service.

The problem is that, with newer versions of Cisco drivers, only the kmp version of the driver is distributed:

```
Sollabdsm33:/mnt/image/Storage/Cisco/VIC/SLES/SLES12.3 # ls
LICENSE
README
cisco-fnic-kmp-default-1.6.0.50_k4.4.73_5-1.x86_64.rpm
fcc
fnic-1.6.0.50-SLES-DUD.iso
fnic-sles-1.6.0.50.tgz
fnic_trace.txt
Sollabdsm33:/mnt/image/Storage/Cisco/VIC/SLES/SLES12.3 #
```

That's the basis of this issue. On SLES 12 SP3, MUST `cisco-fnic-1.6.0.36-100R.11.3.x86_64` be installed? Could we get by with only `cisco-fnic-kmp-default-1.6.0.36_k4.4.73_5-100R.11.3.x86_64`, so that when we upgrade to 1.6.0.50 (assuming blade firmware 4.0(4), the upgrade is "clean" with no residual RPMs to deal with?

**Comment by rjschwei** [comment]
> Cisco tends to deliver a version of firmware to SUSE that will at least allow you to boot.

This is simply not correct. Cisco does not provide firmware to SUSE for distribution. We do not distribute a "cisco", "ucs", or "vic" branded firmware package. What is being built in the Enterprise Build Service is the `fcc` executable, and two kernel module packages (kmp). You can verify this by visiting

https://drivers.suse.com/index.php?vendor=Cisco&SLE=SLES12SP3&name=ucs

The package `cisco-fnic` provides a user space component, as I had suspected in my previous comment.

```
# rpm -ql cisco-fnic
/bin/fcc
# /bin/fcc --help
usage: fcc '[<cmd> [<hba> ...]]'

cmd:
	create 		Start FCoE on an ethernet interface.
	delete / del	Delete an FCoE instance
	destroy 	Same as delete
	enable / en	Same as create
	help		Show this usage message
	info		Show HBA detailed info
	list		List the HBAs with remote port and LUN status
	luns		Show LUN list and status
	stats		Show HBA statistics
	reset		Reset the HBA
	version		Show version
```
and the kmp package provides the Linux kernel driver.

> For a fully supported scenario, you're supposed to install a version of UCS drivers that match the blade firmware that's running on the blade (which is part of the service profile). That's why we have the package installation service.
> 
> The problem is that, with newer versions of Cisco drivers, only the kmp version of the driver is distributed:

Also incorrect, the listing you provide shows the `fcc` executable as being distributed with the "archive" you have. The `fcc` executable is what is distributed from EBS with the "cisco-fnic" RPM, as shown above.

> 
> ```
> Sollabdsm33:/mnt/image/Storage/Cisco/VIC/SLES/SLES12.3 # ls
> LICENSE
> README
> cisco-fnic-kmp-default-1.6.0.50_k4.4.73_5-1.x86_64.rpm
> fcc
> fnic-1.6.0.50-SLES-DUD.iso
> fnic-sles-1.6.0.50.tgz
> fnic_trace.txt
> Sollabdsm33:/mnt/image/Storage/Cisco/VIC/SLES/SLES12.3 #
> ```
> 
> That's the basis of this issue. On SLES 12 SP3, MUST `cisco-fnic-1.6.0.36-100R.11.3.x86_64` be installed? 

I was able to install "cisco-fnic-1.6.0.36-9.1.x86_64.rpm" on a system independently (the different version should not matter) I would be surprised if there is a reverse dependency from the kernel module onto the user space component.

However, the user space component, i.e. `/bin/fcc` provided by the "cisco-fnic" has no way of interfering with the functioning of the system and the interaction of the kernel module provided by "cisco-fnic-kmp-default". 

As pointed out above the listing shows that it contains `fcc`. So the difference here is simply that in EBS (Enterprise Build Service) we build an RPM package for the user space executable while the distribution of the new version (1.6.0.50) does not provide an RPM for the user space component but rather gives you the raw executable.

> Could we get by with only `cisco-fnic-kmp-default-1.6.0.36_k4.4.73_5-100R.11.3.x86_64`, so that when we upgrade to 1.6.0.50 (assuming blade firmware 4.0(4)), the upgrade is "clean" with no residual RPMs to deal with?

Yes, we can drop the installation of "cisco-fnic" but this removes the `/bin/fcc` executable and we do not know what processes in user space may be dependent on this executable. Based on the help of the executable I would say it looks rather important to keep the executable in place and when the upgrade to 1.6.0.50 happens a script should be executed that removes the package "cisco-fnic" at that time and then puts the `fcc` version from the new tarball in place. This is going to be the only way to provide a "clean" rpm list, which is what you appear to be after. My gut feel is that we do not want to remove the `bin/fcc` executable.

**Comment by jeffaco** [comment]
> > Cisco tends to deliver a version of firmware to SUSE that will at least allow you to boot.
> 
> This is simply not correct. Cisco does not provide firmware to SUSE for distribution.

Sorry, this was a typo. I know Cisco doesn't distribute *firmware* to SUSE. I meant to say that Cisco tends to deliver a version of a driver to SUSE that will at least allow you to boot. But the rest of what I said was absolutely correct:

>For a fully supported scenario, you're supposed to install a version of UCS drivers that match the blade firmware that's running on the blade (which is part of the service profile). 

Next:

> > For a fully supported scenario, you're supposed to install a version of UCS drivers that match the blade firmware that's running on the blade (which is part of the service profile). That's why we have the package installation service.
> > The problem is that, with newer versions of Cisco drivers, only the kmp version of the driver is distributed:
> 
> Also incorrect, the listing you provide shows the `fcc` executable as being distributed with the "archive" you have. The `fcc` executable is what is distributed from EBS with the "cisco-fnic" RPM, as shown above.

No, this is correct. If you follow [Cisco's instructions on how to install the RPMs](https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/sw/vic_drivers/install/Linux/b_Cisco_VIC_Drivers_for_Linux_Installation_Guide/b_Cisco_VIC_Drivers_for_Linux_Installation_Guide_chapter_010.html), it talks about only installing the "kmp" rpm, like this:

```
rpm -ivh cisco-enic-kmp-default-version-0.x86_64.rpm 
```

This is for enic, the same applies to fnic (fiber). 

I think the change here is that, in future versions of enic/fnic RPMS, the "kmp" style RPMs appear to supply the `/bin/fcc` binary in a single RPM with the driver. This creates a situation where two packages supply the same executable upon upgrading the drivers:

```
azurehost1:~ # rpm -Uvh cisco-fnic-kmp-default-1.6.0.50_k4.4.73_5-1.x86_64.rpm
  <output squashed>
azurehost1:~ # rpm -qf /bin/fcc
cisco-fnic-1.6.0.36-100R.11.3.x86_64
cisco-fnic-kmp-default-1.6.0.50_k4.4.73_5-1.x86_64
azurehost1:~ # 
```

I was hoping to avoid this oddity. But given that it only seems to occur on SLES 12 SP3, and given that SLES 12 SP3 should not be used in new installations anyway (hopefully customers will honor this, I have no control over that), this situation will presumably phase out over time.

Ultimately, though, this is why I was asking if `cisco-fnic-1.6.0.36-100R.11.3.x86_64` could be skipped on SLES 12 SP3. It's already not on SLES 12 SP4 and SLES 15. And ultimately, it will be there once we install proper (supported) drivers from Cisco.

**Comment by rjschwei** [comment]
If we do not install `cisco-fnic` then the executable will not be in the image. My guess is something else will break, but I have no way to verify this.

That Cisco does not set the `Obsoletes` directive in their new package that would force the removal of "cisco-fnic-1.6.0.36-100R.11.3.x86_64" is a packaging bug on their side. We SUSE cannot fix that. 

The way I see it we have 3 choices:
1.) We build an image without "cisco-fnic"
  - There is a good chance that the image will be broken as `/bin/fcc` will be missing
  - We (SUSE) have no way to verify the effect of the removal of `/bin/fcc`
2.) We get Cisco to push the new code to EBS and then packages can be created that match the same setup and behave properly on update
3.) We get Cisco to fix the package they provide

Given the risk of option 1 and no means to verify the effects, it is hopefully understandable that we do not want to ship you a broken image. We also would rather avoid the "remove it, of it's broken, add it back in" cycle.

**Comment by jeffaco** [comment]
Yeah, a bunch of crappy options. I see your point with issue 1. Yes, we would promptly install the `/bin/fcc` package with installation of the kmp package. But it doesn't make sense that the O/S from SUSE not be functionally complete.

I think doing issue 2 or issue 3 would take a while. Given that this doesn't happen in newer releases, I guess I'll just let this pass. Yeah, it's ugly, but it's not going to cause a defect as such. The package will install properly, and the fact that two packages deliver the same file is something that won't cause a system error.

I'll go ahead and close this issue. Thanks for your consideration.

Note that #162 is still relevant here, and is unaffected by this.
