### ISSUE TITLE
Need module parameter specified for sunrpc

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#159]
We need a module parameter via something like:

```
echo "options sunrpc tcp_max_slot_table_entries=128" > /etc/modprobe.d/sunrpc.conf
```

This is a new requirement, and relates to both LI and VLI.

For background, see [NetApp Documentation], page 22.

**Comment by jeffaco** [comment]
Note: I updated the base posting. This relates to both LI and VLI.

**Comment by jesusbv** [comment]
This issue was fixed and currently waiting to be included in the next release

**Comment by schaefi** [comment]
Closing as fixed. Jesus has provided a testing image that applies the change. On agreement of a new production release of the image the respective bugzilla report will be closed too
