### ISSUE TITLE
VLI: Need additional boot parameters of "intel_pstate=disable clocksource=tsc "

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#160]
Much like issue #113, we need a few additional boot line parameters for VLI images only:

```
intel_pstate=disable 
clocksource=tsc 
```

Please add this to the VLI images for all O/S versions supported, thanks.

**Comment by schaefi** [comment]
We will update the image using this setting. However I really wonder how you could come to this conclusion when we currently at the stage that the image does not boot in your environment ??

**Comment by jeffaco** [comment]
We know how we need to set up the O/S for existing installations. We're going through that list now so we can get everything we need here into documented issues ...

**Comment by schaefi** [comment]
ok but please note, existing installations, probably done through yast, have no common ground compared to the image we deliver. In any case I agree it's good to have this setup instructions documented here. Thanks for doing this. I just wanted to point out that it feels strange to see this type of issues when we actually don't have a booting version of the delivered image in your environment.

That having said we are still blocked on the boot problem you have. I can't reproduce this and I also don't see a mistake in the image itself. I hope this falls into the category of the "small pain points" you mentioned in your farewell e-mail.

**Comment by jeffaco** [comment]
I know you're still blocked on the VLI booting issue, I asked Jai to look at that further and follow up with you. It's very strange in that:

1. For VLI image installed by DVD, we have a NetApp LUN exposed to the machine. This is expected and provides the system disk.

1. For VLI image installed with your image, we have a (different) NetApp LUN exposed to the machine. This is identical to what we were doing with LI. So I'm at a loss to explain why the system doesn't see the LUN.

I did ask Jai to perform a test where both boot LUNs are configured at once (to make sure they were both seen as expected, but only one would be bootable). But to our surprise, the O/S on the DVD LUN became corrupted (read-only F/S for no obvious reason). That's being rebuilt now, and then Jai can perform that test. That may provide some clarity in this area.

**Comment by jesusbv** [comment]
This issue was fixed and currently waiting to be included in the next release

**Comment by schaefi** [comment]
Closing as fixed. Jesus has provided a testing image that applies the change. On agreement of a new production release of the image the respective bugzilla report will be closed too
