### ISSUE TITLE
VLI: New ports opened in firewall for SFS

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#161]
For VLI, we need have additional ports open for SFS (Software Foundation Services).

For SFS, we need ports 3128 (TCP) and 53 (TCP & UDP) open in addition to the other (LI) ports. This is so that SFS can "phone home" with hardware issues.

We're going through VLI issues now that we're starting the VLI process, and this came up.

**Comment by schaefi** [comment]
Can you provide us with a working etc/sysconfig/SuSEfirewall2 file. This makes integration into the image build process more reliable. Otherwise I just add a change from your explanation but I can't test it. Thanks

**Comment by jeffaco** [comment]
Okay, here you go, [/etc/sysconfig/SuSEfirewall2](https://github.com/SUSE-Enceladus/azure-li-services/files/3370327/SuSEfirewall2.txt)

**Comment by schaefi** [comment]
Thanks

**Comment by jesusbv** [comment]
This issue was fixed and currently waiting to be included in the next release

**Comment by schaefi** [comment]
Closing as fixed. Jesus has provided a testing image that applies the change. On agreement of a new production release of the image the respective bugzilla report will be closed too
