### ISSUE TITLE
need PasswordAuthentication to be set to yes"

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#165]

**Comment by jaawasth** [comment]
Hi Team,

We need to have "PasswordAuthentication yes" setting in /etc/ssh/sshd_config file, 
currently PasswordAuthentication  is being set to "no" and the customer faced issues while logging in via password.
Can you please make this change in next release.

Thanks !!

**Comment by rjschwei** [comment]
The implementation of the system setup code does not modify the value of `PasswordAuthentication` neither is this value modified in the image build, I checked all image build configurations.

Either the system was deployed from an older image that still modified this value or the user has a configuration system running that sets the value to a secure setting to disallow password based login. In any event there is nothing for us to do.
