### ISSUE TITLE
SBD configuration issue with LI SLES15 and SLES15SP1 images 

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#170]
Hi Team,

With both of the below images :

SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.5-Build1.75.raw
SLES15-SP1-SAP-Azure-LI-BYOS.x86_64-1.0.1-Build1.77.raw

I'm seeing the below error messages.

> sollabdsm32:~ #  systemctl status -l azure-li-system-setup
Warning: azure-li-system-setup.service changed on disk. Run 'systemctl daemon-reload' to reload units.
● azure-li-system-setup.service - System Setup of Azure Li/VLi machine
   Loaded: loaded (/usr/lib/systemd/system/azure-li-system-setup.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Tue 2019-09-10 06:09:44 UTC; 2min 58s ago
  Process: 5646 ExecStart=/usr/bin/azure-li-system-setup (code=exited, status=1/FAILURE)
 Main PID: 5646 (code=exited, status=1/FAILURE)
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]: Traceback (most recent call last):
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]:   File "/usr/bin/azure-li-system-setup", line 11, in <module>
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]:     load_entry_point('azure-li-services==1.1.36', 'console_scripts', 'azure-li-system-setup')()
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]:   File "/usr/lib/python3.6/site-packages/azure_li_services/units/system_setup.py", line 92, in main
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]:     raise AzureHostedException(system_setup_errors)
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]: azure_li_services.exceptions.AzureHostedException: [AzureHostedCommandException('sbd: stderr: sbd failed; please check the logs.\n, stdout: Initializing device /dev/disk/by-path/ip-10.20.253.31:3260-iscsi-iqn.1992-08.com.netapp:s>
Sep 10 06:09:44 sollabdsm32 systemd[1]: azure-li-system-setup.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 06:09:44 sollabdsm32 systemd[1]: Failed to start System Setup of Azure Li/VLi machine.
Sep 10 06:09:44 sollabdsm32 systemd[1]: azure-li-system-setup.service: Unit entered failed state.
Sep 10 06:09:44 sollabdsm32 systemd[1]: azure-li-system-setup.service: Failed with result 'exit-code'.

I deployed SLES12SP4 "SLES12-SP4-SAP-Azure-LI-BYOS.x86_64-1.0.6-Build1.2.raw" version on the same host and that is deployed without any issues.

Can you please take a look.

Thanks !!

**Comment by schaefi** [comment]
I think this is related to the network setup. the sbd device is an iscsi network. I guess the path is not there because the network was not up. Can you clarify this from the log file ? If we run into a timing issue here the same patch as #164 is needed

Thanks

**Comment by jaawasth** [comment]
The network is already up, I'm able to login to the host from jumpbox. As well storage devices are mounted on the host.
I tried with SLES12 sp4 image as well to see if there are any iscsi related issues, but that image works fine, apart from the image version, I'm using the same yaml file and host [as forSLES12 sp4] but I'm getting this error.

Pasting some additional logs [I'll forward you the log file as well]

> Sep 10 06:09:44 sollabdsm32 iscsid[5472]: iscsid: Kernel reported iSCSI connection 2:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)
Sep 10 06:09:44 sollabdsm32 kdump[19981]: Loaded kdump kernel: /sbin/kexec -p /boot/vmlinuz-4.12.14-150.32-default --append="net.ifnames=1 mce=ignore_ce nomodeset numa_balancing=disable transparent_hugepage=never intel_idle.max_cstate=1 processor.max_cstate=1 rw elevator=deadline sysrq=yes reset_devices acpi_no_memhotplug cgroup_disable=memory nokaslr irqpoll nr_cpus=1 root=kdump rootflags=bind rd.udev.children-max=8 disable_cpu_apicid=0   panic=1" --initrd=/boot/initrd-4.12.14-150.32-default-kdump  -s, Result:
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]: Traceback (most recent call last):
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]:   File "/usr/bin/azure-li-system-setup", line 11, in <module>
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]:     load_entry_point('azure-li-services==1.1.36', 'console_scripts', 'azure-li-system-setup')()
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]:   File "/usr/lib/python3.6/site-packages/azure_li_services/units/system_setup.py", line 92, in main
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]:     raise AzureHostedException(system_setup_errors)
Sep 10 06:09:44 sollabdsm32 azure-li-system-setup[5646]: azure_li_services.exceptions.AzureHostedException: [AzureHostedCommandException('sbd: stderr: sbd failed; please check the logs.\n, stdout: Initializing device /dev/disk/by-path/ip-10.20.253.31:3260-iscsi-iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6-lun-0\n',)]

Thanks !!

**Comment by schaefi** [comment]
So this is the call we issued:

```bash
sbd -d /dev/disk/by-path/ip-10.20.253.31:3260-iscsi-iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6-lun-0 create
```

You can go and test on your system if 

a) the device exists
b) repeat the call from above and try to debug why the connection broke

In any case the device information for the sbd device is provided via the config file and given that data is correct there is not much we can do here. The iscsi backend is under your control and we have no pointer to debug this.

Thanks

**Comment by schaefi** [comment]
You can also check if the discovery output from the iscsiadm command matches our expectations.
If you take a look in the code I wrote:

```python
 # 4. create sbd device
    # The first line of the iscsiadm discovery output is taken into
    # account as we expect any group tag to respond with the same
    # target name. We also expect the discovery output to be in the
    # format: target_IP:port,target_portal_group_tag proper_target_name
    discovery_format = '.*:.*,.* .*'
    if discovery_output and re.match(discovery_format, discovery_output[0]):
        ...
```

I think this is correct because on a wrong match an "Unexpected iSCSI discovery information" exception is thrown by the code. But it's still worth checking

**Comment by jaawasth** [comment]
We are able to discover the sbd lun with sles12 sp4 [all commands mentioned below]
Running these same set of commands on sles15, we are not able to discover the lun.

iscsiadm --mode node --logout all
iscsiadm --mode discoverydb --type sendtargets --portal 10.20.253.31 -o delete
iscsiadm --mode discovery --type sendtargets --portal 10.20.253.31
iscsiadm --mode node --portal 10.20.253.31 --login

I'm looking into it, but incase you also hit upon anything please do let me know

**Comment by jaawasth** [comment]
I tried again, after running the above commands, it takes some time for the sbd lun device to be discovered.
I'm now able to issues the following command and sbd setup is done

> sbd -d /dev/disk/by....  create

Can we try to increase timeouts and see if that will work ?

**Comment by jaawasth** [comment]
Sorry, the above isn't entirely true.
I tried a couple of things as well as the above commands.
Running Simply the above said commands, doesn't discover the sbd device.

If on a newly deployed system i just run the below command

>  systemctl restart iscsi iscsid

I'm able to discover the sbd lun.
Can you please check why the iscsi services are not running or why if there needs to be increased timouts before creating the sbd device.

**Comment by schaefi** [comment]
both services iscsi and iscsid are running. I do not understand why a restart of the service is needed. On a freshly deployed system please check:

```
systemctl status iscsi
systemctl status iscsid
```

both states should be "active running" if this is the case a restart is not needed.

I'm confused about the timeouts though. By default sbd has set plenty of timeouts, 120s for device discovers, 240s for the watchdog. Without access to the infrastructure I can't help you with timeouts.

In my previous comment I asked if you can see the storage device /dev/disk/.. to be created ?
So on a fresh deployed system can you check if the device is present ? if yes you can focus on the sbd call and why it fails, if not we have to focus why the storage device is not present.

Thanks

**Comment by schaefi** [comment]
Please also remember, I don't have access to your iscsi infrastructure. My test inhouse stops at the level of checking if iscsi and iscsid services are up. I can confirm they are up. All the rest I can test is based on mock regarding your documentation:

* https://github.com/SUSE-Enceladus/azure-li-services/blob/master/test/unit/units/system_setup_test.py#L295

So what I need from you is a review of this process on sle15 and unfortunately I rely on clear instructions what needs to be changed if something does not work because I can't access the infrastructure. So playing with timeouts or guessing from my side is probably not very helpful.

Hope that clarifies a bit on roles and responsibilities. Thanks

**Comment by jaawasth** [comment]
The devices "/dev/disk/by-path/ip-*" are not created.

sollabdsm31:~ # systemctl status iscsi

> ● iscsi.service - Login and scanning of iSCSI devices
Loaded: loaded (/usr/lib/systemd/system/iscsi.service; enabled; vendor preset: enabled)
   Active: active (exited) since Wed 2019-09-18 09:00:50 UTC; 3min 38s ago
     Docs: man:iscsiadm(8)
           man:iscsid(8)
 Main PID: 5596 (code=exited, status=21)
    Tasks: 0 (limit: 29491)
   CGroup: /system.slice/iscsi.service
~
Sep 18 09:00:50 localhost systemd[1]: Starting Login and scanning of iSCSI devices...
Sep 18 09:00:50 localhost iscsiadm[5596]: iscsiadm: No records found
Sep 18 09:00:50 localhost systemd[1]: Started Login and scanning of iSCSI devices.


sollabdsm31:~ # systemctl status iscsid

> ● iscsid.service - Open-iSCSI
Loaded: loaded (/usr/lib/systemd/system/iscsid.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-09-18 09:00:50 UTC; 3min 48s ago
     Docs: man:iscsid(8)
           man:iscsiuio(8)
           man:iscsiadm(8)
 Main PID: 5563 (iscsid)
   Status: "Ready to process requests"
    Tasks: 1 (limit: 29491)
   CGroup: /system.slice/iscsid.service
           └─5563 /sbin/iscsid -f                                                                                                                                                                                                                                            24,1          All
Sep 18 09:00:50 localhost systemd[1]: Starting Open-iSCSI...
Sep 18 09:00:50 localhost systemd[1]: Started Open-iSCSI.
Sep 18 09:00:51 sollabdsm31 iscsid[5563]: iscsid: Connection1:0 to [target: iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6, portal: 10.20.253.31,3260] through [iface: default] is operational now
Sep 18 09:00:51 sollabdsm31 iscsid[5563]: iscsid: Connection2:0 to [target: iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6, portal: 10.20.253.42,3260] through [iface: default] is operational now
Sep 18 09:00:51 sollabdsm31 iscsid[5563]: iscsid: Connection3:0 to [target: iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6, portal: 10.20.253.32,3260] through [iface: default] is operational now
Sep 18 09:00:51 sollabdsm31 iscsid[5563]: iscsid: Connection4:0 to [target: iqn.1992-08.com.netapp:sn.562892c1030b11e9b8ec00a098d274e4:vs.6, portal: 10.20.253.41,3260] through [iface: default] is operational now

however, now, if i restart the iscsi services, the storage devices "/dev/disk/by-path/ip-10.*"  are created 

If it's not possible debugging at your end, I can setup a screen share session.

Thanks !!

**Comment by schaefi** [comment]
> The devices "/dev/disk/by-path/ip-*" are not created.

ok, that's what I guessed. Good with that information I can come up with a patch. Expect a pull
request soon

Thanks

**Comment by schaefi** [comment]
re-open for tracking image update
