### ISSUE TITLE
LI: SLES15-SP1, java package not installed

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#171]
Hi Marcus,

We expect java package "java-1_8_0-ibm" to be installed with SLES15 images.
This package is missing with the image  "SLES15-SP1-SAP-Azure-LI-BYOS.x86_64-1.0.1-Build1.77.raw"

Can you please check.

Thanks !!

**Comment by schaefi** [comment]
I've updated the sle15 GA and SP1 builds

```
Added java-1_8_0-ibm
```
