### ISSUE TITLE
LI: SLES15; SLES15-SP1

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#172]
Hi Marcus,

As per issue https://github.com/SUSE-Enceladus/azure-li-services/issues/149 
It seems that the issue got resolved.

But even with the new images the current active profile is still "saptune"

> sollabdsm32:~ # tuned-adm active
Current active profile: saptune

> sollabdsm32:~ # tuned-adm list
Available profiles:
>- balanced                    - General non-specialized tuned profile
>- cpu-partitioning            - Optimize for CPU partitioning
>- desktop                     - Optimize for the desktop use-case
>- latency-performance         - Optimize for deterministic performance at the cost of increased power consumption
>- network-latency             - Optimize for deterministic performance at the cost of increased power consumption, focused on low latency network performance
>- network-throughput          - Optimize for streaming network throughput, generally only necessary on older CPUs or 40G+ networks
>- powersave                   - Optimize for low power consumption
>- sapconf                     - Optimize for SAP workloads like NetWeaver, SAP HANA and HANA based products
>- saptune                     - Comprehensive system optimisation with saptune
>- throughput-performance      - Broadly applicable tuning that provides excellent performance across a variety of common server workloads
>- virtual-guest               - Optimize for running inside a virtual guest
>- virtual-host                - Optimize for running KVM guests
Current active profile: saptune

`sollabdsm32:~ #  saptune daemon status
Daemon (tuned.service) is running.
The system has been tuned for the following solutions and notes:
        HANA
`

Can you please let me know if this still needs fixing.

Thanks !!

**Comment by schaefi** [comment]
This is the sequence that has proven to work on sle12.

```python
def set_saptune_service():
    profile = 'sapconf'
    if os.path.exists('/usr/lib/tuned/sap-hana'):
        profile = 'sap-hana'
    Command.run(
        ['saptune', 'daemon', 'start']
    )
    Command.run(
        ['tuned-adm', 'profile', profile]
    )
    Command.run(
        ['systemctl', 'start', 'tuned']
    )
    Command.run(
        ['systemctl', 'enable', 'tuned']
    )
    Command.run(
        ['tuned-adm', 'profile', profile]
    )
    Command.run(
        ['saptune', 'solution', 'apply', 'HANA']
    )
    Command.run(
        ['saptune', 'daemon', 'start']
    )
```

I expect this to work on sle15 in the same way. Please verify in the log if you can find any saptune related problems. I guess not because otherwise the system_setup service would have a failed state.

```
saptune daemon status Daemon (tuned.service) is running. The system has been tuned for the following solutions and notes: HANA
```

This looks correct to me

**Comment by jaawasth** [comment]
The current active profile should be "sapconf" what we see is "saptune". is this expected ?

**Comment by jeffaco** [comment]
The name of the profile depends on the version of SuSE, see [here](https://github.com/SUSE-Enceladus/azure-li-services/issues/142#issuecomment-494171785).

**Comment by schaefi** [comment]
As you can see we handle it that way. 

```
profile = 'sapconf'
    if os.path.exists('/usr/lib/tuned/sap-hana'):
        profile = 'sap-hana'
```

So on your system does '/usr/lib/tuned/sap-hana' exist y|n ?

**Comment by schaefi** [comment]
All this was already resolved, why do we again see this weird sap tooling behavior ? Was there any change we don't know about ?

**Comment by jaawasth** [comment]
sap-hana doesn't exist.
But the profile name should be "sapconf" which exists [please see the issue description]
the active profile is "saptune" which is what i'm saying.
Even from the code snippet if "sap-hana" doesnt exist, we need to apply "sapconf" but what we get as active profile is "saptune"

**Comment by schaefi** [comment]
> But the profile name should be "sapconf" which exists [please see the issue description]

I know, please see the code, we apply sapconf

**Comment by schaefi** [comment]
The problem here we apply sapconf but it has no effect. I have an instance running here where I can see that

**Comment by jaawasth** [comment]
Applied the same steps to SLES15 image as well as a SP4 image :

1.  saptune daemon start
2.  tuned-adm profile sapconf
3.   systemctl start tuned
4.  systemctl start tuned
5.  systemctl enable tuned
6.  tuned-adm profile sapconf
7.   saptune solution apply HANA

With SLES15 image, I'm getting the below error [which is not present in SLES12 SP4]
INFO: There is already one solution applied. Applying another solution is NOT supported.

Running "saptune daemon start" on SLES12 SP4 activates sap-hana profile
while running the same command on SLES15 changes the active profile to "saptune"

Let me check on this, and I will get back to you.

**Comment by schaefi** [comment]
I tested the behavior. So

```tuned-adm profile sapconf``` activates the profile and ```tuned-adm active``` says sapconf
So far so good. ```saptune solution apply HANA``` and the subsequent restart of ```saptune daemon restart``` resets the active profile back to saptune

Whatever these things does it always seems broken to me

**Comment by schaefi** [comment]
Correct, so we both have the same observations. I can only implement one sequence to start this and I would say ```tuned-adm profile sapconf``` should survive a restart of the daemon. To me this smells like a bug in the tooling

**Comment by jaawasth** [comment]
Hi Marcus,

It does seem we can't configure both saptune & sapconf.
So, i had an internal discussion on this, 
For SLES15 we can just configure sapconf and not apply saptune HANA solution.

We have come with below steps for configuration :   

mkdir /etc/tuned/sapconf 
cp /usr/lib/tuned/sapconf/tuned.conf /etc/tuned/sapconf/tuned.conf
cd /etc/tuned/
chmod -R 777 sapconf
cd sapconf
vi tuned.conf
[edit cpu field to]
force_latency = 70
[edit script field to]
script = /usr/lib/tuned/sapconf/script.sh
systemctl restart sapconf.service
tuned-adm profile sapconf

Please let us know if you can make this change.

Thanks !!

**Comment by schaefi** [comment]
This sounds to me like we need a custom version of /etc/tuned/sapconf/tuned.conf that changes

* force_latency
* script 

to the values you suggested. This change can be done in an overlay as part of the image description.

The other change I see is that we should _NOT_ call

* saptune solution apply HANA

as part of the startup sequence in the instance services here. Is that correct ?

If so is this a change that is because of a tool difference between sles12 and sles15 ?
Is this change backward compatible ? meaning also working for sle12. If it's not backward compatible how do we found which toolset saptune/sapconf requires which startup sequence ?

I know this is not your project but if you are already talking to the guys that develop those tools can you bring up the question why they have different and incompatible startup sequences ?
From my understanding all this should be just simple. There is a config and a service, start the service and be done. Can somebody on the sap side please be informed that there is room for improvement.

Thanks a ton

**Comment by jaawasth** [comment]
> as part of the startup sequence in the instance services here. Is that correct ?

Yes that is correct

> If so is this a change that is because of a tool difference between sles12 and sles15 ?

Yes, we are not able to configure both HANA solution as well as sapconf at the same time with SLES15, this was not the case with SLES12SP4

> Is this change backward compatible ? meaning also working for sle12

No this is just for SLES15.
With SLES15 what i have seen is that if i configure sapconf then HANA solution gets reverted and vice versa.
I can check with SLES12 that if we apply HANA solution first, then with the application of sapconf profile does it get reverted, if not maybe we can use this solution, because in that case for SLES15, although HANA solution gets reverted but it's fine because anyway we want just sapconf profile to be configured, does this look ok to you ?

> I know this is not your project but if you are already talking to the guys that develop those tools can you bring up the question why they have different and incompatible startup sequences ?
From my understanding all this should be just simple. There is a config and a service, start the service and be done. Can somebody on the sap side please be informed that there is room for improvement.

Let me bring all related parties on this thread itself so we can directly figure out whats best and get all our queries answered.

**Comment by schaefi** [comment]
Thanks maybe we can find a solution that does not require us to add code like

```python
if sles15:
    sequence_a
elif sles12:
    sequence_b
```

It really should not be necessary and it would be the first time we have to take that into account. Let's find a better solution. Maybe we can distinguish by a file or version information.

I'm setting this to blocked until we got clarity

**Comment by amishp1971** [comment]
We need to understand that these are all SAP recommendations and not Part of something that Azure mandates.  The reason we are trying to incorporate these directly into the image is to make life easier for the end customers when they get the server, its already configured for SAP HANA related recommendations from SAP and SuSE.

**Comment by schaefi** [comment]
I completely agree and I understood what you have said. Making it easier for the customer means pre-populating configuration, settings and services, which we all do in our image. Regarding saptune and sapconf these are helpers to setup the system in a way an SAP workload needs it which is great.

However those tools are just services and I would expect them to function as such. This means there is a configuration which we can handle individually for sle12 and sle15 as we need it but the process to start the service should be the same.

I understand we want to make live easier for customer but that does not mean live has to be complex for us trying to make it easier for customers.

Therefore I'm still aiming for information about a startup sequence for those tools which works for sle12 and sle15. If we understand why saptune and sapconf could be used in combination on sle12 but can't be used in combination on sle15 we will have a chance to come up with code that explicitly states that and can be understood by readers.

If we just blindly follow a startup sequence without knowing why it is done that way things becomes complex, for us, for customers for everybody.

I want to avoid that.

To be honest take a look at the current startup procedure of those tools, it's already weird and that empiric way of debugging it should come to an end. It's already completely unclear to me why ```saptune daemon start``` hast to be called twice.

With any iteration of such and now even facing a conditional switch all this will become a nightmare to maintain. If something is hard to maintain the customers are those who suffers from it.

Let's do the right thing, get in contact with them, start a discussion, find a good solution.

I don't have contact details to the team writing sapconf/saptune and was hoping you guys could help us in this regard.

Thanks much

**Comment by amishp1971** [comment]
There is a Linux Lab in Germany which consists of SuSE engineers / RedHat Enginners / SAP Linux Team.  Let me see if I can get the name of the Suse Contact from there or the SAP contact from there.

**Comment by amishp1971** [comment]
Bernd Schubert is the guy from SuSE who might be able to help us with this.    Can you please try to ping him internally?

**Comment by rjschwei** [comment]
@amishp1971 I have already reached out internally at SUSE to get help and clarification around this topic. Sorry for making you chase information. I just caught up to this discussion today and sent the e-mail. I was not aware that you were chasing this until after I alreday reached out internally at SUSE.

**Comment by amishp1971** [comment]
Hey Robert, No worries. Lets hope that Bernd can help us with this as he sits with the SAP's Linux Lab team in Germany and talks to them all the time.

**Comment by schaefi** [comment]
Thanks Robert, I saw your e-mail and did not sent mine :-) I'll hope we get some feedback. Keeping the blocked label until there is clarity for a solution. Thanks
