### ISSUE TITLE
SLES15 sbd device needs to wait for udev to finish

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#179]
Hi Marcus,

With the new image provided "SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.4-Devel-Build4.11.raw"

I'm seeing  below error :

Oct 01 08:36:28 sollabdsm32 azure-li-system-setup[5697]: Traceback (most recent call last):
Oct 01 08:36:28 sollabdsm32 azure-li-system-setup[5697]:   File "/usr/bin/azure-li-system-setup", line 11, in <module>
Oct 01 08:36:28 sollabdsm32 azure-li-system-setup[5697]:     load_entry_point('azure-li-services==1.1.39', 'console_scripts', 'azure-li-system-setup')()
Oct 01 08:36:28 sollabdsm32 azure-li-system-setup[5697]:   File "/usr/lib/python3.6/site-packages/azure_li_services/units/system_setup.py", line 86, in main
Oct 01 08:36:28 sollabdsm32 azure-li-system-setup[5697]:     raise AzureHostedException(system_setup_errors)
Oct 01 08:36:28 sollabdsm32 azure-li-system-setup[5697]: azure_li_services.exceptions.AzureHostedException: [AzureHostedCommandException('sbd: stderr: sbd failed; please check the logs.\n, stdout: Initializing device /dev/disk/by-path/ip-10.20.213.41:3260-iscsi-iqn.1992-08.com.netapp:sn.98a704f9dfb811e9988d00a098d3b5f1:vs.19-lun-0\n',)]

The device " /dev/disk/by-path/ip-10.20.213.41:3260-iscsi-iqn.1992-08.com.netapp:sn.98a704f9dfb811e9988d00a098d3b5f1:vs.19-lun-0" exists on the host, post deployment.

I ran the command "sbd -d device create" and was able to run it without error, but during deployment time there is error running it.

Can you also please take a look.

Thanks !!

**Comment by schaefi** [comment]
Please provide the log file

* /var/log/azure-li-services.log

Thanks

**Comment by jaawasth** [comment]
Log links : 
workload.log
https://imagestoreaccount.blob.core.windows.net/logs/workload_SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.4-Devel-Build4.11.log

azure-li-service.log
https://imagestoreaccount.blob.core.windows.net/logs/azure-li-service_SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.4-Devel-Build4.11.log

**Comment by schaefi** [comment]
Ok so to be honest I don't understand it. The sequence applies exactly the steps including the latest fix with the restart of the scsi subsystem:

```
Calling: ['iscsiadm', '-m', 'discovery', '-t', 'st', '-p', '10.20.213.41:3260']
Calling: ['iscsiadm', '-m', 'node', '-l']
Calling: ['rescan-scsi-bus.sh']
Calling: ['systemctl', 'restart', 'iscsi']
Calling: ['systemctl', 'restart', 'iscsid']
Calling: ['sbd', '-d', '/dev/disk/by-path/ip-10.20.213.41:3260-iscsi-iqn.1992-08.com.netapp:sn.98a704f9dfb811e9988d00a098d3b5f1:vs.19-lun-0', 'create']
```

Do you see any error in that sequence ?

Could it be a timeout issue ?

Does the log written by sbd show more details ?

Thanks

**Comment by jaawasth** [comment]
The previous issue is fixed with this build [when even the sbd device was not available on host]
It could be a timeout issue, as when i ran the create/dump commands on the device, there were no issues but during deployment these do fail.

I have provided the workload.log which shows errors during image deployment, that has little info about the error. Where may i find the sbd logs.

**Comment by schaefi** [comment]
the sbd logs are on the system, I guess below /var/log/sbd...

**Comment by jaawasth** [comment]
I guessed the same but there is no such directory as /var/log/sbd

**Comment by jaawasth** [comment]
I can setup a call to discuss this issue further, please let me know if that works for you.

**Comment by jaawasth** [comment]
I ran the below commands in succession as a script

iscsiadm -m discovery -t st -p 10.20.213.41:3260
iscsiadm -m node -l
rescan-scsi-bus.sh
systemctl restart iscsi
systemctl restart iscsid
sbd -d /dev/disk/by-path/ip-10.20.213.32:3260-iscsi-iqn.1992-08.com.netapp:sn.98a704f9dfb811e9988d00a098d3b5f1:vs.19-lun-1 create

I'm able to observe the same error as during deployment.
sbd failed; please check the logs.

If now i sleep for 1 second after "systemctl restart iscsid" things work fine.

I tried grepping  sbd in logs directory but i dont see any errror still, so not sure where the logs are going but that's a separate issue.

Can we add a sleep statement after iscsi services restart ?

**Comment by schaefi** [comment]
Hrm, sleeps are evil and strike back :-) I think we have to wait for udev to get the devices created. I suggest to add a

* udevadm settle --timeout=30

max timeout will then be 30sec before we continue. If udev has operated on the queue it will return earlier.

Thanks for the tests that should lead us to a solution

**Comment by jaawasth** [comment]
Sure, this looks fine to me, thanks !

**Comment by jaawasth** [comment]
Hi Marcus / Jesus

I'm still seeing this behavior with the latest set of images provided :  
SLES15-SP1-SAP-Azure-LI-BYOS.x86_64-1.0.5-Devel-Build4.13.raw.xz
SLES15-SP1-SAP-Azure-VLI-BYOS.x86_64-1.0.5-Devel-Build4.13.raw.xz

log snippet below 

> ● azure-li-system-setup.service - System Setup of Azure Li/VLi machine
   Loaded: loaded (/usr/lib/systemd/system/azure-li-system-setup.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2019-10-24 00:00:41 UTC; 949ms ago
  Process: 5740 ExecStart=/usr/bin/azure-li-system-setup (code=exited, status=1/FAILURE)
 Main PID: 5740 (code=exited, status=1/FAILURE)
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]: Traceback (most recent call last):
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]:   File "/usr/bin/azure-li-system-setup", line 11, in <module>
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]:     load_entry_point('azure-li-services==1.2.1', 'console_scripts', 'azure-li-system-setup')()
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]:   File "/usr/lib/python3.6/site-packages/azure_li_services/units/system_setup.py", line 86, in main
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]:     raise AzureHostedException(system_setup_errors)
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]: azure_li_services.exceptions.AzureHostedException: [AzureHostedCommandException('sbd: stderr: sbd failed; please check the logs.\n, stdout: Initializing device /dev/disk/by-path/ip-10.20.213.41:3260-iscsi-iqn.1992-08.com.netapp:sn.98a704f9dfb811e9988d00a098d3b5f1:vs.19-lun-0\n',)]
Oct 24 00:00:41 sollabdsm32 systemd[1]: azure-li-system-setup.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 00:00:41 sollabdsm32 systemd[1]: Failed to start System Setup of Azure Li/VLi machine.
Oct 24 00:00:41 sollabdsm32 systemd[1]: azure-li-system-setup.service: Unit entered failed state.
Oct 24 00:00:41 sollabdsm32 systemd[1]: azure-li-system-setup.service: Failed with result 'exit-code'.

Please find the logs below for one of the images:
https://imagestoreaccount.blob.core.windows.net/logs/workload_31.log?sp=r&st=2019-10-24T03:02:05Z&se=2019-10-24T11:02:05Z&spr=https&sv=2019-02-02&sr=b&sig=wqYTF9uVoHnyhMG5v6v5yp0hu6fybnNXIiH9BqQUwt4%3D

The device "/dev/disk/by-path*" is available on the host.
I think its the issue just after restart of iscsi services [somehow the device is not available just after the restart of the iscsi services]

> iscsiadm -m discovery -t st -p 10.20.213.41:3260
iscsiadm -m node -l
rescan-scsi-bus.sh
systemctl restart iscsi
systemctl restart iscsid
udevadm settle --timeout=30
/dev/disk/by-path/ip-10.20.213.31\:3260-iscsi-iqn.1992-08.com.netapp\:sn.98a704f9dfb811e9988d00a098d3b5f1\:vs.19-lun-0

the "/dev/disk/by-path/ip-10.20.213.31\:3260-iscsi-iqn.1992-08.com.netapp\:sn.98a704f9dfb811e9988d00a098d3b5f1\:vs.19-lun-0" device is already available on the host when i try the script, as against first boot when its being discovered the first time.

Even with "udevadm settle --timeout=30" i see the same behavior.
However a timeout of 1 second works fine.

Can you please let me know if you want any other inputs from me ?

Thanks !!
