### ISSUE TITLE
swap volume not configured on SLES15 images

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#181]
Hi Marcus,

It seems swap space not getting configured properly was resolved in issue https://github.com/SUSE-Enceladus/azure-li-services/issues/163 but SLES15 images don't have swap configured properly  still, can you please take a look

sollabdsm32:~ # free -m
              total        used        free      shared  buff/cache   available
Mem:        2063561        1089     2062185          19         285     2056719
Swap:             0           0           0
sollabdsm32:~ # cat /etc/os-release
NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15"

Thanks !!

**Comment by schaefi** [comment]
Hmm, that's strange, can you please repeat the deployment and add the boot option:

*  rd.kiwi.debug

at the grub level. Once the system has booted there is now a log file

* /run/initramfs/log/boot.kiwi

Can you attach this here. Thanks

**Comment by jaawasth** [comment]
Please find the link to log below :

https://imagestoreaccount.blob.core.windows.net/logs/boot.kiwi?sp=r&st=2019-10-07T08:06:43Z&se=2019-10-07T16:06:43Z&spr=https&sv=2018-03-28&sig=JtkTn4Js8q2fnA8KYxVKdM%2BXIFQa7PuopNvolrG82bc%3D&sr=b

**Comment by schaefi** [comment]
Thanks I found the reason. The patch we created to fix this issue here:

* https://github.com/OSInside/kiwi/pull/1129

is not yet part of SLES15-SP1. The patch has been ported to the kiwi_sle15 code stream and is available in version: 9.18.16 but seems to be not available in the SLES15 code stream

I'll check up with my team mates why the submission to SLE15 is not yet processed

**Comment by davidcassany** [comment]
The upadate is expected to released around 14th of Oct. So next week the updated package (v9.18.16) should be available in SLE-15-SP1 stream.

**Comment by schaefi** [comment]
Thanks, until then I have setup the testing image builds to use the version that will be released soon such that we can continue delivering images for testing that includes the fixes from the kiwi side.

**Comment by schaefi** [comment]
Images for sle15 are building now with the updated kiwi in the testing area
