### ISSUE TITLE
Switch to saptune for setting SAP tunables

### ISSUE THREAD

**Issue by schaefi** [SUSE-Enceladus/azure-li-services#185]
saptune is the successor of sapconf and also the preferred solution on the SLES4SAP product. Currently we use sapconf and are therefore on a deprecated coding path. This should be changed.
Following information by Angela Briel, thanks to Angela for helping

```
In your quoted list of installed packages you can only skip 'sapconf',
but need to stay with 'tuned' and 'saptune' as the current version of
saptune still needs tuned. This will change in the future, but for now
you need both packages.
```

The right startup sequence in case of saptune will be:

```python
def set_saptune_service():
     Command.run(
         ['saptune', 'daemon', 'start']
     )
     Command.run(
         ['saptune', 'solution', 'apply', 'HANA']
     )
```

After installing the image you can check (if needed or desired) on the
command line with the following commands:

```
saptune daemon status
saptune solution list
saptune note list
```

**Comment by scmschmidt** [comment]
> saptune is the successor of sapconf ...

This is not quite correct. Sapconf is a tool that just does the absolute necessary to run SAP workloads. Saptune is more advanced and therefore - as an additional value - part of SLES4SAP only.

**Comment by schaefi** [comment]
ok thanks for making that clear. From our point of view it does not change the actions we need to take; prefer saptune over sapconf for SLES4SAP based images. Please correct when wrong. Thanks

**Comment by scmschmidt** [comment]
No, it does not change your actions, but I wanted to prevent another misunderstanding. We had that in the past, when sapconf indeed logged a deprecation warning incorrectly.
