### ISSUE TITLE
VLI: Packages needed in SLES12 SP4 sap hana image

### ISSUE THREAD

**Issue by lalitb** [SUSE-Enceladus/azure-li-services#186]
Few of the packages are missing in sap hana sles12 sp4 image, while they are present in base sles image. These packages are required for installing some of HPE specific services. Please create a new image with these packages:

```
cpp48 = 4.8.5-31.17.1
patch
libxml2  ( libxml2-2 32 bit)
```

**Comment by schaefi** [comment]
* You request this only for sle12 sp4 or also for sle12 sp3, sle15, sle15-sp1 ?
* You need this for Large Instance, Very Large Instance or both ?

Thanks

**Comment by lalitb** [comment]
This is for VLI, and for sles versions starting sles12 sp4, sles15 sp1...

**Comment by lalitb** [comment]
Any update on this ?

**Comment by schaefi** [comment]
see #190, added you as reviewer too. Thanks
