### ISSUE TITLE
SBD device issue with SLES15 & SLES15 SP1 & the latest SLES12 SP4 images SLES15-SP1-SAP-Azure-LI-BYOS.x86_64-1.0.5-Devel-Build4.13.raw SLES15-SP1-SAP-Azure-VLI-BYOS.x86_64-1.0.5-Devel-Build4.13.raw && SLES12-SP4-SAP-Azure-LI-BYOS.x86_64-1.0.9-Devel-Build4.10.raw

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#188]
Hi Marcus / Jesus

I'm still seeing this behavior with the latest set of images provided :
SLES15-SP1-SAP-Azure-LI-BYOS.x86_64-1.0.5-Devel-Build4.13.raw
SLES15-SP1-SAP-Azure-VLI-BYOS.x86_64-1.0.5-Devel-Build4.13.raw

log snippet below

● azure-li-system-setup.service - System Setup of Azure Li/VLi machine
Loaded: loaded (/usr/lib/systemd/system/azure-li-system-setup.service; enabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Thu 2019-10-24 00:00:41 UTC; 949ms ago
Process: 5740 ExecStart=/usr/bin/azure-li-system-setup (code=exited, status=1/FAILURE)
Main PID: 5740 (code=exited, status=1/FAILURE)
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]: Traceback (most recent call last):
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]: File "/usr/bin/azure-li-system-setup", line 11, in
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]: load_entry_point('azure-li-services==1.2.1', 'console_scripts', 'azure-li-system-setup')()
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]: File "/usr/lib/python3.6/site-packages/azure_li_services/units/system_setup.py", line 86, in main
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]: raise AzureHostedException(system_setup_errors)
Oct 24 00:00:41 sollabdsm32 azure-li-system-setup[5740]: azure_li_services.exceptions.AzureHostedException: [AzureHostedCommandException('sbd: stderr: sbd failed; please check the logs.\n, stdout: Initializing device /dev/disk/by-path/ip-10.20.213.41:3260-iscsi-iqn.1992-08.com.netapp:sn.98a704f9dfb811e9988d00a098d3b5f1:vs.19-lun-0\n',)]
Oct 24 00:00:41 sollabdsm32 systemd[1]: azure-li-system-setup.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 00:00:41 sollabdsm32 systemd[1]: Failed to start System Setup of Azure Li/VLi machine.
Oct 24 00:00:41 sollabdsm32 systemd[1]: azure-li-system-setup.service: Unit entered failed state.
Oct 24 00:00:41 sollabdsm32 systemd[1]: azure-li-system-setup.service: Failed with result 'exit-code'.

Please find the logs below for one of the images:
https://imagestoreaccount.blob.core.windows.net/logs/workload_31.log?sp=r&st=2019-10-24T03:02:05Z&se=2019-10-24T11:02:05Z&spr=https&sv=2019-02-02&sr=b&sig=wqYTF9uVoHnyhMG5v6v5yp0hu6fybnNXIiH9BqQUwt4%3D

The device "/dev/disk/by-path*" is available on the host.
I think its the issue just after restart of iscsi services [somehow the device is not available just after the restart of the iscsi services]

iscsiadm -m discovery -t st -p 10.20.213.41:3260
iscsiadm -m node -l
rescan-scsi-bus.sh
systemctl restart iscsi
systemctl restart iscsid
udevadm settle --timeout=30
/dev/disk/by-path/ip-10.20.213.31:3260-iscsi-iqn.1992-08.com.netapp:sn.98a704f9dfb811e9988d00a098d3b5f1:vs.19-lun-0

the "/dev/disk/by-path/ip-10.20.213.31:3260-iscsi-iqn.1992-08.com.netapp:sn.98a704f9dfb811e9988d00a098d3b5f1:vs.19-lun-0" device is already available on the host when i try the script, as against first boot when its being discovered the first time.

Even with "udevadm settle --timeout=30" i see the same behavior.
However a timeout of 1 second works fine.

Can you please let me know if you want any other inputs from me ?

Thanks !!

**Comment by schaefi** [comment]
Ok, so it seems it's not the presence of the device but something else that is not yet ready ?
Could you provide the log file written by sbd ?

Thanks

**Comment by schaefi** [comment]
Sorry for being picky but I'd like to implement the suggested sleep fix only as last resort if we don't find anything else. Thanks

**Comment by jaawasth** [comment]
I'm unable to find SBD logs 

If you could tell me where to find them, I could provide you, I can't see it 
I'm providing ls output and the grep output [for "sbd"] of the /var/log directory below

**sollabdsm31:~ # ls -lrt /var/log/**

> total 9616
drwxr-xr-x 2 root      root           6 May 25  2018 cluster
drwx------ 2 root      root          40 Nov 13  2018 YaST2
drwxr-x--- 2 chrony    chrony         6 Mar 29  2019 chrony
drwxr-xr-x 2 lp        lp             6 Apr  6  2019 cups
drwxr-xr-x 2 root      root           6 Apr  8  2019 ctdb
drwxr-x--- 2 hacluster haclient       6 Jul 26 07:24 hawk
drwx------ 2 root      root           6 Aug  7 11:50 krb5
drwxr-x--- 2 root      root          21 Oct  3 14:40 zypp
-rw------- 1 root      root           0 Oct 22 17:37 pbl.log
drwxrwx--- 3 hacluster haclient      21 Oct 22 17:37 pacemaker
lrwxrwxrwx 1 root      root          10 Oct 22 17:38 dump -> /var/crash
drwx------ 2 root      root          23 Oct 23 22:42 audit
-rw------- 1 root      root     4194240 Oct 23 22:42 tallylog
drwxr-xr-x 2 root      root          23 Oct 23 22:42 tuned
-rw-r--r-- 1 root      root        3127 Oct 23 22:42 sapconf.log
-rw------- 1 root      root        8894 Oct 23 22:42 boot.log
-rw-r--r-- 1 root      root       25550 Oct 23 22:42 alternatives.log
-rw-r----- 1 root      root     5291138 Oct 23 22:42 zypper.log
-rw-r--r-- 1 root      root        2914 Oct 23 22:42 azure-li-services.log
-rw-rw-r-- 1 root      utmp      301636 Oct 23 22:46 lastlog
-rw-rw-r-- 1 root      utmp        3072 Oct 23 23:45 wtmp
drwxr-xr-x 2 root      root          61 Oct 24 05:55 sa
-rw------- 1 root      utmp        4992 Oct 24 06:35 btmp

**sollabdsm31:~ # grep -ir sbd /var/log/**

> /var/log/zypp/history:# 2019-10-22 17:37:55 sbd.rpm installed ok
/var/log/zypp/history:# warning: /var/cache/kiwi/packages/031959444a6e8e6404f763d8b4f4e430/sbd.rpm: Header V3 RSA/SHA256 Signature, key ID 39db7c82: NOKEY
/var/log/zypp/history:# Updating /etc/sysconfig/sbd ...
/var/log/zypp/history:2019-10-22 17:37:55|install|sbd|1.4.0+20190514.e9be8d9-3.6.1|x86_64||031959444a6e8e6404f763d8b4f4e430|af3ef927f4f986eddda4d2a64439bcb06a0ebc311e48bb9cb239f3ab656a4a1e|
/var/log/zypper.log:2019-10-22 17:35:54 <1> tornado2(2449) [zypper++] Summary.cc(readPool):144 <install>   U_Ts_r(922)sbd-1.4.0+20190514.e9be8d9-3.6.1.x86_64(031959444a6e8e6404f763d8b4f4e430)
/var/log/zypper.log:2019-10-22 17:36:01 <1> tornado2(2449) [zypp] PackageProvider.cc(providePackage):412 provide Package (922)sbd-1.4.0+20190514.e9be8d9-3.6.1.x86_64(031959444a6e8e6404f763d8b4f4e430)
/var/log/zypper.log:2019-10-22 17:36:01 <1> tornado2(2449) [zypp] RepoProvideFile.cc(provideFile):254 [1]./sbd.rpm{77.2 KiB|sha256-af3ef927f4f986eddda4d2a64439bcb06a0ebc311e48bb9cb239f3ab656a4a1e}
/var/log/zypper.log:2019-10-22 17:36:01 <1> tornado2(2449) [zypp++] MediaSetAccess.cc(provide):253 Going to try to provide  file ./sbd.rpm from media number 1
/var/log/zypper.log:2019-10-22 17:36:01 <1> tornado2(2449) [zypp++] MediaHandler.cc(provideFile):1015 provideFile(./sbd.rpm)
/var/log/zypper.log:2019-10-22 17:36:01 <1> tornado2(2449) [zypp:fetcher] Fetcher.cc(validate):366 Checking job [/repos/SUSE:/SLE-15:/Update/standard/sbd.rpm] (2 checkers )
/var/log/zypper.log:2019-10-22 17:36:01 <1> tornado2(2449) [zypp] PathInfo.cc(hardlinkCopy):863 hardlinkCopy /repos/SUSE:/SLE-15:/Update/standard/sbd.rpm -> /var/cache/kiwi/packages/031959444a6e8e6404f763d8b4f4e430/sbd.rpm => copy
/var/log/zypper.log:2019-10-22 17:36:01 <1> tornado2(2449) [zypp::exec++] ExternalProgram.cc(start_program):259 Executing '/bin/cp' '--remove-destination' '--' '/repos/SUSE:/SLE-15:/Update/standard/sbd.rpm' '/var/cache/kiwi/packages/031959444a6e8e6404f763d8b4f4e430/sbd.rpm'
/var/log/zypper.log:2019-10-22 17:36:01 <1> tornado2(2449) [zypp] PathInfo.cc(copy):800 copy /repos/SUSE:/SLE-15:/Update/standard/sbd.rpm -> /var/cache/kiwi/packages/031959444a6e8e6404f763d8b4f4e430/sbd.rpm
/var/log/zypper.log:2019-10-22 17:36:01 <1> tornado2(2449) [zypp++] MediaSetAccess.cc(releaseFile):88 Going to release file ./sbd.rpm from media number 1
/var/log/zypper.log:2019-10-22 17:36:01 <1> tornado2(2449) [zypp] RepoProvideFile.cc(provideFile):320 provideFile at /var/cache/kiwi/packages/031959444a6e8e6404f763d8b4f4e430/sbd.rpm
/var/log/zypper.log:2019-10-22 17:36:01 <1> tornado2(2449) [zypp] PackageProvider.cc(providePackage):513 provided Package (922)sbd-1.4.0+20190514.e9be8d9-3.6.1.x86_64(031959444a6e8e6404f763d8b4f4e430) at /var/cache/kiwi/packages/031959444a6e8e6404f763d8b4f4e430/sbd.rpm
/var/log/zypper.log:2019-10-22 17:37:55 <1> tornado2(2449) [zypp] RpmHeader.cc(readPackage):252 ReferenceCounted(@0x55ea38e1d980<=1){0x55ea38e1c460}{sbd-1.4.0+20190514.e9be8d9-3.6.1} from /var/cache/kiwi/packages/031959444a6e8e6404f763d8b4f4e430/sbd.rpm
/var/log/zypper.log:2019-10-22 17:37:55 <1> tornado2(2449) [librpmDb] RpmDb.cc(doInstallPackage):2009 RpmDb::installPackage(/var/cache/kiwi/packages/031959444a6e8e6404f763d8b4f4e430/sbd.rpm,0x0000000c)
/var/log/zypper.log:2019-10-22 17:37:55 <1> tornado2(2449) [zypp::exec++] ExternalProgram.cc(start_program):259 Executing 'rpm' '--root' '/' '--dbpath' '/var/lib/rpm' '-U' '--percent' '--noglob' '--force' '--nodeps' '--' '/var/cache/kiwi/packages/031959444a6e8e6404f763d8b4f4e430/sbd.rpm'
/var/log/zypper.log:2019-10-22 17:37:55 <1> tornado2(2449) [Progress++] ProgressData.cc(report):88 {#1539|Installing: sbd-1.4.0+20190514.e9be8d9-3.6.1.x86_64}END
/var/log/zypper.log:2019-10-22 17:37:55 <1> tornado2(2449) [zypp] PathInfo.cc(unlink):659 unlink /var/cache/kiwi/packages/031959444a6e8e6404f763d8b4f4e430/sbd.rpm
/var/log/azure-li-services.log:Calling: ['sbd', '-d', '/dev/disk/by-path/ip-10.20.213.31:3260-iscsi-iqn.1992-08.com.netapp:sn.98a704f9dfb811e9988d00a098d3b5f1:vs.19-lun-0', 'create']
sollabdsm31:~ #

**Comment by schaefi** [comment]
Hmm, this is interesting. From your initial report you can see that sbd said something like

```
sbd: stderr: sbd failed; please check the logs.
```

It does not say where to look for but I remember last time they are located in /var/log/sbd/...
maybe sbd on sle12 behaves differently than on sle15. You can take a look at /etc/sysconfig/sbd 
if you see anything regarding the log setup ?

This is unfortunate because without log information I'm running out of ideas what we could do to come up with a race free fix

**Comment by jaawasth** [comment]
I have updated the title, even the latest SLES12 SP4 [SLES12-SP4-SAP-Azure-VLI-BYOS.x86_64-0.0.21-Devel-Build4.11.raw] is failing with this issue

**Comment by jaawasth** [comment]
Sorry, the image version for LI is SLES12-SP4-SAP-Azure-LI-BYOS.x86_64-1.0.9-Devel-Build4.10.raw.xz, updated the title to reflect the same

**Comment by schaefi** [comment]
> I think for some time its unavailable

ok I see that explains it. The udev call just waits for the device to be present but it seems the presence of the device is not a valid sign that we can also read the iSCSI target. The problem now is what means "some time" 1sec, 5sec, 30sec. This is the problem with unconditional wait times.

@rjschwei Do you have a contact person in SUSE I can ask regarding iSCSI and SBD ?

**Comment by schaefi** [comment]
worst I can imagine is a try and error loop until success or X numbers of retries

**Comment by jaawasth** [comment]
Hey Marcus,  Were we able to decide upon fix path ?
