### ISSUE TITLE
VLI: enable softdog

### ISSUE THREAD

**Issue by lalitb** [SUSE-Enceladus/azure-li-services#192]
Checked for SLES15 SP1 and SLES12 SP4. This needs to be enabled for VLI by default as there is no hardware watchdog in HPE 990 series.
```
azsollabdsm36:~ # lsmod | grep dog
azsollabdsm36:~ #
azsollabdsm36:~ # cat /etc/os-release
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"
azsollabdsm36:~ #
```

**Comment by schaefi** [comment]
Please confirm if the following procedure is what you request

```
echo softdog > /etc/modules-load.d/watchdog.conf
systemctl restart systemd-modules-load
```

Thanks

**Comment by lalitb** [comment]
Yes, but seems its enabled by default in the latest SLES 12 SP4 image - SLES12-SP4-SAP-Azure-VLI-BYOS.x86_64-0.0.21-Devel-Build7.41.raw

**Comment by schaefi** [comment]
We have no explicit enabling in our image descriptions as you can see in images/vli here, but if you are saying it is enabled by default I'm good with that. How about the SLE15 image ?

**Comment by schaefi** [comment]
@lalitb any news ?

**Comment by lalitb** [comment]
Sorry for late here ? I will be checking it again in latest images, and get back to you.

**Comment by jaiawasthi** [comment]
@schaefi , i see we are enabling softdog for our images in get_stonith_needed_modules,
But i was testing some latest development images & see its enabled, please check if we are doing it for all latest images.
I'll check as well for all new images and see if there is any issue and report back.

Thanks !!

**Comment by schaefi** [comment]
ok

**Comment by schaefi** [comment]
I guess it's not an issue anymore after the long time this ticket was open. If this is still an issue please create a new issue with details which appliances are missing softdog. Thanks
