### ISSUE TITLE
SLES12 SP4: sbd device not created

### ISSUE THREAD

**Issue by lalitb** [SUSE-Enceladus/azure-li-services#194]
Below errors logged during boot time:

Dec 09 04:23:06 azsollabdsm36 azure-li-system-setup[9903]: azure_li_services.exceptions.AzureHostedException: [AzureHostedCommandException('sbd: stderr: sbd failed; please check the logs.\n, stdout: Initializing device /dev/disk/by-path/ip-10.20.213.31:3260-iscsi-iqn.1992-08.com.netapp:sn.98a704f9dfb811e9988d00a098d3b5f1:vs.19-lun-0\n',)]

Please provide a fix for this.

**Comment by lalitb** [comment]
Tested on SLES12-SP4-SAP-Azure-VLI-BYOS.x86_64-0.0.21-Build1.1.raw

**Comment by schaefi** [comment]
Well the build looks old to me, probably not containing the fix #188

Via mail I asked Jesus to send you the latest testing image. Please re-open if you still see the issue. Thanks
