### ISSUE TITLE
SLES 12 SP4: loginshell not recognized in yaml configuration.

### ISSUE THREAD

**Issue by lalitb** [SUSE-Enceladus/azure-li-services#195]
loginshell is not recognized in yaml configuration, and by default the bash shell is associated with new accounts created.

**Comment by lalitb** [comment]
Tested on SLES12-SP4-SAP-Azure-VLI-BYOS.x86_64-0.0.21-Build1.1.raw

**Comment by schaefi** [comment]
Pretty much the same issue, I consider this image to be old and outdated not having the fix for #178 

Via mail Jesus will sent the latest testing image, Please re-open if you still see the issue with that one

Thanks
