### ISSUE TITLE
Include server side monitoring tools modules in LI images

### ISSUE THREAD

**Issue by jaiawasthi** [SUSE-Enceladus/azure-li-services#198]
Hi Team,

For our monitoring efforts, we’re looking to leverage standard Prometheus modules shipped by SuSE (such as the Node exporter or Pacemaker/HA cluster exporter). This will help to light up additional scenarios, such as OS-level monitoring.
Can you please add below steps into the LI images

Installation steps

**Set OS version (change as desired) and then add repository**
export DISTRO=SLE_12_SP3 
zypper addrepo https://download.opensuse.org/repositories/server:/monitoring/$DISTRO/server:monitoring.repo

**Install Prometheus with Node and HA Cluster exporters**
zypper install golang-github-prometheus-node_exporter prometheus-ha_cluster_exporter

**Set arguments for Node exporter**
sed -i '/ARGS/d' /etc/sysconfig/prometheus-node_exporter
echo 'ARGS="--collector.systemd"' >> /etc/sysconfig/prometheus-node_exporter

**Start the Node exporter**
systemctl start prometheus-node_exporter

**Start the HA Cluster exporter (HA Clusters only)**
systemctl start prometheus-ha_cluster_exporter

Please let me know incase of any queries

**Comment by rjschwei** [comment]
We cannot ship packages from opensuse.org in our supported SLES images, nor can we automate a process that would automatically add unsupported packages to the instance. The user has to make an explicit choice to add unsupported software to their system.

I will create a feature request for these packages to allow Product Management to evaluate whether or not SUSE wants to ship and support these modules.

**Comment by jaiawasthi** [comment]
Thanks Robert, if you are creating a feature request, how long do you think it will take for these modules to get required SUSE support to ship with our official image ?

**Comment by rjschwei** [comment]
Sorry there is no ETA as there a number of options.
1.) Ship unsupported packages
  - While there is principal agreement that we should be able to do this on a technical level this is not so easy. Once a package is in the image customer will expect updates, it is uncertain where these updates would come from and how this would be handled.
2.) Support the requested packages
  - From an image perspective that makes it easy, but obviously has broader organizational and resources implications
3.) Follow the path you suggested and pull the packages from OBS (openSUSE Build Service)
  - This would require the running system to have Internet access, but many customers running SAP work loads do not want such access. Therefore this would lead to some systems having teh packages and other that do not.

We will continue to discuss the situation internally at SUSE to try and understand the various implications and then come back with a solution.

**Comment by jaiawasthi** [comment]
Thanks Robert.
Regarding  1 )
This is not what has been asked by customers, but it's us [Microsoft] that requires availability of these packages for monitoring customer OS, I'm not sure [let me check] if we can come to an understanding of how frequently we would want updates to this.
But given that, if we dont require frequent updates, how feasible is this request ?

2) 
Sure, i understand that.

3) 
Yes, this is not an option

**Comment by rjschwei** [comment]
> Thanks Robert.
> Regarding 1 )
> This is not what has been asked by customers, but it's us [Microsoft] that requires availability of these packages for monitoring customer OS, I'm not sure [let me check] if we can come to an understanding of how frequently we would want updates to this.
> But given that, if we dont require frequent updates, how feasible is this request ?

Well the frequency of updates is immaterial, it only takes 1 unpatched vulnerability that creates a problem.
