### ISSUE TITLE
KDump enabled in latest GA SLES12-SP4 image ?

### ISSUE THREAD

**Issue by prtyag** [SUSE-Enceladus/azure-li-services#201]
Is the KDump enabled in latest GA SLES12-SP4 image? here is the output of the following command
`systemctl status kdump.service`

> ● kdump.service - Load kdump kernel and initrd
   Loaded: loaded (/usr/lib/systemd/system/kdump.service; enabled; vendor preset: disabled)
   Active: active (exited) since Thu 2020-03-05 11:49:06 UTC; 3 days ago
 Main PID: 4845 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 512)
   CGroup: /system.slice/kdump.service

> Mar 05 11:48:37 sollabdsm31 systemd[1]: Starting Load kdump kernel and initrd...

> Mar 05 11:49:06 sollabdsm31 systemd[1]: Started Load kdump kernel and initrd.

` cat /proc/cmdline`

> BOOT_IMAGE=(hd0,msdos1)/boot/vmlinuz-4.12.14-95.32-default splash=verbose net.ifnames=1 mce=ignore_ce nomodeset numa_balancing=disable transparent_hugepage=never intel_idle.max_cstate=1 processor.max_cstate=1 crashkernel=160M,high crashkernel=80M,low root=UUID=8a9c9662-9aa0-420a-a9b7-f20e800467fb rw

From the above results, can you confirm that KDump is enabled?

**Comment by schaefi** [comment]
> From the above results, can you confirm that KDump is enabled?

kdump is enabled. I guess the question is more why there is no core information on crash.

I have tested a simulated crash and it all worked fine. From your e-mail I wasn't sure if your sysrq based crash scenario was complete. So here is what I did.

```
echo 1 > /proc/sys/kernel/sysrq 
echo c > /proc/sysrq-trigger
```

The kernel oops is showed on the console and the dump kernel gets loaded through kexec.
After reboot I have crash dump info below:

```
/var/crash/2020-03-16-09:04/...
```

If you don't see this I guess the configured memory area is too small

* In this azure li services we run a tool on firstboot that updates the pre-configured memory area if the main memory of the machine is > 1TB. We also update the grub setup with the new values and reboot the machine through kexec to make this values effective. From your report it looks to me that the values were not modified and taken as we configured them in the image description. However they can still be inaccurate, so better check.
Could you please provide the output of:

```
kdumptool calibrate
```

So for me in my VM things are working, but that could be different on bare metal and big machines.

**Comment by prtyag** [comment]
Here is the output:
```
azsollabdsm175:~ # kdumptool calibrate
Total: 6289915
Low: 72
High: 218
MinLow: 72
MaxLow: 1371
MinHigh: 0
MaxHigh: 6288384

```

**Comment by prtyag** [comment]
I also tried the below commands but not able to see any crash log in the specified folder. i.e /var/crash folder is empty for me. 
> ```
> echo 1 > /proc/sys/kernel/sysrq 
> echo c > /proc/sysrq-trigger
```

**Comment by schaefi** [comment]
I guess the memory area is too small. Try this

* edit the file ```/boot/grub2/grub.cfg```
* change

```
crashkernel=160M,high
```

to

```
crashkernel=250M,high
```

reboot the machine and try again. Any difference ?

**Comment by schaefi** [comment]
I also need the amount of main memory of the machine

```
cat /proc/meminfo
```

**Comment by prtyag** [comment]
`azsollabdsm175:~ # cat /proc/meminfo
MemTotal:       6339842568 kB
MemFree:        6337517252 kB
MemAvailable:   6323550828 kB
Buffers:           15756 kB
Cached:           339324 kB
SwapCached:            0 kB
Active:           327452 kB
Inactive:         196692 kB
Active(anon):     233520 kB
Inactive(anon):    77924 kB
Active(file):      93932 kB
Inactive(file):   118768 kB
Unevictable:      111484 kB
Mlocked:          111484 kB
SwapTotal:       2079792 kB
SwapFree:        2079792 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:        280848 kB
Mapped:           174344 kB
Shmem:            121380 kB
Slab:             296496 kB
SReclaimable:      92792 kB
SUnreclaim:       203704 kB
KernelStack:       35728 kB
PageTables:         7492 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    3172001076 kB
Committed_AS:    2027276 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      440208 kB
DirectMap2M:    14759936 kB
DirectMap1G:    6427770880 kB
`

**Comment by schaefi** [comment]
5g of RAM if I calculated correctly, ok. Let me know if the highmem change made a difference

**Comment by schaefi** [comment]
ah wrong

**Comment by schaefi** [comment]
6TB of RAM that should have triggered the update of the crashkernel values. Can you provide the log file: /var/log/azure-li-services.log

**Comment by schaefi** [comment]
Can you also provide the file ```/etc/default/grub```

**Comment by schaefi** [comment]
last but not least I also need your system configuration. The yaml config file you used to deploy this machine

**Comment by prtyag** [comment]
> 6TB of RAM that should have triggered the update of the crashkernel values. Can you provide the log file: /var/log/azure-li-services.log
Hi there is no file with this name. here are the files in this directory:
`azsollabdsm175:~ # ls /var/log
NetworkManager    audit     ctdb     faillog                   lastlog        mail.info             messages-20200311.xz  pacemaker.log-20200308.xz  sapconf.log  wtmp
YaST2             boot.log  cups     firewall                  localmessages  mail.warn             news                  pacemaker.log-20200315.xz  tallylog     zypp
acpid             btmp      dirmngr  ha-cluster-bootstrap.log  mail           messages              ntp                   pbl.log                    tuned        zypper.log
alternatives.log  cluster   dump     krb5                      mail.err       messages-20200305.xz  pacemaker.log         sa                         warn
`

**Comment by schaefi** [comment]
And I need a little test. Can you run the following python code on your machine:

```python
from psutil import virtual_memory

machine_memory = virtual_memory()
machine_memory_tbytes = int(machine_memory.total / 1024**4)

print(machine_memory_tbytes)
```

Thanks

**Comment by prtyag** [comment]
> Can you also provide the file `/etc/default/grub`

[etc_default_grub.txt](https://github.com/SUSE-Enceladus/azure-li-services/files/4337500/etc_default_grub.txt)

**Comment by schaefi** [comment]
Sorry the log file is written onto the LUN that also provides the yaml config file and is named

* workload.log

Can you provide it together with the yaml config

Thanks

**Comment by schaefi** [comment]
> > Can you also provide the file `/etc/default/grub`
> 
> [etc_default_grub.txt](https://github.com/SUSE-Enceladus/azure-li-services/files/4337500/etc_default_grub.txt)

ok that looks fine

**Comment by prtyag** [comment]
Yaml contain this file which has this value: 
crash_dump:
  activate: false

**Comment by schaefi** [comment]
with 6TB of RAM the memory area is for sure too small

**Comment by schaefi** [comment]
> Yaml contain this file which has this value:
> crash_dump:
> activate: false

And that's the reason for it :)

activate: true

**Comment by schaefi** [comment]
With this setting enabled we manage the memory area according to the output of kdumptool. If not activated you are on your own with the settings. The default in the image description is relatively small on purpose because it eats away parts of your memory

**Comment by prtyag** [comment]
Is there any method we can enable this manually for the already deployed systems?

**Comment by schaefi** [comment]
no, this services runs once at deployment time

**Comment by schaefi** [comment]
but of course you can update your crash setup on the running machines

**Comment by schaefi** [comment]
Here is what we do on systems with >1TB of RAM

**Comment by schaefi** [comment]
* call kdumptool calibrate

* Take the low value as reported
* Take the high value multiplied by the TB's of RAM, in your case *6

update the grub setup and reboot

**Comment by schaefi** [comment]
test the crash

**Comment by prtyag** [comment]
sure @schaefi i'll try this for the existing setup and change the crash_dump to be true in yaml to test if it is automatically enabling the kdump as expected.

**Comment by prtyag** [comment]
Hi @schaefi,
Instructions for the already deployed system is working as expected however i changed the crash_dump's activate to be true from false in suse_first_boot_config.yaml and reimaged the server with the updated config yaml but as i can see the /proc/cmdline file still has memory parameter which is default. Here are some of the outputs:
`
```
azsollabdsm175:~ # kdumptool calibrate
Total: 6289915
Low: 72
High: 218
MinLow: 72
MaxLow: 1371
MinHigh: 0
MaxHigh: 6288384
```
```
azsollabdsm175:~ # cat /proc/cmdline
splash=verbose net.ifnames=1 mce=ignore_ce nomodeset numa_balancing=disable transparent_hugepage=never intel_idle.max_cstate=1 processor.max_cstate=1 crashkernel=160M,high crashkernel=80M,low root=UUID=8a9c9662-9aa0-420a-a9b7-f20e800467fb rw
```
```
azsollabdsm175:~ # cat /etc/default/grub
# If you change this file, run 'grub2-mkconfig -o /boot/grub2/grub.cfg' afterwards to update
# /boot/grub2/grub.cfg.

# Uncomment to set your own custom distributor. If you leave it unset or empty, the default
# policy is to determine the value from /etc/os-release
# GRUB_DISTRIBUTOR=""

GRUB_DEFAULT=0
GRUB_HIDDEN_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_TIMEOUT=10
GRUB_CMDLINE_LINUX_DEFAULT="splash=verbose net.ifnames=1 mce=ignore_ce nomodeset numa_balancing=disable transparent_hugepage=never intel_idle.max_cstate=1 processor.max_cstate=1 crashkernel=1095M,high crashkernel=72M,low root=UUID=8a9c9662-9aa0-420a-a9b7-f20e800467fb rw "
GRUB_CMDLINE_LINUX=""

# Uncomment to automatically save last booted menu entry in GRUB2 environment
# variable `saved_entry'
#GRUB_SAVEDEFAULT="true"

# Uncomment to enable BadRAM filtering, modify to suit your needs
# This works with Linux (no patch required) and with any kernel that obtains
# the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
#GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

# Uncomment to disable graphical terminal (grub-pc only)
#GRUB_TERMINAL=console

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
#GRUB_GFXMODE=640x480

# Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
#GRUB_DISABLE_RECOVERY="true"

# Uncomment to get a beep at grub start
#GRUB_INIT_TUNE="480 440 1"

```
Truncating the config yaml content because of the obvious reasons
```
azsollabdsm175:~ # cat /etc/suse_firstboot_config.yaml
version: "20180614"
instance_type: LargeInstance
sku: "S224"
hostname: "azsollabdsm175"

crash_dump:
  activate: true

machine_constraints:
  min_cores: 72
  min_memory: "700GB"
```

```
azsollabdsm175:/mnt # cat azure-li-services.log
Calling: ['mkdir', '-p', '/var/lib/azure_li_services']
Calling: ['mountpoint', '/mnt']
Calling: ['mount', '-o', 'sync', '--label', 'azconfig', '/mnt']
Calling: ['mkdir', '-p', '/etc']
Calling: ['cp', '/mnt/suse_firstboot_config.yaml', '/etc/suse_firstboot_config.yaml']
Calling: ['umount', '--lazy', '/mnt']
Calling: ['grep', '-q', '^h35adm:', '/etc/passwd']
Calling: ['grep', '-q', '^sapsys:', '/etc/group']
Calling: ['groupadd', '-g', '1010', 'sapsys']
Calling: ['useradd', '-g', 'sapsys', '-p', '$6$e8JMOsEv4P3rDUJy$NMf11b7JF1e4Lp.J/
```

**Comment by schaefi** [comment]
The set_kdump_service() method is not called. If you look at:

https://github.com/SUSE-Enceladus/azure-li-services/blob/master/azure_li_services/units/system_setup.py#L130

you can see that we should at least see the calibrate call in the log file if the crash dump is activated. Thus I think something is wrong. Are you sure your config change became effective ?

**Comment by prtyag** [comment]
> The set_kdump_service() method is not called. If you look at:
> 
> https://github.com/SUSE-Enceladus/azure-li-services/blob/master/azure_li_services/units/system_setup.py#L130
> 
> you can see that we should at least see the calibrate call in the log file if the crash dump is activated. Thus I think something is wrong. Are you sure your config change became effective ?

yes i copied the suse_firstboot_config.yaml above. This is the same yaml that i have used to reimage the system.

**Comment by schaefi** [comment]
I need to see the image you used to tell more about this.

**Comment by prtyag** [comment]
sure, do you need any information from my side ?

**Comment by schaefi** [comment]
yes, which image did you use ? (this is the .raw file that gets dumped on your machine). If you can tell me the name it will help. If you can provide it to me I can look into the exact same binary you used. If not I look into the production bucket from where we submitted the images to Microsoft and fetch it by the name you will give me. If I can put my fingers directly on the binary you used it will avoid any side effects though.

**Comment by prtyag** [comment]
Hi marcus,
i can provide you the .raw image over the email. you can download using the SAS url. will that work for you ?

**Comment by schaefi** [comment]
>    i can provide you the .raw image over the email. you can download using
>    the SAS url. will that work for you ?

yep that will be fine, thanks

**Comment by prtyag** [comment]
I have a image name i think this will be sufficient for you 
![image](https://user-images.githubusercontent.com/51941156/76773716-f208bb00-67c8-11ea-9d46-def592111c10.png)

**Comment by schaefi** [comment]
ok with that info I can fetch it

**Comment by prtyag** [comment]
Hi @schaefi 
I tried manually enabling it for VLI as well using the steps you mentioned but after reboot the values are not reflected in /proc/cmdline still has the old default value.

**Comment by schaefi** [comment]
I'm going to test right now

**Comment by schaefi** [comment]
I have done my tests in a VM with ```SLES12-SP4-SAP-Azure-LI-BYOS.x86_64-1.0.6-Build1.110.raw```

My yaml config adds:

```yaml
crash_dump:
  activate: true
```
my image given default values where:

```
crashkernel=160M,high crashkernel=80M,low
```

kdumptool calibrate reported:

```
Total: 4095
Low: 72
High: 163
MinLow: 72
MaxLow: 3070
MinHigh: 0
MaxHigh: 3070
```

After the first boot I checked the grub setup ```/boot/grub2/grub.cfg``` and found

```
crashkernel=163M,high crashkernel=72M,low
```

So the values were applied. Next I checked for proc/cmdline and found

```
crashkernel=160M,high crashkernel=80M,low
```

So the values were not effective. The reason why they were not effective is because the overall deployment had errors. Those were intentional because I tested the network setup with names that does not exist in the VM. So this means on the LUN with the config I also see the file:

```
workload_success_is_false
```

In this case we intentionally do not reboot. That causes the new kdump values to be not applied. But that's intentional. Therefore you should check if your deployment was overall successful. You should also check the status reports from the services. Those are stored in:

```
/var/lib/azure_li_services/...
```

Overall the behavior is expected and working. I couldn't find a mistake

**Comment by prtyag** [comment]
Hi @schaefi,
I have added a script to enable kdump on LI system using the instruction you described. can you please review [this](https://github.com/Azure/sap-hana/pull/336) PR ?

Beside this the instruction that you gave to me are not working for VLI system. please provide me with the fresh step of instructions to enable KDUMP on VLI systems.

**Comment by prtyag** [comment]
Hi @schaefi ,
for 2 TB LI server kdump is not working.

**Comment by prtyag** [comment]
Hi @schaefi,
we have a several case in the past in VLI that the kernel crash and since the KDUMP is not enabled in that system we don't have anything for RCA. Since some of our customers are using VLI we wanted kdump to be working  asap. can we work on VLI kdump on a priority basis ?

**Comment by schaefi** [comment]
any change we might been doing after our debugging session will be handed in #203
