### ISSUE TITLE
SLES 15 SP1 image is not based on SAP Hana image 

### ISSUE THREAD

**Issue by vireddyc** [SUSE-Enceladus/azure-li-services#207]
SLES 15 SP1 is not SAP Hana based image it is SLES 15 SP1 Enterprise OS, Is there any reason why it is not SLES 15 SP1 for SAP Hana?

azsollabdsm36:~ # cat /etc/os-release
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"

**Comment by rjschwei** [comment]
SLES For SAP is not differentiated from SLES by entries in /etc/os-release but by the baseproduct link

```
~> cat /etc/os-release
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"

~> ls -l /etc/products.d/baseproduct 
lrwxrwxrwx 1 root root 13 Feb 27 18:18 /etc/products.d/baseproduct -> SLES_SAP.prod
```
