### ISSUE TITLE
Numad and libyui-qt-pkg7 are not included SLES12 SP4 GA image for Azure

### ISSUE THREAD

**Issue by YunziZhangAzure** [SUSE-Enceladus/azure-li-services#208]
Hi there,

Our team found there are two packages Numad and libyui-qt-pkg7 not included in SLES12 SP4 GA image which cause some problems when we try to install a software depending on these two packages on Azure instance. We want to know if there is a plan that Numad and libyui-qt-pkg7 will be included into the image in a future version, or maybe you have other advice, please let me know. 

Thank you!

**Comment by jeffaco** [comment]
@YunziZhangAzure Just to be clear, are you talking bare metal images, or are you talking Azure images for VMs? If VMs, this is the wrong forum for that ...

**Comment by YunziZhangAzure** [comment]
This is for bare metal image. sorry for the confusion.
