### ISSUE TITLE
how to get libhwloc.so.5()(64bit) rpm

### ISSUE THREAD

**Issue by vireddyc** [SUSE-Enceladus/azure-li-services#209]
Hi Marcus/Grant,

I am trying to install vendor dependent package, but I am unale to install it due to unable to find dependency package, below is the package name and details, I am also raising github issue,

It would be great, if you prioritize this issue

Package name: libhwloc.so.5()(64bit)

Installation logs:

sdflex01:~ # zypper in /opt/hfs/hfs/sgi/x86_64/numatools-2.0-732r191018T1130.sles15sp1hpe.x86_64.rpm
Refreshing service 'Basesystem_Module_15_SP1_x86_64'.
Refreshing service 'Containers_Module_15_SP1_x86_64'.
Refreshing service 'Desktop_Applications_Module_15_SP1_x86_64'.
Refreshing service 'Development_Tools_Module_15_SP1_x86_64'.
Refreshing service 'Legacy_Module_15_SP1_x86_64'.
Refreshing service 'Public_Cloud_Module_15_SP1_x86_64'.
Refreshing service 'Python_2_Module_15_SP1_x86_64'.
Refreshing service 'SAP_Applications_Module_15_SP1_x86_64'.
Refreshing service 'SUSE_Cloud_Application_Platform_Tools_Module_15_SP1_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_High_Availability_Extension_15_SP1_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Server_for_SAP_Applications_15_SP1_x86_64'.
Refreshing service 'SUSE_Package_Hub_15_SP1_x86_64'.
Refreshing service 'Server_Applications_Module_15_SP1_x86_64'.
Refreshing service 'Web_and_Scripting_Module_15_SP1_x86_64'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libhwloc.so.5()(64bit) needed by numatools-2.0-732r191018T1130.sles15sp1hpe.x86_64
 Solution 1: do not install numatools-2.0-732r191018T1130.sles15sp1hpe.x86_64
 Solution 2: break numatools-2.0-732r191018T1130.sles15sp1hpe.x86_64 by ignoring some of its dependencies

Suse registration details:

sdflex01:~ # zypper in /opt/hfs/hfs/sgi/x86_64/numatools-2.0-732r191018T1130.sles15sp1hpe.x86_64.rpm   SUSEConnect --status-text
Installed Products:
------------------------------------------

  SUSE Linux Enterprise Server for SAP Applications 15 SP1
  (SLES_SAP/15.1/x86_64)

  Registered

    Subscription:

    Regcode: E99B8D8D1656F8
    Starts at: 2019-12-10 00:00:00 UTC
    Expires at: 2020-12-10 00:00:00 UTC
    Status: ACTIVE
    Type: partner

------------------------------------------

  SUSE Linux Enterprise High Availability Extension 15 SP1
  (sle-ha/15.1/x86_64)

  Registered

    Subscription:

    Regcode: E99B8D8D1656F8
    Starts at: 2019-12-10 00:00:00 UTC
    Expires at: 2020-12-10 00:00:00 UTC
    Status: ACTIVE
    Type: partner

------------------------------------------

  Basesystem Module
  (sle-module-basesystem/15.1/x86_64)

  Registered

------------------------------------------

  SUSE Cloud Application Platform Tools Module
  (sle-module-cap-tools/15.1/x86_64)

  Registered

------------------------------------------

  Containers Module
  (sle-module-containers/15.1/x86_64)

  Registered

------------------------------------------

  Desktop Applications Module
  (sle-module-desktop-applications/15.1/x86_64)

  Registered

------------------------------------------

  Development Tools Module
  (sle-module-development-tools/15.1/x86_64)

  Registered

------------------------------------------

  Legacy Module
  (sle-module-legacy/15.1/x86_64)

  Registered

------------------------------------------

  Public Cloud Module
  (sle-module-public-cloud/15.1/x86_64)

  Registered

------------------------------------------

  SAP Applications Module
  (sle-module-sap-applications/15.1/x86_64)

  Registered

------------------------------------------

  Server Applications Module
  (sle-module-server-applications/15.1/x86_64)

  Registered

------------------------------------------

  Web and Scripting Module
  (sle-module-web-scripting/15.1/x86_64)

  Registered

------------------------------------------

  HPE Foundation Software 2.2
  (hpe-foundation/2.2/x86_64)

  Not Registered

------------------------------------------

  Python 2 Module
  (sle-module-python2/15.1/x86_64)

  Registered

------------------------------------------

sdflex01:~ # SUSEConnect --list-extensions
AVAILABLE EXTENSIONS AND MODULES

    Basesystem Module 15 SP1 x86_64 (Activated)
    Deactivate with: SUSEConnect -d -p sle-module-basesystem/15.1/x86_64

        Containers Module 15 SP1 x86_64 (Activated)
        Deactivate with: SUSEConnect -d -p sle-module-containers/15.1/x86_64

        Desktop Applications Module 15 SP1 x86_64 (Activated)
        Deactivate with: SUSEConnect -d -p sle-module-desktop-applications/15.1/x86_64

            Development Tools Module 15 SP1 x86_64 (Activated)
            Deactivate with: SUSEConnect -d -p sle-module-development-tools/15.1/x86_64

            SUSE Linux Enterprise Workstation Extension 15 SP1 x86_64
            Activate with: SUSEConnect -p sle-we/15.1/x86_64 -r ADDITIONAL REGCODE

        Python 2 Module 15 SP1 x86_64 (Activated)
        Deactivate with: SUSEConnect -d -p sle-module-python2/15.1/x86_64

        SUSE Cloud Application Platform Tools Module 15 SP1 x86_64 (Activated)
        Deactivate with: SUSEConnect -d -p sle-module-cap-tools/15.1/x86_64

        SUSE Linux Enterprise Live Patching 15 SP1 x86_64
        Activate with: SUSEConnect -p sle-module-live-patching/15.1/x86_64 -r ADDITIONAL REGCODE

        SUSE Package Hub 15 SP1 x86_64 (Activated)
        Deactivate with: SUSEConnect -d -p PackageHub/15.1/x86_64

        Server Applications Module 15 SP1 x86_64 (Activated)
        Deactivate with: SUSEConnect -d -p sle-module-server-applications/15.1/x86_64

            Legacy Module 15 SP1 x86_64 (Activated)
            Deactivate with: SUSEConnect -d -p sle-module-legacy/15.1/x86_64

            Public Cloud Module 15 SP1 x86_64 (Activated)
            Deactivate with: SUSEConnect -d -p sle-module-public-cloud/15.1/x86_64

            SUSE Linux Enterprise High Availability Extension 15 SP1 x86_64 (Activated)
            Deactivate with: SUSEConnect -d -p sle-ha/15.1/x86_64

                SAP Applications Module 15 SP1 x86_64 (Activated)
                Deactivate with: SUSEConnect -d -p sle-module-sap-applications/15.1/x86_64

            Web and Scripting Module 15 SP1 x86_64 (Activated)
            Deactivate with: SUSEConnect -d -p sle-module-web-scripting/15.1/x86_64

REMARKS

(Not available) The module/extension is not enabled on your RMT/SMT
(Activated)     The module/extension is activated on your system

MORE INFORMATION

You can find more information about available modules here:
https://www.suse.com/documentation/sles-15/singlehtml/art_modules/art_modules.html

**Comment by rjschwei** [comment]
libhwloc is part of the HPC module which is not part of the SLES For SAP product. Meaning we cannot built it into the images the package would not be able to be updated in case of a security issue.

This will have to be discussed with Product Management.

**Comment by schaefi** [comment]
Right, thanks Robert. The discussion is currently taken place and my latest information is that the needed package submissions are on its way. From here we can only wait for libhwloc to appear in SLES for SAP

**Comment by schaefi** [comment]
Package still does not exist in SLES for SAP. @rjschwei do you have any details ?

Thanks

**Comment by schaefi** [comment]
I was told this is available now. As we can't do anything about it here I'm going to close this issue.
