### ISSUE TITLE
SLES 15 SP1 boot going to emergency mode

### ISSUE THREAD

**Issue by vireddyc** [SUSE-Enceladus/azure-li-services#210]
Hi Team,

We have critical customer onboarding blocker they play major medical emergency role, OS Is booting fine with 6TB Blade, Same image is not working with 24TB(Going emergency mode). We have tried with Standard ISO Image and it is working fine.

Please find the attached file for boot logs, looks like boot partitions timeout. I have attached boot logs

Thanks,
Vidya  
[QuincySLES15Bootlogs_Server1.txt](https://github.com/SUSE-Enceladus/azure-li-services/files/4464546/QuincySLES15Bootlogs_Server1.txt)

**Comment by schaefi** [comment]
```
   Below is our testing and outcomes.


    1. We booted int SLES 15 SP1 Custom image for
       VLI(SLES15-SP1-SAP-Azure-VLI-BYOS.x86_64-1.0.5-Production-Build1.19
       )
    2. Server not booted and going emergency mode
    3. In emergency mode we have blacklisted these two modules â\200\234ioatdma
       and skx_edac"
    4. Server rebooted successfully
```

**Comment by schaefi** [comment]
Thanks for the testing. I wonder if blacklisting those modules has no other unwanted side effects ?
You said it only happens if you go beyond a certain ram boundary ?

**Comment by schaefi** [comment]
Target distro will be SLE15-SP1 and SP2 correct ?

**Comment by schaefi** [comment]
Also only needed for VLI as Lalit told me recently

**Comment by lalitb** [comment]
Yes, target distro needs to be SLES15-SP1 and beyond.
