### ISSUE TITLE
New images to have package libgcc_s

### ISSUE THREAD

**Issue by jaiawasthi** [SUSE-Enceladus/azure-li-services#218]
Hi Marcus,

All new images need to have the libgcc_s  package integrated into a new image as per SAP Note
"SAP Note 2593824 - Linux: Running SAP applications compiled with GCC 7.x"

Can you please accommodate the same in newer images.

Thanks !!

**Comment by schaefi** [comment]
what does "newer" images mean ? for which SLE is SAP applications compiled with gcc 7.x ?

Thanks

**Comment by schaefi** [comment]
Also there should be nothing to do from our side because libgcc_s1 vs libgcc_s1-gcc7 is pulled in when needed.

**Comment by schaefi** [comment]
So the question is basically if you need gcc7 in the image for compile jobs ?

```xml
<package name="gcc7"/>
```

This would be the instruction in the image description to get all of gcc7 into the image

* Is this what you need ?
* for which images SLE12/15 SP ?

Thanks

**Comment by jaiawasthi** [comment]
Yes, these are required for running some SAP applications
from sap note :
In order to run SAP applications which were compiled with GCC 7.x, a newer compiler version than originally delivered with RHEL 7 and SLES 12, additional runtime environment packages for GCC 7.x need to be installed before running such an SAP application. Otherwise, the SAP application no longer starts and it issues error messages such as:

/usr/lib64/libstdc++.so.6: version `GLIBCXX_<version>' not found (required by <application binary>)

 
By newer images i mean, all images that will be released in future, including both LI/VLI new / image refreshes

**Comment by schaefi** [comment]
>By newer images i mean, all images that will be released in future, including both LI/VLI new / image refreshes

This does not answer the question. For which code streams SLE 12/15 and starting at which SP ?

thanks

**Comment by schaefi** [comment]
Any news on this one ?

**Comment by schaefi** [comment]
Going to close this one due to no further information. Please open a new issue if the requested change gains more attraction again. Thanks
