### ISSUE TITLE
occasional drop to dracut rescue shell on first boot

### ISSUE THREAD

**Issue by jaiawasthi** [SUSE-Enceladus/azure-li-services#220]
Hi Marcus, 

We are intermittently seeing an issue with the sles12 sp4 image for LI systems [sles12_sp4_sap_azure_li_byos_x86_64_1_0_6_build1_110] where dracut startup is failing to start.
Below is the attached snapshot. 
![issue](https://user-images.githubusercontent.com/33454743/83797988-1e91ec00-a6c1-11ea-9fb5-0766248e6b0c.png)

We have a cron job of sorts which creates a new blade with this image every hour or so and that fails sometimes with this error.

**Comment by schaefi** [comment]
I'll look into this next week. You said it happens only sometimes.
This is hard to debug. What you need to do is run the process with
the following boot variables:

    rd.debug rd.kiwi.debug

If the problem appears it will drop you into a shell and from there
we could look at /run/initramfs/log/boot.kiwi and also on the console
messages printed.

With rd.debug there will be a ton of messages

**Comment by schaefi** [comment]
It seems this should be solved with the changes done in:

https://bugzilla.suse.com/show_bug.cgi?id=1174009
