### ISSUE TITLE
migration from sles15 to sles15 sp1 fails

### ISSUE THREAD

**Issue by lalitb** [SUSE-Enceladus/azure-li-services#224]
VLI Image: SLES15-SAP-Azure-VLI-BYOS.x86_64-1.0.5-Production-Build1.20.raw

$ zypper migration
Getting below error while migration :
---

All repositories have been refreshed.
Can't get available migrations from server: SUSE::Connect::ApiError: The requested products 'SUSE Cloud Application Platform Tools Module 15 x86_64, Containers Module 15 x86_64, Development Tools Module 15 x86_64, Legacy Module 15 x86_64, Public Cloud Module 15 x86_64, Web and Scripting Module 15 x86_64' have not been activated on the system.
'/usr/lib/zypper/commands/zypper-migration' exited with status 1

$

**Comment by rjschwei** [comment]
Using yast add the noted repositories to the system.

-> yast
Software -> Software Repositories
"F3" for "Add"
"Extensions and Modules from Registration Server"
