### ISSUE TITLE
unable to verify image signatures using SUSE public key

### ISSUE THREAD

**Issue by jaiawasthi** [SUSE-Enceladus/azure-li-services#229]
Hi Marcus, 

Opening an issue here as tracking in mail is a bit tedious 

Below are my observations for verifying signatures, please help me understand where im going wrong.
I have calculated the sha256 hashses of both the signature files as well as the image files, just to check if we are referring to same files.

jaawasth@blade-jb:/datadrive/jaawasth/images$ sha256sum SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.6-Production-Build1.2.raw.xz
96029c738b90682cff399125686540658f8b5f01d9486fd55ed0c40d71e60077  SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.6-Production-Build1.2.raw.xz
jaawasth@blade-jb:/datadrive/jaawasth/images$ sha256sum SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.6-Production-Build1.2.raw.xz.sha256.asc
c7e196fdc27117ad4f75b1892685f2b87440b8d91311e3dd8d36d993d86842a3  SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.6-Production-Build1.2.raw.xz.sha256.asc
jaawasth@blade-jb:/datadrive/jaawasth/images$ gpg --list-keys
/home/jaawasth/.gnupg/pubring.kbx

---------------------------------
pub   rsa2048 2013-01-31 [SC] [expires: 2020-12-06]
      FEAB502539D846DB2C0961CA70AF9E8139DB7C82
uid           [ unknown] SuSE Package Signing Key <build@suse.de>

jaawasth@blade-jb:/datadrive/jaawasth/images$ gpg --verify  SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.6-Production-Build1.2.raw.xz.sha256.asc SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.6-Production-Build1.2.raw.xz
gpg: Signature made Wed Jun 10 15:15:09 2020 UTC
gpg:                using RSA key 70AF9E8139DB7C82
gpg: BAD signature from "SuSE Package Signing Key <build@suse.de>" [unknown]

Thanks !!

**Comment by schaefi** [comment]
As Jesus pointed out the gpg command to verify the signature is the problem here. From my perspective the following sequence should work for you

```
$ wget SAS-URL-for-raw.xz image
$ wget SAS-URL-for-raw.xz.sha256.asc signature file

both files in the same directory

gpg --verify the-raw.xz.sha256.asc
```

That's it

@jesusbv please correct me when wrong, but this procedure worked for me

**Comment by jesusbv** [comment]
Yes, that is the procedure to verify the signature.

**Comment by schaefi** [comment]
Guess we made that clear. Please re-open if not, thanks

**Comment by jaiawasthi** [comment]
Hi Marcus,

>wget SAS-URL-for-raw.xz.sha256.asc signature file
We dont get a URL for signature files, instead we directly get the signatures in a file 


>both files in the same directory
yes

> gpg --verify the-raw.xz.sha256.asc
This gives below error 
jaawasth@blade-jb:/datadrive/jaawasth/logicapps$ gpg --verify SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.6-Production-Build1.7.raw.xz.sha256.asc
gpg: no signed data
gpg: can't hash datafile: No data


jaawasth@blade-jb:/datadrive/jaawasth/logicapps$ gpg --verify SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.6-Production-Build1.7.raw.xz.sha256.asc SLES15-SAP-Azure-LI-BYOS.x86_64-1.0.6-Production-Build1.7.raw.xz
gpg: Signature made Thu Jun 18 11:15:37 2020 UTC
gpg:                using RSA key 70AF9E8139DB7C82
gpg: BAD signature from "SuSE Package Signing Key <build@suse.de>" [unknown]


As you see I'm still getting the below error, please help

**Comment by schaefi** [comment]
>    As you see I'm still getting the below error, please help

Yes I agree and responded via e-mail. This was all my fault :/
You are missing a mandatory file to run the signature check.
See my mail for details
