### ISSUE TITLE
Printk timing issue

### ISSUE THREAD

**Issue by NitVijay** [SUSE-Enceladus/azure-li-services#233]
Background:

This is very old and complicated problem. Kernel historically tries to show
messages on the console ASAP. On the other hand, it does not want to block all
processes that need to print to the console in parallel. The result is that a
random process might spend a lot of time in handling console when other
processes add many messages in parallel.

There were many attempts to solve this by offloading the job to a kthread but
it was not acceptable upstream for a long time. The attitude has changed
recently but the solution is still not ready.

Some old SUSE kernels offloaded the console to a kthread. But it was removed
because it caused some issues, especially lost messages in some situations.

State:

The result is that the problem and workaround is the same on both SUSE and
RedHat.

Solution:

I see that the customer uses "splash=verbose" on the kernel command line. I
causes showing all messages on the console, including INFO level.

IMHO, in practice, is is even better to show only messages reporting some
problems. It means the levels: error, critical, alert, and emergency.

I suggest to use: splash=verbose loglevel=3

Real Solution:

The real solution is the offload to a kthread. But there are many details that
need to be solved upstream first. The historical attempts suggests that it
might take one or even more years before the real solution is ready.

*****************************************************************************************************

Above is the details about this issue where server hung observed And fix is pending from SuSe side. Currently below workaround is suggested by hardware vendor but we are looking for updated patch or image from SuSe which will not require any workaround on Servers

WORKAROUND:

	Edit "/etc/sysctl.conf" and set "kernel.printk" to read:
                kernel.printk = 3 4 1 7
	Then run "sysctl -p" to make the change effective

**Comment by rjschwei** [comment]
I think this is a first good image change for @KeithMnemonic to take a crack at

**Comment by KeithMnemonic** [comment]
@rjschwei @schaefi  is this just a matter of patching here for example https://github.com/SUSE-Enceladus/azure-li-services/blob/master/images/vli/sle12_sp5/config.kiwi#L26 ? and repeating for all of the li/vli images?

**Comment by schaefi** [comment]
@KeithMnemonic yes that's basically it and also the version of the image should change

**Comment by KeithMnemonic** [comment]
> @KeithMnemonic yes that's basically it and also the version of the image should change

@schaefi For the version update for the images in azurli-services, did you mean the version string in the kiwi file?  For example just go up to the next number? i.e. 1.0.7 for SLE15-sp1 and 0.0.24 for SLE12-sp4?

**Comment by KeithMnemonic** [comment]
issue resolved with https://github.com/SUSE-Enceladus/azure-li-services/pull/234

**Comment by NitVijay** [comment]
@schaefi - Can you please provide test image for validation ? And once it is validated then we will go for prod image for final validation

**Comment by schaefi** [comment]
testing images will be automatically available on schedule. Currently the automation kicks in every Friday. The window for today is already past due. If you need new testing images before next Friday let me know.

**Comment by NitVijay** [comment]
Yeah, Please provide it before,  if possible on monday so that we can validate it.

**Comment by schaefi** [comment]
@NitVijay done, an e-mail with information how to fetch the images has been sent out to azb...suse...@microsoft.com, I assume you are subscribed there. If not please head out to @jaawasth. This comment reaches you while I'm on vacation. Thus for further help please get in contact with @jesusbv 

Thanks

**Comment by NitVijay** [comment]
@schaefi - Yeah I have got it , Thanks.
