### ISSUE TITLE
Modify the sap-hana settings in OS

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#245]
Hi Marcus, 

We need to modify the sap hana settings in the OS.

New settings will be 
>net.ipv6.conf.all.disable_ipv6 = 1
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.rmem_default = 16777216
net.core.wmem_default = 16777216
net.core.optmem_max = 16777216
net.core.somaxconn = 4096
net.core.netdev_max_backlog = 300000
net.ipv4.tcp_rmem = 65536 16777216 16777216
net.ipv4.tcp_wmem = 65536 16777216 16777216
net.ipv4.tcp_max_syn_backlog = 16348
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.conf.all.rp_filter = 0
net.ipv4.tcp_dsack = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_syn_retries = 8
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.ip_local_port_range = 40000 65300
The sunrpc settings are not relevant for NFS4.1 anymore but we keep it for NFSv3 (oracle)
sunrpc.tcp_slot_table_entries = 128
sunrpc.tcp_max_slot_table_entries = 128
vm.swappiness=10
#For background information, see SAP Note 2205917 and 1557506
vm.pagecache_limit_mb = 0
vm.pagecache_limit_ignore_dirty = 1
vm.dirty_bytes = 629145600
vm.dirty_background_bytes = 314572800
vm.max_map_count = 2147483647
vm.memory_failure_early_kill = 1
fs.file-max = 820448174
kernel.shmmni = 524288
#SAP Note 1868829
fs.aio-max-nr = 18446744073709551615

These apply to all LI/VLI images.
Please include these changes in the next iteration of all version of images you will be releasing.

Thanks !!

**Comment by schaefi** [comment]
ok, will do

**Comment by schaefi** [comment]
Jai, please review. We will do a release together with the fix of #243

**Comment by jaawasth** [comment]
Thanks Marcus, reviewed, changes look good.
