### ISSUE TITLE
SLES15-SP1-SAP-Azure-VLI-BYOS.x86_64-1.0.7-Production-Build1.3.raw entered into grub mode after reboot 

### ISSUE THREAD

**Issue by balram2697** [SUSE-Enceladus/azure-li-services#258]
The System entered into grub mode on reboot after doing some configurations on the image SLES15-SP1-SAP-Azure-VLI-BYOS.x86_64-1.0.7-Production-Build1.3.raw. I have tried the same configuration on the same image earlier also ..and it worked out fine. 
Please find attached the screenshot from the RMC.
<img width="916" alt="1" src="https://user-images.githubusercontent.com/28356383/104213168-073b8e00-545c-11eb-8bae-3b31b55c5179.PNG">
<img width="918" alt="2" src="https://user-images.githubusercontent.com/28356383/104213154-04409d80-545c-11eb-837b-2682185b5a60.PNG">

**Comment by schaefi** [comment]
> The System entered into grub mode on reboot after doing some configurations on the image

I'm sorry but with the provided information it's not possible for me to:

a) guess what changes you have done on the image
b) get any idea why you land in the grub loop

Usually this is caused when system identifiers in the partition table or the filesystem has changed.

Please re-open this issue if you see the same problem with an original image delivered by us or start a private conversation with Jesus and/or me by e.g mail where you explain in detail what changes to the image were done.

Thanks
