### ISSUE TITLE
Kdump not working on Image "SLES12-SP5-SAP-Azure-LI-BYOS.x86_64-1.0.15-Production-Build1.1"

### ISSUE THREAD

**Issue by balram2697** [SUSE-Enceladus/azure-li-services#270]
Hello Marcus,

KDUMP test if failing on the above mentioned image. After kernel crash host is not coming up. 

Attaching snapshot of logs from the system after kernel crash.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/28356383/127360606-db8cc456-8bc1-405b-932a-8e723aa4a7fe.png)

Please have a look into this.

Thanks.

**Comment by jaawasth** [comment]
@schaefi , can you please help us here, we are not able to run kdump on any of the cisco servers with any of the new images.

**Comment by balram2697** [comment]
We are seeing major faults on the systems after kdump kernel crash.

Problem Details: 
Affected object : sys/chassis-1/blade-7/fabric-B/path-3/vc-2867 Description : fc VIF 2867 on server 1 / 7 of switch B down, reason: waiting for flogi
Affected object : sys/chassis-1/blade-7/adapter-3/host-eth-8 Description : Adapter ether host interface 1/7/3/8 link state: down
Affected object : sys/chassis-1/blade-7/adapter-3/host-eth-8/vif-2852 Description : Virtual interface 2852 link state is down

**Comment by balram2697** [comment]
@schaefi, can you please have a look into the issue.?

**Comment by rjschwei** [comment]
kdump is unrelated to the images as within the image we only consume functionality provided by packages. In this case please file a bug in bugzilla.suse.com such that we can involve the proper parties at SUSE that handle kdump functionality.

Thanks
