### ISSUE TITLE
Request to blacklist module "isst_if_mbox_msr" from Images

### ISSUE THREAD

**Issue by balram2697** [SUSE-Enceladus/azure-li-services#271]
Module "isst_if_mbox_msr" caused bootup hang issues on P&G servers. 

According to Suse Technical Support "It looks like this isst_if_mbox_msr module is related to Intel Speed Select. However, according to /proc/cpuinfo the CPU model is Intel(R) Xeon(R) Platinum 8276L, which does not even support Intel Speed Select [1]. Why load a module for which there is no CPU support for?"

As we don't have any hardware dependency on the module "isst_if_mbox_msr" we want to add a blacklist to a modprobe.d file for the installation images going forward.

**Comment by rjschwei** [comment]
This issue is being addressed via a bug report, bsc#1187196 on bugzilla.suse.com. The blacklisting will happen via package per conversation in the bug report. No image changes are necessary.
