### ISSUE TITLE
Runtime checker for extended config file validation

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/azure-li-services#56]
We need a runtime check, if storage is configured then we also need to handle storage authentication. This currently implies we need to have the 'ssh-private-key' entry in the YAML. This is related to discussion #42

**Comment by jeffaco** [comment]
I'd like to understand this:

You're saying that if we have storage configured (mounting NFS shares), then we MUST specify a key for storage?

If so, that's fine, but for test purposes we shouldn't REQUIRE this. We don't set this up on our test blades, as this requirement is setting dependent on the NetApp side. This would mean that, via YAML, there should be some way to override this behavior.

**Comment by schaefi** [comment]
@rjschwei I think this needs some clarification by you

Typically runtime checks are implemented if the features of the schema validation are not enough to check the condition. iirc in this case the runtime check would implement a dependency check between sections in the yaml config and that can't be done optional, either the check makes sense and is applied in any case or it does not make sense and should not exist.

Thanks

**Comment by schaefi** [comment]
Personally I don't think we need extended runtime checks in this project. I think the validation of providing enough data to operate is in the hands of the $MS team creating the config file. But let's wait for details by Robert

**Comment by rjschwei** [comment]
@schaefi Storage can only be setup if we have the private SSH key, otherwise the storage setup will fail. This is a dependency that cannot be expressed in the schema, thus IMHO we should have a runtime check to validate that we have the proper values to configure the storage.

However, as @jeffaco points out there are exceptions. I do not claim to understand the reason behind these exceptions. I will observe that based on experience, whenever things are tested out of context something will inevitably go wrong in production. But that is not our (SUSE) risk, nor do we (SUSE) have to deal with the customer calls.

Given the "exception", I am not in favor of implementing a work around to avoid what I would consider a necessary check, I think no work is needed here. If we get a config file that doesn't have the necessary information then storage setup will fail. As we write the log to the LUN that provides the config file we can hope that the person looking at the issue can figure out the problem.
