### ISSUE TITLE
VLI: ISO files vs. IMG files (Unable to boot ISO file as a USB Image)

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#79]
I'm looking at our VLI systems and how we'll be booting for legacy (Gen3) systems.

I am NOT able to boot an ISO file as a USB image. For virtual devices, I have three choices:

1. Floppy Image
2. ISO Image
3. HD/USB Image (under section "Hard disk/USB Key")

If I try to select an `.iso` file for USB Key, I get an error: "Invalid image file. Cannot redirect Hard disk/USB Key Image."

That error does NOT occur if I mount the .ISO file as an ISO image.

I'm unfamiliar with these imaging styles. How is a .IMG file different than a .ISO file? Can I convert from one to the other? Or can you provide a .IMG file that I can try to work with?

Thanks in advance.

**Comment by jeffaco** [comment]
Hi Marcus, welcome back from your vacation!

Unfortunately, I don't have physical access to these machines. So I'm not able to stick the USB stick into our legacy systems. Sorry! Any other suggestions?

**Comment by schaefi** [comment]
yeah my bad, sorry this was short thinking. Ok try the following:

* on some linux machine call

    ```
    qemu-img create mystick.img 8g
    dd if=our_image.iso of=mystick.img conv=notrunc
    ```

* use that mystick.img file as USB stick with your legacy (Gen3) system.

**Comment by schaefi** [comment]
Have not gotten that e-mail, but the suggestion sounds great to me.

Thanks for the heads up
