### ISSUE TITLE
LI Testing: Missing SuSEfirewall2 configuration

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#82]
We generally configure the SUSE firewall as follows:

```
# cat /etc/sysconfig/SuSEfirewall2 | grep 112
FW_SERVICES_EXT_TCP="22 53 3128 1128"
FW_SERVICES_EXT_UDP="53 1129"
```

I can get you more data (like the entire file) if needed, just let me know.

What's recommended practice these days for SUSE firewall configuration?

**Comment by schaefi** [comment]
> What's recommended practice these days for SUSE firewall configuration?

That can't be answered in general and depends on your network and the level of security. It seems you already know the list of ports to close or open. If this is a generic setup I'm happy to apply the file you will give me to our image build.

If it's dynamic data it would be another step in the system_setup service of this project

**Comment by schaefi** [comment]
> I think Robert wanted to avoid us using the call script mechanism

well yes because you can do basically everything, also nasty things :). But if you would tell us what scripts you want to call I'm sure we would find a common base. We have the service and so it should also be useful for some action

> I don't believe this is dynamic; we're just locking down ports in the firewall. Thanks.

In this case it's easy as it would end up in just another overlay file and I would agree with Robert that no scripts are needed

> Do you need the exact /etc/sysconfig/SuSEfirewall2

yes I would need that file and I would take it as is unmodified as overlay file. It will result in the image when built.

**Comment by rjschwei** [comment]
I just want to make sure the effects are understood.

If we bake the file into the image then if it needs modification Microsoft will have to file a bug and the turn around time is probably going to be a week, maybe more.

Given that we do have the "execute whatever you want" feature in the service, it may make snese to use that feature for the firewall setup.

However, we are certainly willing to back the firewall rules into the image build, as @schaefi has indicated.

**Comment by schaefi** [comment]
yes so all options were discussed, @jeffaco we just need a decision what's the best from your perspective. Thanks

**Comment by jeffaco** [comment]
It probably makes sense to get you the complete file. I don't think we change this with any frequency at all.

I've asked the PMs for it, and will let you know when I get it.

**Comment by jeffaco** [comment]
This guidance is actually coming from [SUSE documentation](https://www.suse.com/documentation/sles-for-sap-12/book_s4s/data/sec_s4s_configure_firewall.html).

That's why we're checking the specific ports allowed via UDP and TCP; we're just validating that the firewall is configured properly. I think this image isn't quite set up properly for SAP HANA, which is why our check failed (see first message I posted to this issue).

**Comment by schaefi** [comment]
ok so could you attach the file which is proven to do it right here ? I'm happy to add it to our image

**Comment by jeffaco** [comment]
Looks like we have slightly different files for HLI and VLI. HLI (UCS, what we're wrapping up now) is [here](https://1drv.ms/u/s!AtCDpQuLZQRZr2o4U-MlyErg-GbS), and VLI (what we're just getting started on) is [here](https://1drv.ms/u/s!AtCDpQuLZQRZr2uihPGcQpCCBxrv).

Let me know if you need anything further.

**Comment by schaefi** [comment]
Thanks I could access both files and put them to the appropriate image builds

**Comment by jeffaco** [comment]
I just wanted to verify: For VLI, do we have the additional ports open for SFS? For SFS, we need ports 3128 (TCP) and 53 (TCP & UDP) open in addition to the other (LI) ports. This is so that SFS can "phone home" with hardware issues.

We're going through VLI issues now that we're starting the VLI process, and this came up.

**Comment by schaefi** [comment]
The current firewall does not open 3128 and 53. Please open a new issue to address this. Please flag the subject with ```VLI: ...``` as it's specific to this target. Thaks
