### ISSUE TITLE
Timing issue with O/S deployment

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#93]
An issue came up as we're working with the O/S deployment that we have so far:

1. We deploy the O/S and configuration YAML and boot the system,
1. Once the system boots, since we have no visibility on when the configuration is complete, a co-worker actually automated removing the configuration LUN from the system after boot was detected. Since configuration wasn't complete, this caused a problem since the YAML file got yanked away.

Could we have one more feature:

1. Write a marker file to the configuration LUN showing that the cleanup mechanism is complete, and that the YAML is no longer needed (for automation), and
1. Since we have a means of communicating via that LUN, could a log file or other information be written to detect if the deployment was successful or unsuccessful?

This will allow us to automate the entire process of setting up network, storage, and compute, and detect any errors along the way.

Let me know, thanks.

**Comment by schaefi** [comment]
> Write a marker file to the configuration LUN showing that the cleanup mechanism is complete

Can be done, no problem

> Since we have a means of communicating via that LUN, could a log file or other information be written > to detect if the deployment was successful or unsuccessful?

I didn't understand that part. Deployment means you dump the image we gave you onto that lun. At that point in time no operating system is active.

**Comment by jeffaco** [comment]
To clarify: Right now, the only way to determine if something went wrong is to go to the console of the machine and see what the login banner has to say. In both HLI and VLI cases, this means manually connecting to the console (since the VNETs of the machine aren't accessible by us).

If the LUN will have a marker file showing that everything is complete (which is true when the cleanup phase is complete), then I thought that the LUN could also have some indication of if the O/S setup was successful or not. So, essentially, right now we look at `journalctl` to see what went wrong or not - is it possible to have this information also available to a file in the LUN?

The thought is:

1. Write a marker file that says "hey, everything works!". That file either would or would not exist when the marker file was created showing cleanup was completed.
1. If the "everything worked" file is not created (or even if it is), have a separate log file on the LUN that we could look at showing success/failure of each of the subsections.

Hope this clarifies what I have in mind.

By the way, I picked up the latest image (finally, sorry it took so long), and am installing it and testing it.

**Comment by schaefi** [comment]
Ah ok that was meant by you with deployment. Ok got it and yes that can be done too
