### ISSUE TITLE
Verify that CMCI is always disabled on SUSE images

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#94]
We came across a problem:

>When Correctable Machine Check Interrupt (CMCI) was enabled on the Operating system, it can cause the server to go into hung mode. Cisco has advised that a bug in CMCI, would read the correctable memory errors from hardware as genuine hardware failures, which slows down the server over a period of time and ultimately resulting in system going to hung mode.
>
>Cisco has recommended to disable the CMCI check on the OS end.
>
>This is Cisco’s link for more details :- https://bst.cloudapps.cisco.com/bugsearch/bug/CSCun84751.
>
>Cisco has also provided a SUSE KB article containing instructions on how to disable MCE or CMCI : https://www.suse.com/support/kb/doc/?id=7022118.

Can we insure that CMCI is always disabled on SUSE images?

**Comment by schaefi** [comment]
Ok I've read the articles and just to double check you want us to set the following kernel option permanently:

```
mce=ignore_ce
```

I've added that now to the image build. Please re-open if that's not what you expected

Thanks

**Comment by jeffaco** [comment]
This is absolutely needed for LI platforms. Jeff needs to engage HPE to see if VLI needs this as well. Re-opening until Jeff hears back from HPE, blocked waiting for HPE.

**Comment by jeffaco** [comment]
I heard back from HPE, this does NOT apply to HPE.

So: Please make this setting LI specific, this should NOT be set in VLI. If you would prefer that I mark this as closed and open a new issue to handle this, I can do so.

**Comment by rjschwei** [comment]
Since we have no VLI build at the moment there is nothing to do, we just need to remember than when we tackle VLI that we do not want this on the kernel command line. Another good argument for a second image build

**Comment by schaefi** [comment]
> If you would prefer that I mark this as closed and open a new issue to handle this, I can do so.

It's ok, please leave this open such that I can remember. Thanks

**Comment by schaefi** [comment]
ok VeryLarge image builds added without mce=ignore_ce setting

* Devel:PubCloud:Azure:ImagesSLE124P/SLES12-SP4-SAP-Azure-VLI-BYOS
* Devel:PubCloud:Azure:ImagesSLE12/SLES12-SP3-SAP-Azure-VLI-BYOS
