### ISSUE TITLE
Expose log file to LUN

### ISSUE THREAD

**Issue by schaefi** [SUSE-Enceladus/azure-li-services#96]
The complete log information to debug why the service deployment has failed can be obtained via:

```
systemctl status -l --all
```

To get that information a user needs to login to the machine and issue the command. Alternatively this could be done by the cleanup service which can try to write that information as file to the storage location from which the yaml file was provided.

I'll put that up for a discussion if we want to expose information from the host

**Comment by schaefi** [comment]
All of that information is also written to the ```/var/log/messages``` file which we also could consider to just copy on the LUN

**Comment by jeffaco** [comment]
The `/var/log/messages` file contains a **lot** more information which, arguably, not terribly useful for understanding why a deployment failed from a customization perspective.

For this reason, `systemctl status -l --all` seems like a better option.

Even better, though, might be just showing each of the services individually:

```
systemctl status azure-li-config-lookup
systemctl status azure-li-network
systemctl status -l azure-li-machine-constraints
...
```

**Comment by schaefi** [comment]
I think limiting the services log to only the services we wrote in the scope of azure large instance might not be enough to debug failure conditions. I can't construct a real life example right now but I'm sure there are cases in which an azure-li service fails but the reason for it lives in another area. It's very helpful to see the complete chain from start to end.

I would also assume that in case of failure that information will be passed along to us and from my perspective I would be interested in the complete deployment process instead of only a part of it.

Makes sense ?

**Comment by schaefi** [comment]
I'll prepare a pull request. We can discuss the scope of the log in code if necessary. Once done and merged I'll prepare a new image such that you can give it a test. As I don't have the hardware at hand it would be very nice if you can do a test with an intentional failure and send us the written log file. I'm very interested in the contents as they accumulate on your hardware.

This would also be helpful to convince myself we are doing the right thing here ;)

Thanks

**Comment by jeffaco** [comment]
No problem causing a failure. I can change the YAML version, and then try with something a little less drastic (like a bad line in the YAML file, or perhaps a GID that I know already exists).

It's easiest, in this sort of a case, to give me a checklist of what you'd like me to look at in particular. Then I can just run down the checklist.

**Comment by schaefi** [comment]
> No problem causing a failure

yeah that's easy isn't it :smile: 

From a checklist point of view I would just need the file

* workload.log

as it gets written to the lun
